### ISSUE TITLE
Request: ability to configure the analysis server

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23851]
We'd like to be able to configure the analysis server, in such as way that the configuration is associated/tied to a project.

There are a few things we'd like to configure, among other things:

* which directories should be ignored during analysis (blacklist)
* which warnings/hints should be displayed to a user
* a whitelist of directories to analyze (potentially)
* plugins (potentially)

Ideally, this configuration is human readable/writable, is machine readable/writable, is easy to extend, can be checked into source control, and is discoverable by the analysis server.

**Comment by sethladd** [comment]
Initial thoughts:

* a dot file lives at the root of the project
* YAML
* discovered by the analysis server automatically

**Comment by pq** [comment]
Here's a sample of the kind of format we've been discussing:
```
analyzer:
  ignore:
    - lib/foo.dart
    - 'test/data/*'
  disable:
    - error_id1
    - error_id2
linter:
  include: '**/src'
  rules:
    camel_case_types: true # shorthand for enabled: true
    new_lines:
      - enabled: true
      - chars: '\n'
```
Linter config ideas derived from https://github.com/dart-lang/linter/issues/41 and included just for context.  Consuming linter options will be the province of the linter.

The most salient bit is the idea that it's YAML and has a mapping from 'scopes' to options.

For further reference, here's where we parse options in `analyzer_cli`:
https://github.com/dart-lang/analyzer_cli/blob/master/lib/src/options.dart#L493 (look for OptionsFileParser)

And here's where the options format is defined for plugins:
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/plugin/options.dart

Regarding discovery by server, I think we should allow options to live at all "context roots" (e.g., next to a `pubspec` or `.packages` spec).  How about `.analysis_options` as the magic file name?
