### ISSUE TITLE
.analysis_options file exclusions should take into account context creation as well

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#23941]
When specifying exclusions in the `.analysis_options` file, I'd like it to take into account context creation too. So this file:

```yaml
analyzer:
  exclude:
    - 'test_package/**'
    - 'test_package_small/**'
    - 'test_package_bad/**'
    - 'doc/api/**'
    - 'pub.dartlang.org/**'
```

would exclude the above directories from analysis, _and_ indicate to the AS that we didn't want analysis contexts created there either. It was surprising to me that specifying the `test_package` above didn't prevent warnings from that dir; it was because the dir had a pubspec, and that context's potential exclusions overrode the one in the main pubspec.

Perhaps when scanning a dir for `pubspec.yaml` or `.packages` files, that list is filtered by any defined exclusions?
