### ISSUE TITLE
ToSourceVisitor drops ctor parameter annotations

### ISSUE THREAD

**Issue by kegluneq** [dart-lang/sdk#24578]
I know, I'm using code in `src/` which isn't public api, but I thought I'd file this anyway:

To repro, create `bin/main.dart`:
```
library main;

import 'package:analyzer/analyzer.dart';
import 'package:analyzer/src/generated/java_core.dart';

void main() {
  var writer = new PrintStringWriter();
  var visitor = new ToSourceVisitor(writer);
  var parsedCode = parseCompilationUnit(code);
  parsedCode.accept(visitor);

  var toSourceCode = writer.toString();
  if (!toSourceCode.contains('Annotation')) {
    print('My @Annotation is gone!');
  } else {
    print('Succeeded.');
  }
}

const code = '''
library test;

class TestClass {
  TestClass(@Annotation('a') String a);
}
''';
```

The result of running this is to print "My @Annotation is gone!", but "Succeeded." is expected.

-----------------------------------------------
pubspec.yaml:
```
name: test
dependencies:
  analyzer: any
```

pubspec.lock:
```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description: analyzer
    source: hosted
    version: "0.26.1+9"
  args:
    description: args
    source: hosted
    version: "0.13.2"
  charcode:
    description: charcode
    source: hosted
    version: "1.1.0"
  collection:
    description: collection
    source: hosted
    version: "1.1.3"
  csslib:
    description: csslib
    source: hosted
    version: "0.12.1"
  glob:
    description: glob
    source: hosted
    version: "1.0.5"
  html:
    description: html
    source: hosted
    version: "0.12.2"
  logging:
    description: logging
    source: hosted
    version: "0.11.2"
  package_config:
    description: package_config
    source: hosted
    version: "0.1.3"
  path:
    description: path
    source: hosted
    version: "1.3.6"
  plugin:
    description: plugin
    source: hosted
    version: "0.1.0"
  source_span:
    description: source_span
    source: hosted
    version: "1.2.1"
  string_scanner:
    description: string_scanner
    source: hosted
    version: "0.1.4"
  utf:
    description: utf
    source: hosted
    version: "0.9.0+2"
  watcher:
    description: watcher
    source: hosted
    version: "0.9.7"
  yaml:
    description: yaml
    source: hosted
    version: "2.1.7"
```

dart --version:
```
Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:28:05 2015) on "linux_x64"
```
