### ISSUE TITLE
Add .analysis_options support for `enableSuperMixins`.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#24750]
Straw-man:
```
analyzer:
  enableSuperMixins: true
```

@sethladd : are there other options we need while I'm at it?

**Comment by bwilkerson** [comment]
It might be nice to group all of the "enable language feature" flags in one place, kind of like we're doing with controlling error generation. Not sure what to call it; maybe "language"?

**Comment by pq** [comment]
That sounds good to me.  I feel somewhat inclined to leave `strong-mode` top-level (for backwards compatibility partly but also because it's kind of "meta").

```
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
```

Thoughts?
