### ISSUE TITLE
Segfault when passing Client to isolate with Worker package

### ISSUE THREAD

**Issue by astashov** [dart-lang/sdk#24941]
Steps to reproduce:
- Download the archive, unpack it:
  https://dl.dropboxusercontent.com/u/8489008/segfault.tar.gz
- Do `pub get`, then `dart main.dart`

On my machine it results in `Segmentation fault: 11`.

Dart version: `Dart VM version: 1.12.1 (Tue Sep  8 04:10:39 2015) on "macos_x64"`
OS version: `OS X 10.9.5`

Source code:

``` dart
import 'dart:async';
import 'package:http/http.dart';
import 'package:worker/worker.dart';

var worker = new Worker(poolSize: 4);

Future<Null> main() async {
  var client = new IOClient();
  var task = new HandleUploadTask(client);
  var result = await worker.handle(task);
  print(result);
}

class HandleUploadTask extends Task<Future> {
  final Client client;
  HandleUploadTask(this.client);

  Future execute() {
    return new Future.delayed(new Duration(seconds: 2), () => "foo");
  }
}
```

``` yaml
name: 'segfault'
version: 0.0.1
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: 0.11.3+2
  worker: 0.5.0
```
