### ISSUE TITLE
Support a draft compilation mode for faster development iteration

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#24951]
Although Dartium is great, sometimes it is necessary to test / develop on other browsers, and dart2js is painfully slow for interactive development.

I know DDC will eventually fix this use case, but I think there should be a way to skip some passes from dart2js in (optimize.dart)[https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/ssa/optimize.dart#L32) with a `-draft` compilation mode, even at the expense of execution speed and code size: I'd be happy to compromise with 20x slower & 10x larger code if it means I save 1 minute (out of 2) on each dev iteration.

This would be similar to GWT's [draftCompile](http://www.gwtproject.org/doc/latest/DevGuideCompilingAndDebugging.html) option.

**Comment by sigmundch** [comment]
There are some efforts in the dart2js backend that will make this easier in the future. Unfortunately the ssa-backend requires some of the optimizations to produce valid output, so we need to do a little refactoring first before we can add a flag like that.

Meanwhile, one thing you can try is to disable type inference by passing `--disable-type-inference`. Type inference is a big part of compilation times, but it also helps reduce the number of functions that end up being compiled. The more code we need to compile, the longer the compilation times, so it might not give you as much savings as you would like... Please give it a try and let us know how much that helps!

**Comment by ochafik** [comment]
`--disable-type-inference` doesn't seem to save much on a first try (TBC, but looks like 5 sec out of 2 minutes)

**Comment by ochafik** [comment]
So... since we wouldn't want `--disable-type-inference` set in release mode (pub build), would be *great* if we could have it set in debug (pub serve) only... (see similar request for Angular2: https://github.com/angular/angular/issues/5379)

```yaml
transformers:
- $dart2js:
    debug:
        environment:
            COMPILATION_MODE: "debug"
        commandLineOptions:
            - --disable-type-inference
            - --trust-primitives
            - --trust-type-annotations
            - --trust-primitives
            - --fast-startup # unless this makes the compilation slower
    release: {...}
    commandLineOptions: [...] # options common to both debug and release
```

WDYT?
