### ISSUE TITLE
Regression between 1.12.2 and 1.13.0 with angular1

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#25009]
I have a private angular1 project where `pub build` works with _1.12.2_ but fails with _1.13.0_. Here is the error I get:

```
Loading source assets... 
Loading di/module_transformer, initialize/build/loader_replacer, observe, smoke/src/default_transformer and initialize transformers... 
Loading angular transformers... 
Building xxx_admin... (1.2s) 
[Error from InjectorGenerator on xxx_admin|web/main.dart]:
Unable to resolve asset ID for "dart:core"
Build error:
Transform InjectorGenerator on xxx_admin|web/main.dart threw error: <rethrow>
Caused by Could not resolve dart:core
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6762:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6727:7)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2414:79)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3046:17)
#4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3077:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1192:58)
#6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:157:25)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158:10)
#10     _RootZone.runUnary (dart:async/zone.dart:1149)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#13     _Future._completeWithValue (dart:async/future_impl.dart:376)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


package:analyzer/src/generated/engine.dart 2115:11       AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 5304:98       AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 14327:50      ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6732:12       AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2414:79       AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3046:17       AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3077:14       AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1192:58       AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25  ResolverImpl._performResolve.<fn>.<fn>
dart:_internal/iterable.dart 413                         MappedListIterable.elementAt
dart:_internal/iterable.dart 219                         ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10  ResolverImpl._performResolve.<fn>
dart:async/zone.dart 1149                                _RootZone.runUnary
dart:async/future_impl.dart 502                          _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 585                          _Future._propagateToListeners
dart:async/future_impl.dart 376                          _Future._completeWithValue
dart:async/future_impl.dart 430                          _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                    _microtaskLoop
dart:async/schedule_microtask.dart 52                    _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                 _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 151                _RawReceivePortImpl._handleMessage

package:analyzer/src/generated/engine.dart 2115:11       AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 5304:98       AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 14327:50      ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6732:12       AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2414:79       AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3046:17       AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3077:14       AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1192:58       AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25  ResolverImpl._performResolve.<fn>.<fn>
dart:_internal                                           ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10  ResolverImpl._performResolve.<fn>


```

**Comment by a14n** [comment]
Here is a simpler reproduction that work with 1.12.2 and fails with 1.13.0:

**pubspec.yaml**

```yaml
name: xxx_admin
version: 0.0.1-dev
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  angular: ^1.0.0
transformers:
- angular
```

**web/main.dart**

```dart
import 'package:angular/angular.dart';
import 'package:angular/application_factory.dart';
void main() {
  applicationFactory().addModule(new Module()).run();
}
```

After a `pub get && pub build` I get the error:

```
[Error from InjectorGenerator on xxx_admin|web/main.dart]:
Unable to resolve asset ID for "dart:core"
Build error:
Transform InjectorGenerator on xxx_admin|web/main.dart threw error: <rethrow>
Caused by Could not resolve dart:core
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6762:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6727:7)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2414:79)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3046:17)
#4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3077:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1192:58)
#6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:157:25)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158:10)
#10     _RootZone.runUnary (dart:async/zone.dart:1149)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#13     _Future._completeWithValue (dart:async/future_impl.dart:376)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


package:analyzer/src/generated/engine.dart 2115:11       AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 5304:98       AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 14327:50      ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6732:12       AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2414:79       AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3046:17       AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3077:14       AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1192:58       AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25  ResolverImpl._performResolve.<fn>.<fn>
dart:_internal/iterable.dart 413                         MappedListIterable.elementAt
dart:_internal/iterable.dart 219                         ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10  ResolverImpl._performResolve.<fn>
dart:async/zone.dart 1149                                _RootZone.runUnary
dart:async/future_impl.dart 502                          _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 585                          _Future._propagateToListeners
dart:async/future_impl.dart 376                          _Future._completeWithValue
dart:async/future_impl.dart 430                          _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                    _microtaskLoop
dart:async/schedule_microtask.dart 52                    _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                 _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 151                _RawReceivePortImpl._handleMessage

package:analyzer/src/generated/engine.dart 2115:11       AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 5304:98       AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 14327:50      ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6732:12       AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2414:79       AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3046:17       AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3077:14       AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1192:58       AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25  ResolverImpl._performResolve.<fn>.<fn>
dart:_internal                                           ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10  ResolverImpl._performResolve.<fn>
```

**Comment by kevmoo** [comment]
@a14n have you tried `pub upgrade` on this project?

**Comment by a14n** [comment]
Same issue after a `pub upgrade`.

**Comment by kevmoo** [comment]
@a14n copy-paste your pubspec.lock file, if you could

**Comment by a14n** [comment]
Actually my above `pubspec.yaml` was not correct. I forgot the `intl` package that triggers the error only in _1.13.0_

But what is really bothering is that switching from _1.12.2_ to _1.13.0_ shouldn't fail a build! Is it correct ?

```
name: xxx_admin
version: 0.0.1-dev
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  angular: ^1.0.0
  intl: ^0.11.12
transformers:
- angular
```

With that my _pubspec.lock_ is:

```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description: analyzer
    source: hosted
    version: "0.22.4"
  angular:
    description: angular
    source: hosted
    version: "1.1.1"
  args:
    description: args
    source: hosted
    version: "0.12.2+6"
  async:
    description: async
    source: hosted
    version: "1.4.0"
  barback:
    description: barback
    source: hosted
    version: "0.15.2+7"
  browser:
    description: browser
    source: hosted
    version: "0.10.0+2"
  cli_util:
    description: cli_util
    source: hosted
    version: "0.0.1+2"
  code_transformers:
    description: code_transformers
    source: hosted
    version: "0.2.9+3"
  collection:
    description: collection
    source: hosted
    version: "0.9.4"
  csslib:
    description: csslib
    source: hosted
    version: "0.12.2"
  di:
    description: di
    source: hosted
    version: "3.3.5+1"
  html:
    description: html
    source: hosted
    version: "0.12.2"
  html5lib:
    description: html5lib
    source: hosted
    version: "0.12.1"
  intl:
    description: intl
    source: hosted
    version: "0.11.12"
  logging:
    description: logging
    source: hosted
    version: "0.9.3"
  observe:
    description: observe
    source: hosted
    version: "0.13.1+2"
  path:
    description: path
    source: hosted
    version: "1.3.7"
  perf_api:
    description: perf_api
    source: hosted
    version: "0.0.9"
  petitparser:
    description: petitparser
    source: hosted
    version: "1.5.0"
  pool:
    description: pool
    source: hosted
    version: "1.2.1"
  route_hierarchical:
    description: route_hierarchical
    source: hosted
    version: "0.6.2"
  smoke:
    description: smoke
    source: hosted
    version: "0.3.5"
  source_maps:
    description: source_maps
    source: hosted
    version: "0.10.1"
  source_span:
    description: source_span
    source: hosted
    version: "1.2.1"
  stack_trace:
    description: stack_trace
    source: hosted
    version: "1.5.0"
  utf:
    description: utf
    source: hosted
    version: "0.9.0+2"
  watcher:
    description: watcher
    source: hosted
    version: "0.9.7"
  when:
    description: when
    source: hosted
    version: "0.2.0"
  which:
    description: which
    source: hosted
    version: "0.1.3"
```
