### ISSUE TITLE
What can I put into _embedder.yaml ?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25011]
Can you add a comment with what the options are and maybe an example snippet? (this isn't a formal request for formal docs, but we'd like to use this in flutter and we're curious how to do it)

Thanks!

(part of https://github.com/dart-lang/sdk/issues/24733)

**Comment by pq** [comment]
Sure.

We process `_embedder.yaml` as if it were `.analysis_options` so all of those configurations are supported (and `embedder_libs` too).

For example:

```
embedder_libs:
  "dart:foobar": "../sdk_ext/entry.dart"
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
```

Lints could be added like so:

```
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - avoid_as
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - prefer_is_not_empty
    - slash_for_doc_comments
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
    # ...
```
