### ISSUE TITLE
Make DDC errors suppressible with analysis options.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25104]
The following configuration:
```
analyzer:
  strong-mode: true
  errors:
    dev_compiler.StaticTypeError: false
```
does not suppress `dev_compiler.StaticTypeError`s as expected because the DDC error code naming convention trips up our error suppression logic.

Ideally we can update the error codes to look like those produced by the analyzer (and this will just work).  Failing that, we can add special casing to our filtering logic.
