### ISSUE TITLE
Error suppressions not getting picked up from `_embedder.yaml`.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25102]
See: https://github.com/flutter/flutter/issues/624.

Net-net, adding this to flutter's `_embedder.yaml`, *should* suppress dev compiler static type errors but is not.
```
analyzer:
  strong-mode: true
  errors:
    dev_compiler.StaticTypeError: false
```
