### ISSUE TITLE
Embedder lints not being configured.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25115]
For example, this `flutter/lib/_embedder.yaml` does not enable `camel_case_types` (as expected).
```
analyzer:
  strong-mode: true
  errors:
    strong_mode_static_type_error: false
    unused_local_variable: false
  language:
    enableSuperMixins: true
linter:
  rules:
    - camel_case_types
```
