### ISSUE TITLE
Update error code validation to be strong-mode error-aware.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25117]
We'll need to do this in order to not get false negatives when validating .analysis_options files that suppress strong-mode warnings.

For example:

```
analyzer:
  strong-mode: true
  errors:
    strong_mode_static_type_error: false
```

is valid but the error validator will flag `strong_mode_static_type_error` since it's not in the `ErrorCode.values` enum.
