### ISSUE TITLE
Error when using transformers and dart-1.14.0-dev.7.0-1

### ISSUE THREAD

**Issue by luisvt** [dart-lang/sdk#25461]
when doing `pub serve` on a project that contains a transformer I get next error:

```
Unable to spawn isolate: Unhandled exception:
Load Error for "file:///tmp/tmpeYi8O_/dart-1.14.0-dev.7.0/dart/third_party/pkg/pub/bin/pub.dart": Error loading file:///tmp/tmpeYi8O_/dart-1.14.0-dev.7.0/dart/third_party/pkg/pub/bin/pub.dart:
  FileSystemException: Cannot open file, path = '/tmp/tmpeYi8O_/dart-1.14.0-dev.7.0/dart/third_party/pkg/pub/bin/pub.dart' (OS Error: No such file or directory, errno = 2)
#0      _asyncLoadErrorCallback (dart:_builtin:155)
#1      _asyncLoadError (dart:_builtin:566)
#2      _handleLoaderReply (dart:_builtin:383)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Operating System: Linux Mint 17.0

pubspec.yaml
```yaml
name: bootstrap_sass
version: 3.3.6
description: Sess source files to create bootstrap themes
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/luisvt/bootstrap_sass
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  sass: ^0.4.2
transformers:
- sass
```

The project was trying to use sass transformer to convert scss files into css.
