### ISSUE TITLE
Pub get error message on package resolution failure is incorrect

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#25499]
For a pubspec that looks like this:

```
name: lalala
description: Example of the analyzer singing
version: 0.0.1
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  services:
    git: https://github.com/dart-lang/dart-services.git
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
```

pub get fails with: 

```
Package test has no versions that match >=0.12.0 <0.13.0 derived from:
- sintr_code_analysis_example depends on version >=0.12.0 <0.13.0
```

This is incorrect. e.g. https://storage.googleapis.com/pub.dartlang.org/packages/test-0.12.7.tar.gz

This unfortunately falls into the category of one of the worst types of error message where the message from the system asserts something that isn't true, the contradiction is frustrating and it doesn't help the user construct a path to solving the problem.

Thanks for reading, if you need a hand looking at how we might better report the conflict graph to users, please ping.

```
pub --version
Pub 1.13.2

dart --version
Dart VM version: 1.13.2 (Tue Jan  5 06:36:44 2016) on "macos_x64"

```
