### ISSUE TITLE
Generics for Stream.transform

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#25860]
`Stream.transform` always returns `Stream<dynamic>`:
```dart
import 'dart:async';
import 'dart:io';

void main() {
  var input = new File("data/input.bin").openRead();
  var output = new File("data/output.bin").openWrite();
  output.addStream(input.transform(new MyTransformer()));
}

class MyTransformer implements StreamTransformer<List<int>, List<int>> {
  Stream<List<int>> bind(Stream<List<int>> stream) =>
      new Stream<List<int>>.eventTransformed(
          stream, (EventSink<List<int>> sink) => sink);
}
```
Strong mode warning:
```
WARNING: Unsound implicit cast from Stream<dynamic> to Stream<List<int>>
```

**Comment by zoechi** [comment]
Might be related to #25698

**Comment by vsmenon** [comment]
I think we need to just annotate `Stream.transform` as generic in the sdk.

**Comment by leafpetersen** [comment]
https://codereview.chromium.org/1808393002/ for DDC half of this.

**Comment by leafpetersen** [comment]
https://codereview.chromium.org/1815583002/ for the SDK half.

**Comment by zoechi** [comment]
I get the same error message for

```dart
  Map<String, SvgElement> _icons;

  List<String> get iconNames {
    final String iconSetPrefix = name == _iconSetRegistry.defaultIconSetName ? '' : '$name:';
    return _icons.keys.map((String id) => '$iconSetPrefix$id').toList();
  }
```
I think there is enough type information to derive that the result is `List<String>`

**Comment by leafpetersen** [comment]
@zoechi What version of the analyzer are you using?  I see no errors for:

```dart
Map<String, int> _icons;

List<String> get iconNames {
  final String iconSetPrefix = "hello";
  return _icons.keys.map((String id) => '$iconSetPrefix$id').toList();
}
```

**Comment by zoechi** [comment]
```yaml
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
linter:
  rules:
    - always_declare_return_types
#    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_return_types_on_setters
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - public_member_api_docs
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
    - package_names
```

> Dart VM version: 1.16.0-edge.b070d98f6ead4e420a71593f6a578e8a9d84f77d (Mon Mar 21 17:32:46 2016) on "linux_x64"
