### ISSUE TITLE
js-interop: Need to expose a Dart function as a JS function, but can't see how...

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/sdk#25905]
**Describe the issue you're seeing**

Attempting to get up a simple Google Maps sample using package/js

**Does it happen in Dartium or when compiled to JavaScript?**

I'm running with pub serve to Chrome 49.0.2623.63, so Dart2JS

* Dart SDK version: *use `dart --version`*

```bash
$ dart --version
Dart VM version: 1.14.2 (Tue Feb  9 23:13:17 2016) on "linux_x64"
```
* pkg/js version: *look at `pubspec.lock`*

```yaml
  js:
    description: js
    source: hosted
    version: "0.6.0"
```

Failing code: https://gist.github.com/domesticmouse/91681c0d684407fc67e1
