### ISSUE TITLE
EXCEPTION: type 'ShadowRootImpl' is not a subtype of type 'Element' of 'function 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25969]
This works fine in Chrome Version 49.0.2623.75 beta (64-bit)

but fails in Dartium Version 45.0.2454.0 (64-bit)

Dart VM version: 1.16.0-edge.6f6b345f751f14f61d348b3ea53df35828effe71 (Wed Mar  9 15:34:20 2016) on "linux_x64"

I have a few simple Angular components with `encapsulation: ViewEncapsulation.Native` and `<ng-content></ng-content>` inside a component with `encapsulation: ViewEncapsulation.Emulated`.

When I changed all elements to `encapsulation: ViewEncapsulation.Emulated` the exception didn't occur anymore.

```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.2"
  angular2:
    description:
      name: angular2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0-beta.9"
  args:
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3+6"
  async:
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  barback:
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+7"
  browser:
    description:
      name: browser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0+2"
  bwu_sass_transformer:
    description:
      path: "../bwu_sass_transformer"
      relative: true
    source: path
    version: "0.4.2"
  charcode:
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  cli_util:
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  code_transformers:
    description:
      name: code_transformers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  collection:
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  crypto:
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.1"
  csslib:
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2"
  dart_style:
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  dart_to_js_script_rewriter:
    description:
      name: dart_to_js_script_rewriter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0+4"
  fixnum:
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.2"
  func:
    description:
      name: func
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  glob:
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  html:
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2+1"
  intl:
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.7"
  logging:
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.2"
  observe:
    description:
      name: observe
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4"
  package_config:
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  path:
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.9"
  petitparser:
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.1"
  plugin:
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  pool:
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  protobuf:
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.0+1"
  smoke:
    description:
      name: smoke
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.6"
  source_maps:
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.1"
  source_span:
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
  stack_trace:
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.1"
  string_scanner:
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4+1"
  utf:
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+3"
  watcher:
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7"
  when:
    description:
      name: when
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  which:
    description:
      name: which
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  yaml:
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.8"
sdk: ">=1.14.0 <2.0.0"
```

> EXCEPTION: type 'ShadowRootImpl' is not a subtype of type 'Element' of 'function result'. in [item.children.isNotEmpty in BwuQuickNav@25:18]
> VM252:1 EXCEPTION: type 'ShadowRootImpl' is not a subtype of type 'Element' of 'function result'. in [item.children.isNotEmpty in BwuQuickNav@25:18](anonymous function) @ VM252:1
> VM252:1 ORIGINAL EXCEPTION: type 'ShadowRootImpl' is not a subtype of type 'Element' of 'function result'.(anonymous function) @ VM252:1
> VM252:1 ORIGINAL STACKTRACE:(anonymous function) @ VM252:1
> VM252:1 #0      BrowserDomAdapter.parentElement (package:angular2/src/platform/browser/browser_adapter.dart:224:40)
> # 1      moveNodesAfterSibling (package:angular2/src/platform/dom/dom_renderer.dart:307:20)
> # 2      DomRenderer.attachViewAfter (package:angular2/src/platform/dom/dom_renderer.dart:152:5)
> # 3      DebugDomRenderer.attachViewAfter (package:angular2/src/core/debug/debug_renderer.dart:86:27)
> # 4      AppViewManager_._attachViewToContainer (package:angular2/src/core/linker/view_manager.dart:374:21)
> # 5      AppViewManager_.createEmbeddedViewInContainer (package:angular2/src/core/linker/view_manager.dart:270:10)
> # 6      ViewContainerRef_.createEmbeddedView (package:angular2/src/core/linker/view_container_ref.dart:146:15)
> # 7      NgIf.ngIf= (package:angular2/src/common/directives/ng_if.dart:39:27)
> # 8      _BwuQuickNav_3.detectChangesInRecordsInternal (package:bwu_ng_quick_nav/bwu_ng_quick_nav.template.dart:935:34)
> # 9      AbstractChangeDetector.detectChangesInRecords (package:angular2/src/core/change_detection/abstract_change_detector.dart:151:12)
> # 10     AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:125:10)
> # 11     AbstractChangeDetector._detectChangesContentChildren (package:angular2/src/core/change_detection/abstract_change_detector.dart:236:12)
> # 12     AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:126:10)
> # 13     AbstractChangeDetector._detectChangesInViewChildren (package:angular2/src/core/change_detection/abstract_change_detector.dart:244:12)
> # 14     AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:128:10)
> # 15     AbstractChangeDetector._detectChangesInViewChildren (package:angular2/src/core/change_detection/abstract_change_detector.dart:244:12)
> # 16     AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:128:10)
> # 17     AbstractChangeDetector.detectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:111:10)
> # 18     ChangeDetectorRef_.detectChanges (package:angular2/src/core/change_detection/change_detector_ref.dart:209:14)
> # 19     ApplicationRef_.tick.<anonymous closure> (package:angular2/src/core/application_ref.dart:517:63)
> # 20     List.forEach (dart:core-patch/growable_array.dart:254)
> # 21     ApplicationRef_.tick (package:angular2/src/core/application_ref.dart:517:32)
> # 22     ApplicationRef_._loadComponent (package:angular2/src/core/application_ref.dart:484:10)
> # 23     ApplicationRef_.bootstrap.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_ref.dart:446:16)
> # 24     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135:26)
> # 25     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
> # 26     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135:14)
> # 27     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
> # 28     _rootRun (dart:async/zone.dart:891)
> # 29     _ZoneDelegate.run (dart:async/zone.dart:490)
> # 30     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
> # 31     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
> # 32     _CustomZone.runUnary (dart:async/zone.dart:798)
> # 33     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
> # 34     _Future._propagateToListeners (dart:async/future_impl.dart:637)
> # 35     _Future._completeWithValue (dart:async/future_impl.dart:424)
> # 36     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
> # 37     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
> # 38     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
> # 39     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
> # 40     _rootRun (dart:async/zone.dart:895)
> # 41     _ZoneDelegate.run (dart:async/zone.dart:490)
> # 42     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
> # 43     _CustomZone.run (dart:async/zone.dart:790)
> # 44     _CustomZone.runGuarded (dart:async/zone.dart:696)
> # 45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
> # 46     _microtaskLoop (dart:async/schedule_microtask.dart:41)
> # 47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
> # 48     _ScheduleImmediateHelper._handleMutation (dart:html:52073)
> # 49     MutationObserver._create.<anonymous closure> (dart:html:28753)
