### ISSUE TITLE
After removing `@deprecated` from a class, the analyzer info is still shown

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26176]
I removed `@deprecated` from a class but the analyzer still shows the info

> INFO: 'MyClass' is deprecated ([my_project] test/my_test.dart:26)

on 

``` dart
new MyClass();
```

`````` yaml
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
linter:
  rules:
    - always_declare_return_types
#    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_return_types_on_setters
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - public_member_api_docs
    - slash_for_doc_comments
#    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
    - package_names
```#

> Dart VM version: 1.16.0-edge.4b38c3dfc253aba0908611d8026a2151a78d9e9b (Thu Mar 31 21:51:56 2016) on "linux_x64"

Clicking `Reanalyze Dart Sources` in WebStorm fixes it.
``````
