### ISSUE TITLE
Analyzer CLI ignoring analysis options excludes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26212]
In WebStorm I don't get any errors shown, but from console I get

>  (polymer1) $ dartanalyzer --no-hints _/_*.dart
> Analyzing [bin/main.dart, lib/bwu_datagrid.dart, lib/libraries.dart, tool/grind.dart]...
> [warning] Unsound implicit cast from Rectangle<dynamic> to Rectangle<num> (/home/zoechi/dart/bwu_datagrid/lib/bwu_datagrid.dart, line 3402, col 36)
> [error] The setter 'index' is not defined for the class 'int'. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 140, col 22)
> [warning] Unsound implicit cast from Rectangle<dynamic> to Rectangle<num> (/home/zoechi/dart/bwu_datagrid/lib/bwu_datagrid.dart, line 3402, col 36)
> [warning] The argument type 'int' cannot be assigned to the parameter type 'String'. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 102, col 14)
> [lint] Name non-constant identifiers using lowerCamelCase. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 28, col 15)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 29, col 3)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 32, col 3)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 33, col 3)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 38, col 10)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 57, col 12)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 69, col 5)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 70, col 5)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 101, col 12)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 121, col 16)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 121, col 26)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 125, col 18)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 126, col 5)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 130, col 10)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 131, col 7)
> [lint] Specify type annotations. (/home/zoechi/dart/bwu_datagrid/lib/remote_model/remote_model.dart, line 149, col 10)
> 1 error, 3 warnings and 16 lints found.

``` yml
analyzer:
  strong-mode: true
  exclude:
  - lib/remote_model/**

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
#    - avoid_as
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - super_goes_last
#    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
    - package_names
```

> Dart VM version: 1.16.0-edge.95f37e03afcc58ce035d5587cffc5fe57f0232ba (Wed Apr  6 16:08:39 2016) on "linux_x64"

Source of the project (Polymer1 branch)
https://github.com/bwu-dart/bwu_datagrid/tree/polymer1
