### ISSUE TITLE
Dart2JS breaks code when minify flag is turned on

### ISSUE THREAD

**Issue by pstjvn** [dart-lang/sdk#26369]
I have updated to 1.16 last week and today I was trying to build for the web and to my surprise the code is not working.

When `minify` is false the code builds fine, but is not exactly production friendly

Here is the configuration:

``` yaml
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    csp: false
    sourceMaps: true
    checked: false
    # minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
```

When I enable minify the code compiles but does not run and the error is not helpful really:

```
Uncaught 
a @ js_helper.dart:1699
$0 @ async_patch.dart:522
jc @ schedule_microtask.dart:41
dart.lQ @ schedule_microtask.dart:50
$1 @ async_patch.dart:54
$0 @ js_helper.dart:2379
aq @ isolate_helper.dart:462
be @ isolate_helper.dart:54
jF @ js_helper.dart:2379
(anonymous function) @ js_helper.dart:2399
```

Also the code runs fine in Chromium.

I am not sure how to debug this further. The code sits in a private repo, but I can move it somewhere temporarily if this will help. 

Additional info:
When running pub server a warning is issued:

```
[Warning from Dart2JS on swagger_tools|web/main.dart]:
1 hint(s) suppressed in package:semver.
```

Other than that no error, warnings or other noticeable problems in the code (atom + dartlang plugin).
