### ISSUE TITLE
WARNING: 'overriden_field' is not a recognized lint rule ([bwu_datagrid] .analysis_options:28)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26611]
Since today I get 

> WARNING: 'overriden_field' is not a recognized lint rule ([bwu_datagrid] .analysis_options:28)

```yaml
linter:
  rules:
    - overriden_field
```

was this rule renamed, removed, ...?

> Dart VM version: 1.17.0-edge.6b6d363900373a56caa971b5610b3a0050ed55f6 (Thu Jun  2 17:30:30 2016) on "linux_x64"
