### ISSUE TITLE
int += int results in num cannot be assigned to int

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26912]
![image](https://cloud.githubusercontent.com/assets/405837/16942250/63e3b6a0-4d95-11e6-89a5-0d2dcf3ccb3f.png)

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
  - lib/remote_model/**

linter:
  rules:
    - always_declare_return_types
#    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
#    - public_member_api_docs
    - slash_for_doc_comments
#    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters # https://groups.google.com/a/dartlang.org/forum/#!topic/reviews/Q8D-mKoUVQA
    - unrelated_type_equality_checks
    - package_names
```
