### ISSUE TITLE
Default options-file for "pub serve" options

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#27626]
I know this is picky but e.g. in my case I always have to enter the following params to start
pub server:
```
pub server --port 8000 web
```

It would be cool to have something like .pub/config:
```
serve:
     port: 8080
     directories:
          - web
```
