### ISSUE TITLE
IntelliJ/Analysis server: Change analysis_options does not always refresh...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27961]
... your `Dart analysis` view of your project.

For example, I added:

```yaml
analyzer:
  exclude:
    - 'test/_data/**'
```

Add it took hitting the "refresh" button for errors in `test/_data` to go away.
