### ISSUE TITLE
Pull `linter` sources into third_party (or publish `analyzer`)

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#28139]
Currently there is no published `analyzer` package that is compatible with the `linter`.  Since Flutter imports the `linter` package and uses the `analyzer` in the SDK, this means we cannot update the Dart SDK in Flutter until we get this resolved.

The two solutions that come immediately to mind:

1. publish a compatible `analyzer`
2. pull `linter` sources into the SDK and reference them directly from Flutter

The first option might be expedient but only a stop-gap.

There is precedent to the second (we do this for `analyzer` and `front_end`).  

```
dependency_overrides:
  analyzer:
    path: ../../bin/cache/dart-sdk/lib/analyzer
  front_end:
    path: ../../bin/cache/dart-sdk/lib/front_end
```

The only hitch is that `linter` is in `third_party` and we'd need to decide where to put that source in the SDK.  Maybe create a `dart-sdk/third_party/lib` dir in the distro?

@bwilkerson @devoncarew @whesse 

FYI: @Hixie @abarth @danrubel
