### ISSUE TITLE
`constantValue` doesn't return a value for metadata

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28612]
I use this code with `source_gen`

```dart
abstract class MenuItem extends Serializable {
  MenuItemTarget target;
  Property<MenuItemTarget> get targetProperty;

  ...
}

@EnumClass()
class MenuItemTarget {}

class EnumClass {
  const EnumClass();
}
```
`constantValue` used to return a value, 

```dart
FieldElementImpl f = ...
final enumInstancee = f.type.element.metadata.single.constantValue;
```

but now I only get `null`. 

> Dart VM version: 1.23.0-edge.b27f5f910078d8a53cbfdb33663a50fa96812e5f (Thu Feb  2 00:04:28 2017) on "linux_x64"

I don't know with which version exactly this stopped working. 
I guess within ~2 weeks.

**Comment by bwilkerson** [comment]
@scheglov Is this related to the new driver?

**Comment by scheglov** [comment]
@bwilkerson I don't think it is. You don't use the new driver underneath unless you explicitly start using it.

**Comment by bwilkerson** [comment]
@kevmoo Did anything change recently in source_gen? I'm not aware of any changes in analyzer that would account for this change in behavior.

**Comment by kevmoo** [comment]
@zoechi can you upload your `pubspec.lock` file?

This isn't about the version of the SDK you have installed (or it shouldn't be) – it's all about which version of pkg/analyzer you have installed.

It'd be great to have a test in `pkg/source_gen` that reproduces what you're seeing...

**Comment by zoechi** [comment]
```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.29.5"
  angular2:
    description:
      name: angular2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0-alpha"
  angular2_components:
    description:
      name: angular2_components
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1-alpha"
  args:
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.7"
  async:
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.12.0"
  barback:
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+9"
  boolean_selector:
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  browser:
    description:
      name: browser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0+2"
  build:
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.3"
  build_barback:
    description:
      name: build_barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.3"
  build_runner:
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
  bwu_ng_mdl:
    description:
      path: "../bwu_ng_mdl"
      relative: true
    source: path
    version: "0.1.0"
  charcode:
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  cli_util:
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  code_builder:
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0-beta+3"
  code_transformers:
    description:
      name: code_transformers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  collection:
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.13.0"
  convert:
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  crypto:
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  csslib:
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3+1"
  dart_style:
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.15"
  dart_to_js_script_rewriter:
    description:
      name: dart_to_js_script_rewriter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  fhir_client_api:
    description:
      path: "../fhir_client_api"
      relative: true
    source: path
    version: "0.1.0"
  fixnum:
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.5"
  func:
    description:
      name: func
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
  glob:
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  google_maps:
    description:
      name: google_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.0+2"
  html:
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.1"
  http:
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+9"
  http_multi_server:
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  http_parser:
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  intl:
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0"
  isolate:
    description:
      name: isolate
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  js:
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
  js_wrapping:
    description:
      name: js_wrapping
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
  logging:
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+1"
  matcher:
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  meta:
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  mime:
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.3"
  observable:
    description:
      name: observable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.20.2"
  package_config:
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  package_resolver:
    description:
      name: package_resolver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  path:
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.1"
  perf_api:
    description:
      name: perf_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  plugin:
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  pool:
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  protobuf:
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.3"
  pub_semver:
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.2"
  quiver:
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.24.0"
  recase:
    description:
      name: recase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0+1"
  sass:
    description:
      name: sass
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  shelf:
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.7+2"
  shelf_packages_handler:
    description:
      name: shelf_packages_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  shelf_static:
    description:
      name: shelf_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  shelf_web_socket:
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  source_gen:
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.3+2"
  source_map_stack_trace:
    description:
      name: source_map_stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
  source_maps:
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.2"
  source_span:
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  stack_trace:
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  stream_channel:
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.1"
  string_scanner:
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  test:
    description:
      name: test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.18+1"
  typed_data:
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  utf:
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+3"
  uuid:
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.3"
  watcher:
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+3"
  web_socket_channel:
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  when:
    description:
      name: when
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  which:
    description:
      name: which
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  yaml:
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.12"
sdks:
  dart: ">=1.21.0 <2.0.0"
```
