### ISSUE TITLE
Possible issue in dart:io writing/closing race.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28737]
The test `standalone/io/named_pipe_script_test` is launching a subprocess via `dart /dev/fd/0` and writes the `main() { print("Hello, World!"); }` source code to the spawned process's stdin.

There was now a [flake](https://build.chromium.org/p/client.dart/builders/vm-mac-release-ia32-be/builds/17827/steps/vm%20tests/logs/stdio) where the spawned subprocess could not find `main`.

So I suspect our `dart:io` implementation might have closed the writing end of the stdin pipe to the subprocess before it has written all the data.

```
FAILED: none-vm release_ia32 standalone/io/named_pipe_script_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.fail('Unhandled exception:
NoSuchMethodError: No top-level getter 'main' declared.
Receiver: top-level
Tried calling: main
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:194)
#1      _getMainClosure (dart:_builtin:26)
')
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.fail (package:expect/expect.dart:154:5)
#2      main.<main_async_body>.<anonymous closure> (file:///b/build/slave/vm-mac-release-ia32-be/build/sdk/tests/standalone/io/named_pipe_script_test.dart:39:14)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#8      _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#9      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#10     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#11     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#12     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#17     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#18     _StreamController._add (dart:async/stream_controller.dart:635)
#19     _StreamController.add (dart:async/stream_controller.dart:581)
#20     _Socket._onData (dart:io-patch/socket_patch.dart:1682)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#24     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#25     _StreamController._add (dart:async/stream_controller.dart:635)
#26     _StreamController.add (dart:async/stream_controller.dart:581)
#27     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1249)
#28     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:783)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 xcodebuild/ReleaseIA32/dart --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-release-ia32-be/build/sdk/.packages /b/build/slave/vm-mac-release-ia32-be/build/sdk/tests/standalone/io/named_pipe_script_test.dart
Took 0:00:00.4484

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 standalone/io/named_pipe_script_test
```

This is a failure on mac which might make a difference (e.g. the default pipe buffer size might be different).

I haven't been able to reproduce this on linux

/cc @zanderso

**Comment by zanderso** [comment]
Yah, it looks like there could be race here.

Either _SocketStreamConsumer.close() should delay the actual close until its write buffer is empty (which would be my preference), or we need to do a big refactor to make all the write calls return Futures.

**Comment by zanderso** [comment]
The test still fails after adding the flush(), however I think the flush() is still necessary for the following reason.
- On starting the process, the parent end of the stdin pipe is added to the kqueue instance in the eventhandler
- The test does a write() on the IOSink, which can be buffered in _SocketStreamConsumer in socket_patch.dart until a WRITE event comes back from the eventhandler for the pipe.
- Without waiting for a flush() to complete, when we call stdin.close(), this ends up in a call to _StreamSinkImpl.close(), which calls _SocketStreamConsumer.close(), which closes the native socket, which closes the fd without even attempting to write the data that was buffered in the _SocketStreamConsumer.

However, this does not appear to have been the (only) problem causing the test to fail.

**Comment by eernstg** [comment]
Gardening: Same failure seen with `$mode == product` as shown in [this log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-mac-product-x64-be%2F9477%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fvm-mac-product-x64-be%2F9477%2F%2B%2F%2A%2A%2Fstderr). Adjusted status file to include that mode.

**Comment by mraleph** [comment]
This happened today again. 

```
FAILED: dartk-vm product_x64 standalone_2/io/named_pipe_script_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 974ms):
DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/named_pipe_script_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.fail('Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
')
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.fail (package:expect/expect.dart:269:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/named_pipe_script_test.dart:38:14)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#9      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#10     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#11     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#12     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#17     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#18     _StreamController._add (dart:async/stream_controller.dart:640:7)
#19     _StreamController.add (dart:async/stream_controller.dart:586:5)
#20     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#25     _StreamController._add (dart:async/stream_controller.dart:640:7)
#26     _StreamController.add (dart:async/stream_controller.dart:586:5)
#27     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1284:33)
#28     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m product -n dartk-mac-product-x64 standalone_2/io/named_pipe_script_test
```

**Comment by alexmarkov** [comment]
Happened once again:

```
 /====================================================================================\
 | standalone_2/io/named_pipe_script_test broke (Pass -> RuntimeError, expected Pass) |
 \====================================================================================/
 --- Command "vm" (took 515ms):
 DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/named_pipe_script_test.dart
 exit code:
 255
 stdout:
 unittest-suite-wait-for-done
 stderr:
 Unhandled exception:
 Expect.fail('Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
 ')
 #0      Expect._fail (package:expect/expect.dart:665:5)
 #1      Expect.fail (package:expect/expect.dart:275:5)
 #2      main.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/named_pipe_script_test.dart:42:14)
 #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
 #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
 #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
 #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
 #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
 #8      _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
 #9      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
 #10     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
 #11     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
 #12     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
 #13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
 #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
 #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
 #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
 #17     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
 #18     _StreamController._add (dart:async/stream_controller.dart:649:7)
 #19     _StreamController.add (dart:async/stream_controller.dart:595:5)
 #20     _Socket._onData (dart:io-patch/socket_patch.dart:1873:41)
 #21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
 #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
 #23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
 #24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
 #25     _StreamController._add (dart:async/stream_controller.dart:649:7)
 #26     _StreamController.add (dart:async/stream_controller.dart:595:5)
 #27     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
 #28     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
 #29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
 #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
 #31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
 #32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
 --- Re-run this test:
 python tools/test.py -n dartk-mac-product-x64 standalone_2/io/named_pipe_script_test
```
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8891766774310016176/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)
