### ISSUE TITLE
dart2js throws error for initializer list code that works fine in Dartium

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28780]
```
web/packages/fhir_designer/model/property_metadata.dart:15:37:
Not a compile-time constant.
            displayWidth != null && displayWidth >= 0 ? displayWidth : 35,
                                    ^^^^^^^^^^^^^^^^^
```
```dart
class PropertyMetadata {
  final String name;
  final String label;
  final String description;

  const PropertyMetadata({this.name, this.label, this.description});
}

abstract class InputPropertyMetadata extends PropertyMetadata {
  final int displayWidth;

  const InputPropertyMetadata(
      {String name, String label, int displayWidth: 35, String description})
      : displayWidth =
            displayWidth != null && displayWidth >= 0 ? displayWidth : 35,
        super(name: name, label: label, description: description);
}
```
```
Dart VM version: 1.23.0-edge.affb7865826160978c43a112b3da8c95cd22fb72 (Tue Feb 14 07:37:13 2017) on "linux_x64"
```

**Comment by rakudrama** [comment]
I can't reproduce the problem from the given information.
The code is in an abstract class. If I remove the 'abstract' and
instantiate the class as a const, I see no errors.

Can you isolate the concrete class and the const expression that uses this
code?
i.e. can you make a stand-alone program with this error?

**Comment by zoechi** [comment]
I just run into that `abstract` mistake after removing the expressions `dart2js` complained about (initial post),
but removing `abstract` didn't fix it for me.

Could it be related to
```yaml
- $dart2js:
#    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors

- test/pub_serve:
    $include: test/**_test.dart

- dart_to_js_script_rewriter
```
I'll try to create a minimal reproduction
