### ISSUE TITLE
List literals require type annotation

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29315]
![image](https://cloud.githubusercontent.com/assets/405837/24852832/3f85de5e-1dd9-11e7-8b42-8dff284a0beb.png)

This wasn't required until about 2 weeks ago.
Before it was derived from the content when possible. 
Is this an intentional change or a regression?

**Comment by bwilkerson** [comment]
@leafpetersen

**Comment by zoechi** [comment]
Perhaps it's related to some enabled linter rule.

I have 
```yml
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
and all linter rules enabled except
```yml
#    - always_specify_types
#    - avoid_as
#    - directives_ordering
#    - public_member_api_docs
```
