### ISSUE TITLE
enable using the analysis options file to configure the severity of lints

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29563]
Users should be able to configure the severity of lints using the analysis options file, the same as they can do for other analysis issues:

https://www.dartlang.org/guides/language/analysis-options#configuring-specific-rules-for-analysis

```yaml
analyzer:
  errors:
    annotate_overrides: warning
linter:
  rules:
    - annotate_overrides
```

We should investigate why this isn't working.

/cc @pq @bwilkerson
