### ISSUE TITLE
tons of errors from ddc

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29654]
[out.txt](https://github.com/dart-lang/sdk/files/1013795/out.txt)

Is this expected or am I doing something wrong?

I have a few (~20) lints from the angular_analyzer_plugin in templates, but otherwise no strong mode hints/warnings/errors 

**analysis_options.yaml**

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

**angular transformer**
```yml
- angular2/transform/codegen:
#    use_analyzer: true
    resolved_identifiers:
      BaseClient: 'package:http/http.dart'
      FhirConnection: 'package:fhir_client_api/fhir_client_api.dart'
      ResourceFactory: 'package:fhir_client_api/fhir_client_api.dart'
- angular2/transform/reflection_remover:
    $include:
      - web/designer.dart
      - test/webui/main_menu/main_menu_component_test.dart
    $exclude:
      - lib/code_generator/**
      - lib/app_code_generator/**
```
```
Dart VM version: 1.24.0-edge.547b2cdcceb29fdff0f5261a30f4fc8c1a7676ef (Fri May 19 02:11:41 2017) on "linux_x64"
```
[pubspec.lock.txt](https://github.com/dart-lang/sdk/files/1013807/pubspec.lock.txt)
