### ISSUE TITLE
Strange analyzer warnings in new Flutter project when modifying .analysis_options file

### ISSUE THREAD

**Issue by emshack** [dart-lang/sdk#29698]
I'm seeing some confusing dartanalyzer warnings from a new Flutter project, with different configurations of the .analysis_options file. I created a new project, then replaced the body of `main()` with
```
  Row row = new Row();
  print(row.mainAxisAlignment);
```
I also added a `.analysis_options` file with the following code:
```
analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
```
I don't see any errors with this configuration. However, when I comment out either one of the options in this file (or both), I now get the following dartanalyzer warning: 
```
WARNING: The getter 'mainAxisAlignment' isn't defined for the class 'Row'. ([myapp] lib/main.dart:5)
```
The Row widget does have a mainAxisAlignment getter, and regardless of whether I'm seeing any dartanalyzer warnings, the code successfully runs and prints out the correct mainAxisAlignment.

Also, this behavior seems to be flaky. It isn't always consistent when I do and do not get this error. However, it always eventually crops up when I paste in the [full default analysis options](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml) and start commenting out lines.

@Hixie @sethladd

**Comment by matanlurey** [comment]
I believe this issue is partially due to the fact that by default the language does not support super mixins - something I think `Row` uses.

When you disable that language feature but you are using libraries that require it you end up seeing seemingly nonsensical errors. 

We should either fix the errors to be more actionable OR at minimum warn when you are using depenencies that are using language features you don't have enabled.

Hopefully this problem goes away all together when it's enabled by default in a future version of Dart.

/cc @bwilkerson @devoncarew

**Comment by emshack** [comment]
Ah, interesting. Just to be clear, I am consistently seeing the error when my `.analysis_options` file looks like this, with super mixins enabled:
```
analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
```

**Comment by matanlurey** [comment]
Ah, you might have the same issue, but with `const` initializers. Could you try adding:

```yaml
analyzer:
    language:
        enableAssertInitializer: true
```

As well?
