### ISSUE TITLE
Show all quickfixes at once

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29821]
![image](https://user-images.githubusercontent.com/405837/26936860-174c81c0-4c70-11e7-92eb-a1f6de6dec3b.png)

To get the quick-fix to suppress the missing getter message, I first need to remove `dynamic`

```
info: Avoid annotating with dynamic when not required. (avoid_annotating_with_dynamic at [fhir_webui] lib/webui/button/remove_item_button_component.dart:29)
```
```
info:   (avoid_setters_without_getters at [fhir_webui] lib/webui/button/remove_item_button_component.dart:29)
```

```
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
```
Dart VM version: 1.24.0-dev.6.8 (Mon Jun  5 15:26:29 2017) on "macos_x64"
```
