### ISSUE TITLE
pub get fails with CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by drfischer** [dart-lang/sdk#30037]
I had to reinstall Dart after the running into incompatibilities with packages. Now, with a fresh installation

`Dart VM version: 1.24.2 (Thu Jun 22 08:55:56 2017) on "windows_x64"`

I cannot get the packages for my project which used to work until recently. `pub get` reports:

```
ERR : Handshake error in client (OS Error:
    | 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(ssl_cert.c:345))
```

I've tried the connection/certificate test posted in [#17664](https://github.com/dart-lang/sdk/issues/17664) and [#18929](https://github.com/dart-lang/sdk/issues/18929), but they seem to be OK:

```
Response certificate:
/C=US/O=Google Inc/CN=Google Internet Authority G2
/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.dartlang.org
2017-06-19 13:45:54.000Z
2018-06-18 00:00:00.000Z
```

My dart `pubspec.yaml` is:

```yaml
name: myproject
description: Some Description
version: 0.0.1
#homepage: https://www.example.com
author: Me

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: ^2.2.0
  ng_bootstrap: any
  plotly: any
  js: ^0.6.1
  _discoveryapis_commons: ^0.1.0
  crypto: ^0.9.0
  http: ^0.11.1
  http_server: ^0.9.5+1
  logging_handlers: ^0.8.0
  rpc: ^0.5.0
  csv: ^3.1.2
  sqljocky: '>=0.14.1'
  test: '>=0.12.20'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```

and the result of `pub --trace --verbosity all get` is in [pub.get.txt](https://github.com/dart-lang/sdk/files/1107842/pub.get.txt).
