### ISSUE TITLE
Hints not being ignored by analysis_options

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#30086]
Several hints, including at least `strong_mode_top_level_type_arguments` and `strong_mode_top_level_instance_getter`, can't be disabled by ignoring them in analysis_options. I've reproduced this against [this gist](https://gist.github.com/nex3/d67070b975c7c3a7a11c4868d0cb20db) as of Dart 1.25.0-dev.4.0.

**Comment by zakwanhaj** [comment]
@nex3 errors has to be on same strong-mode level, for example:

```yaml
analyzer:
  strong-mode: true
  errors:
    strong_mode_top_level_type_arguments: ignore
    ...
```
