### ISSUE TITLE
Analyzer CLI ignores analysis_options.yaml in some cases?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30206]
```yaml
analyzer:
 strong-mode: true
 errors:
   unused_element: error
   unused_import: error
   unused_local_variable: error
   dead_code: error

   # Allow importing .template.dart files without an analyzer error.
   uri_has_not_been_generated: ignore
```

The last line is the important one - AngularDart now has a requirement where users import a generated file in user code, and that breaks when you use the analyzer CLI to analyzer your source base (such as on travis).

I consider this a P1/potential blocker for AngularDart 4x being released externally.
