### ISSUE TITLE
Analysis options "exclude: ..." behavior suspect

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30231]
I am writing a package that has several "sub" packages for testing. For example:

```
my_package/
  package/
    has_strong_mode_error/
      lib/
        bad.dart
  lib/
    my_package.dart
  analysis_options.yaml
```

My `analysis_options.yaml` file looks ~ like this:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - package/**
```

My `bad.dart` file looks ~ like this:

```dart
void method() {
  var name = 'Kevin Moore';
  // Strong-mode exception: "A value of type 'int' can't be assigned...".
  name = 5;
  print(name);
}
```

When I open the project in IntelliJ, I see no errors, great! But when I open `bad.dart`, I see the error `error: A value of type 'int' can't be assigned to a variable of type 'String'. (invalid_assignment at [bad] lib/bad.dart:8)`. It then does not even go away when I close the file, I have to hit "Restart Analysis Server" for that to happen.
