### ISSUE TITLE
provide analysis errors and warnings of the pubspec.yaml file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#30324]
Companion issue here: https://github.com/flutter/flutter-intellij/issues/1259

Specifically, flutter users would get a lot of benefit from validations of the flutter assets section of the pubspec file.

```yaml
flutter:
  uses-material-design: true
  assets:
    - lib/gallery/example_code.dart
    - packages/flutter_gallery_assets/appbar_background.jpg
    - packages/flutter_gallery_assets/appbar/appbar_background_layer0.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer1.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer2.png
    - packages/flutter_gallery_assets/shrine/vendors/sandra-adams.jpg
    - packages/flutter_gallery_assets/shrine/vendors/zach.jpg
  fonts:
    - family: Raleway
      fonts:
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-Regular.ttf
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: AbrilFatface
      fonts:
        - asset: packages/flutter_gallery_assets/shrine/fonts/abrilfatface/AbrilFatface-Regular.ttf
```
