### ISSUE TITLE
`implicit-casts: false` doesn't appear to work as expected

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30391]
I'm sure I'm doing something wrong here, I'm sure I've seen it work before... however..

Given this code:

```dart
Object o = 1;

void main() {
  String s = o;
  print(s.length);
}
```

and this pubspec:

```yaml
name: danny
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

I expect a warning; but I don't currently get one (using the analysis server from SDK v1.24.2). When I run it, it fails with this:

```text
Unhandled exception:
type 'int' is not a subtype of type 'String' of 's' where
  int is from dart:core
  String is from dart:core

#0      main (file:///c:/Users/DTuppeny/Desktop/test/main.dart:4:12)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
