### ISSUE TITLE
Pub get fails when adding dart_to_js_script_rewriter dependency

### ISSUE THREAD

**Issue by Bikeman868** [dart-lang/sdk#30442]
I updated my development machine from Dart SDK 1.11.3 to 1.24.2 and have struggled for a couple of days to get my `pubspec.yaml` file updated correctly so that the code compiles again. My current yaml file is:

```
name: Urchin.ui
version: 1.0.0
description: User interface for configuring the rules in Urchin server
author: Martin Halliday
homepage: https://github.com/Bikeman868/Urchin
documentation: https://github.com/Bikeman868/Urchin/tree/master/Urchin.Server.Owin

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  dart_to_js_script_rewriter: any

transformers:
- $dart2js

```
This is the output from `pub get`:

```
Resolving dependencies...
+ args 0.13.7 (1.0.0 available)
+ async 1.13.3
+ barback 0.15.2+11
+ charcode 1.1.1
+ collection 1.14.3
+ csslib 0.14.0
+ dart_to_js_script_rewriter 1.0.3
+ html 0.13.2
+ logging 0.11.3+1
+ path 1.4.2
+ pool 1.3.1
+ source_span 1.4.0
+ stack_trace 1.8.0
+ utf 0.9.0+3
Downloading dart_to_js_script_rewriter 1.0.3...
Downloading html 0.13.2...
Downloading async 1.13.3...
Downloading collection 1.14.3...
Downloading barback 0.15.2+11...
Downloading pool 1.3.1...
Downloading csslib 0.14.0...
Downloading stack_trace 1.8.0...
The system cannot find the file specified.

  Command: C:\Program Files\Dart SDK\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
```
I wasn't getting this error before adding `dart_to_js_script_rewriter` to my yaml file as a dependency
