### ISSUE TITLE
Runtime "CastError" only when using DDC

### ISSUE THREAD

**Issue by BorisNaguet** [dart-lang/sdk#30567]
Hello,

Here is a simplified version of a project that execute correctly within Dartium (latest) and in Chrome (60.0.3112.113 64 bits on windows) with pub serve _without_ `dartdevc`, but not when compiled with DDC:

pubspecs.yml:
```yml
name: dart_tests
version: 0.0.1

environment:
  sdk: '1.24.2'

dependencies:
  angular: 4.0.0-beta
  http: 0.11.3+14
  dson: 0.9.0

dev_dependencies:
  browser: 0.10.0+2
  dart_to_js_script_rewriter: 1.0.3

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
```
index.html:
```html
<!DOCTYPE html>
<html>
<head>
    <script defer src="main.dart" type="application/dart"></script>
    <script defer src="packages/browser/dart.js"></script>
</head>
<body>
    <app></app>
</body>
</html>
```

sample.json:
```json
{
  "prop": "value"
}
```

main.dart:
```dart
import 'dart:async';
import 'package:http/http.dart';
import 'package:http/browser_client.dart';
import 'package:dson/dson.dart';
import 'package:angular/angular.dart';
import 'package:angular/core.dart';

abstract class AbstractRequest {
	Client _http = new BrowserClient();

	Future<T> GET<T>(String url, dynamic type) {
		Future<T> f = _http.get(url)
			.then(_getThen(type))
			.catchError(_catch);
		return f;
	}

	Function _getThen(dynamic type) {
		return (Response resp) {
			return type == null ? null : fromJson(resp.body, type);
		};
	}

	T _catch<T>(dynamic e) {
		print("Error $e - ${e.runtimeType}");
		throw e;
	}
}

class FileClient extends AbstractRequest {
	Future<Map> getFile() async {
		return await GET<Map>("sample.json", Map);
	}
}

@Component(
	selector: "app",
	template: """
	<div>
		{{message}}
		{{result}}
	</div>
	"""
)
class AppComponent implements OnInit {
	String message = "Result:";
	Map result;

	@override
	ngOnInit() async {
		result = await new FileClient().getFile();
	}
}

void main() {
	bootstrap(AppComponent);
}
```

When using DDC, here is the stacktrace:
```
dart_sdk.js:65009 EXCEPTION: CastError: Casting value of type '<T>(dynamic) -> T' to incompatible type 'ZoneUnaryCallback((Object) -> dynamic)'
STACKTRACE: 
dart:async            _Future.catchError
web__main.js 248:132  GET
web__main.js 276:40   FileClient.<fn>


-----async gap-----
dart:_runtime       async
web__main.js 68:19  AppComponent.ngOnInit


-----async gap-----
dart:_runtime                                         async
packages/angular/src/core/application_ref.dart 87:27  FutureOrOfComponentRef._check.appRef.run.dart.fn

ORIGINAL EXCEPTION: CastError: Casting value of type '<T>(dynamic) -> T' to incompatible type 'ZoneUnaryCallback((Object) -> dynamic)'
```
