### ISSUE TITLE
DDC: implicit-{casts|dynamic} applies transitively :(

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30810]
I thought there was a bug open, but I guess not or I missed it. Feel free to de-dupe.

Having the following configuration:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

... tries to enforce this configuration transitively, i.e. to your dependencies, that might not be clean enough to use these. For a simple reproduction case, try depending on `package:collection` or `package:path` and add the above to your `analysis_options.yaml`.
