### ISSUE TITLE
pub get / Resolving dependencies - again! (code_transformers / build_barback)

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31347]
This is what I get
```
Resolving dependencies... (5.2s)
Package code_transformers has no versions that match >=0.5.1 <0.6.0 derived from:
- build_barback 0.4.0+1 depends on version >=0.5.1 <0.6.0
- mobiad_rest_ui_mdl_mmui_jobedit_inplace_sample depends on version >=0.5.1 <0.6.0
```
Current version of code_transformer: https://pub.dartlang.org/packages/code_transformers#pub-pkg-tab-installing (0.5.1+3 )

This is my yaml
```yaml
name: mobiad_rest_ui_mdl_mmui_jobedit_inplace_sample
version: 0.0.1
description: MobiAd.REST.UI.MDL 'Test JOB-Inplace-Edit' sample
#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mobiad_rest_ui_mdl:
    path: ../..

  logging: any
  logging_handlers: any
  console_log_handler: any
  dice: ^1.7.0
    # path: /Volumes/Daten/DevLocal/DevDart/dice
  stack_trace: "^1.4.1"
  build: ^0.10.2+1
  build_barback: ^0.4.0+1
  code_transformers: ">=0.5.1 <0.6.0"
  sass: ^1.0.0-beta.2

dev_dependencies:

  git_version:
    path: /Volumes/Daten/DevLocal/DevDart/GitVersion

transformers:

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]
```
