### ISSUE TITLE
Cannot add more analysis options on top of an included one

### ISSUE THREAD

**Issue by yyoon** [dart-lang/sdk#31345]
(related to #31343, #31344)

For one Dart package, we were trying to use a common `analysis_options.yaml` file and only add more exclusion patterns, but it didn't work as expected.

[This works]
```yaml
analyzer:
  exclude:
    - 'testdata/directives_test/after.dart'
    - 'testdata/directives_test/before.dart'
    - 'testdata/double_quotes_test/after.dart'
    - 'testdata/double_quotes_test/before.dart'
```

[This doesn't work]
```yaml
include: ../analysis_options.yaml
analyzer:
  exclude:
    - 'testdata/directives_test/after.dart'
    - 'testdata/directives_test/before.dart'
    - 'testdata/double_quotes_test/after.dart'
    - 'testdata/double_quotes_test/before.dart'
```

This was happening in a fuchsia dart package, in case it matters.

cc: @pylaligand @zanderso @bwilkerson
