### ISSUE TITLE
The analysis exclude path base is from the source directory, not the package root

### ISSUE THREAD

**Issue by yyoon** [dart-lang/sdk#31344]
(related to #31343)

[The documentation](https://www.dartlang.org/guides/language/analysis-options#excluding-files) suggests that the exclude file paths are relative to the package root (seeing that `lib/client/piratesapi.dart` and `test/*_example.dart` are in the examples). However, we've noticed that the exclude pattern works only if the paths are relative to the source directory (i.e. `lib` or `test`).

[This works]
```yaml
analyzer:
  exclude:
    - 'testdata/directives_test/after.dart'
    - 'testdata/directives_test/before.dart'
    - 'testdata/double_quotes_test/after.dart'
    - 'testdata/double_quotes_test/before.dart'
```

[This doesn't work]
```yaml
analyzer:
  exclude:
    - 'test/testdata/directives_test/after.dart'
    - 'test/testdata/directives_test/before.dart'
    - 'test/testdata/double_quotes_test/after.dart'
    - 'test/testdata/double_quotes_test/before.dart'
```

This was happening in a fuchsia dart package, in case it matters.

cc: @pylaligand @zanderso @bwilkerson
