### ISSUE TITLE
glob pattern doesn't work correctly in the exclude section in analysis_options.yaml

### ISSUE THREAD

**Issue by yyoon** [dart-lang/sdk#31343]
When specifying exclude files in the `analysis_options.yaml` file, we've noticed that glob pattern doesn't work but specifying individual files works.

[This works]
```yaml
analyzer:
  exclude:
    - 'testdata/directives_test/after.dart'
    - 'testdata/directives_test/before.dart'
    - 'testdata/double_quotes_test/after.dart'
    - 'testdata/double_quotes_test/before.dart'
```

[This doesn't work]
```yaml
analyzer:
  exclude:
    - 'testdata/**'
```

This was happening in a fuchsia dart package, in case it matters.

cc: @pylaligand @zanderso @bwilkerson
