### ISSUE TITLE
analysis_options.yaml include seems to break the plugins data format

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#31469]
If I include a yaml file from my analysis_options, I can no longer seem to load plugins:

included.yaml
```
analyzer:
  plugins:
    angular:
      enabled: true
```

analysis_options.yaml
```
include: included.yaml
analyzer:
  plugins:
    angular:
      enabled: true
```

then the plugin will not load. Removing the include, or the entire `analyzer` section from one of the two files causes it to work again.

For giant projects that have a 'default' analysis_options.yaml file that includes the angular plugin, there is no way to extend those angular plugin options without completely copying the default yaml file, unfortunately.
