### ISSUE TITLE
question: How can I turn the analyzer warning "final_not_initialized_constructor_1" into an error?

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31629]
Or "undefined_identifier" which is also **JUST** a warning. I never get it how this could be a warning and not an error...
At least in strict_mode - these warnings should all become errors.

**Comment by zoechi** [comment]
add something like to your analysis_options.yaml

```
  errors:
    strong_mode_down_cast_composite: error
    const_eval_throws_exception: ignore
    unused_import: ignore
```

See also https://www.dartlang.org/guides/language/analysis-options
