### ISSUE TITLE
test fasta's patching logic

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31703]
We should have some unit tests for the patching logic in fasta

**Comment by sigmundch** [comment]
An idea I had in mind: 
* set up a package:testing chain like we do for our compile tests
* the chain works as follows:
   * there are 3 files for each individual test: foo.dart, foo_patch.dart, and foo.expect
   * the chain will create a memory file system that contains a libraries.json file with "dart:foo" using foo.dart as the URI and foo_patch.dart as the patch file (we could have more parts or patch files by using indices (foo_patch2.dart) or explicitly creating foo.json for each test).
   * the expected output `foo.expect` is not the text dump from kernel, but some variation of it that highlights the relevant pieces.

For example, we want to highlight the fileUri for every member, and when we have 2 uris, we want to indicate clearly which one is used to define the location of a node in the body of the method or the location of metadata. For example:

**bar.dart**:
```dart
external m1();

class A1 {
  @a2
  external m2();
  m3() => "body 3";
}
```

**bar_patch.dart**:
```dart
@patch
m1() => "body 1";

@patch
class A1 {
  @patch
  m2() => "body 2";
  m4() => "body 4";
}
```

generates **bar.expect**:
```dart
/*metadata location: bar_patch.dart*/ @patch
/*member location: bar.dart*/ m1() => /*body location: bar_patch.dart */ "body 1";

/* metadata location: bar_patch.dart */ @patch
/* class location: bar.dart */ class A1 {
   /*metadata location: bar.dart*/ @a2 /* metadata location: bar_patch.dart */ @patch
  /* member location: bar.dart */ m2() =>  /* body location: bar_patch.dart */ "body 2";
  /* member location: bar.dart */m3() => /* body location: bar.dart */ "body 3";
  /* member location: bar_patch.dart */ m4() => /* body location: bar.dart */ "body 4";
}
```

Or something more readable by creating our custom format that only shows what we want to see. For example, if we were only interested in the location of each member and their annotations and body, it could look like this:
```
- m1:
     declaration: bar.dart:1:1
     annotations:
      -  @patch - bar_patch.dart:1:1
     body: bar_patch.dart:2:8

- A1:
   declaration: bar.dart:3:1
     annotations:
      -  @patch - bar_patch.dart:4:1

   members:
     - m2:
       declaration: bar.dart:5:1
       annotations:
        -  @a2 - bar.dart:4:1
        -  @patch - bar_patch.dart:6:1
       body: bar_patch.dart:7:1

     - m3:
       declaration: bar.dart:6:1
       body: bar.dart:6:8

     - m4: 
       declaration: bar_patch.dart:8:1
       body: bar_patch.dart:8:8
```
