### ISSUE TITLE
Angular dart template can't get dependencies with dev pub.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#31724]
I just created an AngularDart Web App with Intellij's "generate sample content" (as instructed here: https://webdev.dartlang.org/guides/get-started).

When using the trunk version of the SDK (and I'm guessing also the `dev` releases) I can't even get the dependencies. Pub errors out:
```
ᐅ dart-sdk/bin/pub get
Resolving dependencies... (5.1s)
Package sass_builder has no versions that match >=1.0.1 <2.0.0 derived from:
- angular_components 0.8.0 depends on version ^1.0.1
```

/cc @kevmoo

**Comment by kevmoo** [comment]
I just ran through this w/ stagehand - v1.1.8

No problem – with Dart 2.0.0-dev.15.0

Would you try this on a released dev SDK and let me know if you still see it?

**Comment by zoechi** [comment]
there was an analyzer dependency override required 
I think this was fixed in the meantime

**Comment by floitschG** [comment]
The latest pub still fails on my angular example.

My program has the following pubspec:
```
name: Foo
description: Bar
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
```

That pubspec was generated by intelliJ through stagehand.
The pub from 1.24 can do a `pub get`.
The pub from trunk can't.

Since 1.24 can find dependencies, this is clearly a bug in pub of trunk.
Should I move this issue to the pub repository?
