### ISSUE TITLE
IntelliJ should show pubspec validation errors in-line in the yaml editor

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#31861]
We now have validation of items in pubspec.yaml files (like Flutter's asset section). We should report source ranges associated with these errors, so IDEs can show them in-context in an editor with underlines.

<img width="429" alt="screen shot 2018-01-11 at 8 57 20 am" src="https://user-images.githubusercontent.com/1269969/34836679-7a3b0f62-f6ad-11e7-9089-e872ce1c1208.png">

**Comment by devoncarew** [comment]
Nevermind; we are reporting locations for the errors. I suspect that IntelliJ is not showing them properly for yaml file?

/cc @jwren @alexander-doroshko

**Comment by alexander-doroshko** [comment]
You are right, currently, we highlight errors only in Dart and HTML files. It should be easy to add YAML to the list. How can I test it?

**Comment by devoncarew** [comment]
You should be able to add this:

```
flutter:
  uses-material-design: true
  assets:
    - assets/missing_asset.png
    - assets/dartconf.png
    - assets/google_la_map.png
    - assets/app.token.txt
```

to any pubspec. You'll need `2.0.0-dev.15.0` or later. If that doesn't work, then opening a Flutter project and adding a reference to a missing asset should do it.
