### ISSUE TITLE
dartanalyzer doesn't report missing dartdocs anymore

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31905]
At some point between last August and now, the dartanalyzer stopped reporting missing dartdocs even if you have the right lints enabled.

**Comment by Hixie** [comment]
To reproduce:

```dart
// a.dart
void test() { }
```
```yaml
// a .yaml
linter:
  rules:
    - package_api_docs
    - public_member_api_docs
```
```bash
dartanalyzer --options a.yaml a.dart
```
