### ISSUE TITLE
Consider making sdk/lib/libraries.yaml extensible

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32048]
We should look into making it easier to define multiple, yet similar, configurations in `sdk/lib/libraries.yaml`. In particular, flutter currently contains a modified clone of this file.

**Comment by zanderso** [comment]
Is this the mechanism that embedders would use rather than updating CFE source to add new dart: libraries? If so, I would urge a (much) higher priority for this issue---the bar for creating new embeddings of the VM is already too high. If not, could you add some text about what problem this is solving.

**Comment by sigmundch** [comment]
As far as the format goes, one of my motivations for using names for each target in the original design was exactly for this reason: to make it easy to extend and override the definition of one target with another.

For example:

```yaml
vm:
  async: ...
  io: ...
  convert: ...
  isolate: ...
  mirrors: ...

flutter:
  extends: vm  # inherit all definitions from the vm target
  ui: ...      # add more `dart:` libraries
  mirrors: ... # override some `dart:` libraries (for example, to disallow them)
```

**Comment by peter-ahe-google** [comment]
To support flutter, I think the extension mechanism should look like this:

```
flutter:
  extends:
    path: ".../sdk/lib/libraries.yaml"
    name: "vm_common"
  libraries:
    ui: ...
```

If the extension mechanism supports paths, then we can also split the yaml file into multiple files, one for each major backend: VM, dart2js, and DDC.
