### ISSUE TITLE
RangeError due to Analyzer plugin

### ISSUE THREAD

**Issue by akaufmann** [dart-lang/sdk#32096]
I don't know if this is caused by the Angular Analyzer plugin but as soon as I add this plugin to the Analyzer options I get various error messages like:

```bash
RangeError (byteOffset): Invalid value: Not in range 0..77956, inclusive: 101728
#0  _ByteDataView.getUint32 (dart:typed_datapatch/dart:typed_data/typed_data_patch.dart:4021)
#1  BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2  BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54)
#3  StringReader.read (package:front_end/src/base/flat_buffers.dart:662)
#4  Reader.vTableGet (package:front_end/src/base/flat_buffers.dart:644)
...
```

```bash
RangeError (index): Invalid value: Valid value range is empty: 0
#0  List.[] (dart:core-patch/dart:core/array.dart:133)
#1  _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1025)
#2  _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:963)
#3  SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:256)
#4  _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:275)
...
```

Here is my analysis_options.yaml:

```yaml
analyzer:
  strong-mode: true
  plugins:
    angular:
      enabled: true

    # foo:
    #   enabled: true

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
```

If I add a dummy plugin to it like `foo` I get no errors and the plugin (Angular Analyzer) works again.

```bash
angular_analyzer_plugin:
    version: "0.0.12"

analyzer:
    version: "0.31.0+1"

dart:
    version: "2.0.0-dev.20.0"

--------------------------------
macOS: 
    version: "10.12.6"
```
