### ISSUE TITLE
dartanalyzer should fail if analysis_options.yaml has a syntax error

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/sdk#32126]
# Overview
Running the dart analyzer passes successfully even when there is a syntax error in the analyis_options.yaml file in use. This is problematic since it then basically ignores the settings in the yaml file and does not find strong mode and lint errors and warnings. If you're running the analyzer in CI, the point is to prevent lint or errors from being merged into master. 

This came about when setting some of the strong mode sub-options, but leaving true in the `strong-mode: true` line. An example follows:

# To Reproduce

`analysis_options.yaml`

```yaml
analyzer:
  strong-mode: true # << This is the problem
    implicit-casts: true
    implicit-dynamic: false
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    # ... more lint rules 
```

If you run dart analyzer with this analysis_options.yaml file, it passes happily when I feel like it should fail. Bonus points for validating against a schema and printing warnings or hints to check things that are valid syntax, but aren't going to work correctly with the analyzer (wrong indentation, typos, etc)
