### ISSUE TITLE
Shorter syntax for hosted dependencies on a different pub server

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/sdk#32201]
# Overview

It's rather cumbersome and repetitive to specify hosted dependencies that are on a different server than the main public server. Let's take a look at how a dependency is declared currently

```
dependencies:
  my_package_name:
    hosted:
      name: my_package_name # duplicated information in this dependency
      url: https://pub.domain.com  # duplicated information across multiple dependencies
    version: ^2.1.0
  my_package_name2:
    hosted:
      name: my_package_name2  # duplicated information in this dependency
      url: https://pub.domain.com  # duplicated information across multiple dependencies
    version: ^1.2.3
```

As you can see, there is a lot of duplicated information, careful indentation and key names to remember or copy and paste to add a new hosted dependency. The minimal needed information is the dependency **name**, **pub server name**, and **version**. 

# Proposal
```
dependencies:
  browser: ^0.10.0 # Comes from the main public pub server. pub.dartlang.org
  rxdart@pub.dartlang.org: ^0.15.0 # Also comes from the main public pub server. pub.dartlang.org
  my_package_name@pub.domain.com: ^2.1.0 # Comes from a private hosted pub server
  my_package_name2@pub.domain.com: ^1.2.3
```
In this scenario, the fact that it is a hosted dependency and the https scheme can be inferred.
If the `@pub.domain.com` is left off, then the default public pub server would be defaulted.
