### ISSUE TITLE
Have a plan for replacements for strong-mode options that will be deprecated

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32661]
This is a "discussion" issue for now...but we should figure this out.

Guessing we want to keep the `implicit-` flags.
Guessing we want to deprecate (And eventually remove) the `strong-mode` parent.

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

CC @kwalrath @dgrove
