### ISSUE TITLE
Error on line 15, column 8 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?    http: "^0.11.3+16"        ^

### ISSUE THREAD

**Issue by gowsikraja** [dart-lang/sdk#32759]
I have facing the above issue while **Get dependencies** .

**pubspec.yaml**

dev_dependencies:
  test: ^0.12.0
  http: "^0.11.3+16"
  image: "^1.1.30"

**Error message** 

Running "flutter packages get" in dart_demo...
Error on line 15, column 8 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
   http: "^0.11.3+16"
       ^
pub get failed (65)

**Comment by zoechi** [comment]
This means that the formatting (indentation) of the content in your `pubspec.yaml` is invalid.

You'd need to post the content of `pubspec.yaml` wrapped in ``` for anybody to be able to provide advice.

**Comment by gowsikraja** [comment]
I'm not getting . I'm new for Dart lang. pls find `pubspec.yaml` below

```
name: dart_demo
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
  http: "^0.11.3+16"
  image: "^1.1.30"
```
