### ISSUE TITLE
document plugins in analysis_options.yaml

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#32826]
Now that David is working on another plugin, we should document how they work on the dart site to avoid confusion.

It can look like:

```yaml
analyzer:
  plugins:
    - my_package
```

or

```yaml
analyzer:
  plugins:
    my_package:
      my_custom: options
```

where my_package exports an analysis plugin. For someone who wants to do _that_, we should probably ask them to file an issue so that we can advise them and/or approve their use case etc. @bwilkerson  does that sound good to you?

Otherwise, we could maybe just link to a plugin that exists as an example, such as the angular plugin, and not really make it look like something someone can "just write" since it is pretty nontrivial and that API is still subject to change.

For instance, the angular plugin looks like:

```yaml
analyzer:
  plugins:
    angular:
      enabled: true
      custom-tag-names:
        - foo
        - bar
      custom-events:
        foo:
          type: Foo
          path: 'package:bar/baz.dart'
```

but the `enabled: true` is something I added more or less on accident and I should remove the need for.

This is why it'd be good to document centrally -- rather than having others' go off of my code which may contain mistakes for backwards compatibility purposes.

**Comment by bwilkerson** [comment]
> For someone who wants to do that, we should probably ask them to file an issue so that we can advise them and/or approve their use case etc.

I'm not sure why. If we're going to support customizing plugins (and I think angular requires that we do) then we should just support it everywhere. What's your thinking here?

And we should document what the expected form is when you want to mix the two. User's obviously can't write
```
analyzer:
  plugins:
    - package_1
    package_2:
      custom: value
```
so what value do we expect to see after `package_1:`?

**Comment by MichaelRFairhurst** [comment]
Good questions brian.

For the issue about plugins, I mean to say users should file a ticket if they are interested in making a plugin at all, not just if they want to provide config. I'll edit my original writeup to make that less fuzzy.

For mixing the two...I think "true" would be reasonable?

```
  plugins:
    package_1: true
    package_2:
      custom: value
```

Or we could switch to (as we discussed earlier)

```
  plugins:
    - package_1
    - package_2

package_1:
  custom: value
```

?

**Comment by bwilkerson** [comment]
The second alternative is an interesting possible solution to an issue raise in an e-mail thread: that of sharing configuration data when there are two possible ways to load a plugin:
```
analyzer:
  plugins:
#    - angular
    - angular_analyzer_plugin
angular_analyzer_plugin:
  custom-tag-names:
  ...
```
With the new API, plugins can find the options file from the context roots, so parsing custom options should be easy. The downside of top-level custom options is the potential for conflicts.
