### ISSUE TITLE
pause_on_unhandled_async_exceptions_test is failing on bot but not locally

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#33365]
After the sync-async became the default the `pause_on_unhandled_async_exceptions_test` is failing on the bot but not locally.
Seems to need the optcounter flag.

For example see
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-linux-release-x64-reload-rollback-be%2F11004%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout
or
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-linux-release-ia32-optcounter-threshold-be%2F10967%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout

```
python tools/test.py -m release -a ia32 --builder-tag optimization_counter_threshold --vm-options --optimization-counter-threshold=5 service/pause_on_unhandled_async_exceptions_test
python tools/test.py -m release -a ia32 --checked --builder-tag optimization_counter_threshold --vm-options --optimization-counter-threshold=5 service/pause_on_unhandled_async_exceptions_test
```

Error:
```
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --no-preview-dart-2 --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --async_debugger --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions_test.dart
exit code:
255
stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseIA32/dart -DDART_SERVICE_USE_AUTH=false --pause-isolates-on-unhandled-exceptions --profiler --no-preview-dart-2 --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --async_debugger --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions_test.dart
>testee>out> Observatory listening on http://127.0.0.1:42804/
** Signaled to run test queries on http://127.0.0.1:42804/
>testee>out> 
Loading VM...
Done loading VM
Running pause_on_unhandled_async_exceptions_test.dart [1/2]
Paused with PauseException
Running pause_on_unhandled_async_exceptions_test.dart [2/2]
We stopped!
** Killing script
Unexpected exception in service tests: Expected: contains '.dart:34'
  Actual: 'pause_on_unhandled_async_exceptions_test.dart:29:13'
#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions_test.dart:51:5)
<asynchronous suspension>
#4      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:331:23)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#9      Future._propagateToListeners (dart:async/future_impl.dart:667)
#10     Future._completeWithValue (dart:async/future_impl.dart:482)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
stderr:
Unhandled exception:
Expected: contains '.dart:34'
  Actual: 'pause_on_unhandled_async_exceptions_test.dart:29:13'
#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions_test.dart:51:5)
<asynchronous suspension>
#4      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:331:23)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#9      Future._propagateToListeners (dart:async/future_impl.dart:667)
#10     Future._completeWithValue (dart:async/future_impl.dart:482)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
--- Re-run this test:
python tools/test.py -m release -a ia32 --checked --builder-tag optimization_counter_threshold --vm-options --optimization-counter-threshold=5 service/pause_on_unhandled_async_exceptions_test
```
