### ISSUE TITLE
Analyzer complains about missing asset if you specify a folder in pubspec.yaml for Flutter

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#33550]
Flutter introduced the ability to specify asset directories (and just include all files) instead of needing to specify all files as of https://github.com/flutter/flutter/pull/16413

This has now landed in beta.

So I can do this:

```yaml
  assets:
    - assets/
    - assets/w3samples/
    ...
```

instead of 

```yaml
  assets:
    - assets/flutter.svg
    - assets/dart_logo.svg
    - assets/w3samples/aa.svg
    ...
```

However, the analyzer now gives me warnings in this case that the asset is not found:

> warning • The asset assets/ does not exist • pubspec.yaml:36:7
warning • The asset assets/w3samples/ does not exist • pubspec.yaml:37:7

**Comment by dnfield** [comment]
Is there some way to tell the analyzer to ignore this in `analysis_options.yaml` or `pubspec.yaml`?  I tried  `# ignore_for_file: asset_does_not_exist` to no avail.  Also tried setting that to ignore in `analysis_options.yaml` but that complains it doesn't exist.

**Comment by dnfield** [comment]
Hah - I was looking at the code and became confused cause it seemed like it should work .. and that's because the PR was merged in yesterday https://github.com/dart-lang/sdk/commit/d895b4913420036b24110376367946f6195f478b

**Comment by dnfield** [comment]
This ignores it for now - in analysis_options.yaml

```yaml
analyzer:
  errors:
    # allow for asset_does_not_exist
    unrecognized_error_code: ignore
    # ignore this in pubspec.yaml
    asset_does_not_exist: ignore
```
