### ISSUE TITLE
Confusing messages with await_only_futures, unnecessary_parenthesis and futures with ternary operator

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33655]
```yaml
linter:
  rules:
    - await_only_futures
    - unnecessary_parenthesis
```

```dart
import 'dart:async';

main() async {
  bool cond = true;
  await (cond ? Future<void>.value(true) : Future<void>.value(true));
  await cond ? Future<void>.value(true) : Future<void>.value(true);
}
```

I'm sure one of those `await` lines should be valid, but the first one warns `Unnecessary parenthesis can be removed.` and the second one warns `Await only futures.`. I think one of them may be wrong?
