### ISSUE TITLE
dartanalyzer --options not honored

### ISSUE THREAD

**Issue by Kleak** [dart-lang/sdk#33753]
Dart version and OS
- Dart VM version: 2.0.0-dev.66.0 (Unknown timestamp) on "linux_x64"
- linux

[Here](https://gitlab.com/kleak/coverage_playground) is a repos where you can  repros it.

Step:
- clone the repos
- run `tools/pre_commit.sh`

What is expected:
file ending in `.g.dart` should be excluded since it's in the analysis_options.yaml

What happen:
file ending in `.g.dart` are not excluded

here is the call to dartanalyzer
`dartanalyzer --options=analysis_options.yaml --fatal-hints --fatal-warnings .`
and in the analysis_options.yaml i have 
```yaml
analyzer:
  strong-mode: true
  plugins:
    - angular
  exclude:
    - test/**/*.g.dart
```
