### ISSUE TITLE
Error: Method not found: 'KernelBuilder'

### ISSUE THREAD

**Issue by Marco87Developer** [dart-lang/sdk#33964]
I’m developing my web app with **AngularDart 5** and **Dart 2**. `pubspec.yaml` file is:

```
environment:
  sdk: '>=2.0.0-dev.69.2 <2.0.0'

dependencies:
  sass_builder: ^2.1.1
  angular: ^5.0.0-beta+2
  angular_components: ^0.9.0-beta+1
  angular_forms: ^2.0.0-beta+2
  angular_router: ^2.0.0-alpha+17
  js: ^0.6.1+1
  path: ^1.6.2

dev_dependencies:
  angular_test: ^2.0.0-beta+2
  build_runner: ^0.9.2
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  test: ^1.3.0
```

Some details:
* Dart SDK Version: **2.0.0-dev.69.2**
* OS: **Windows 10**
* Browser: **Chrome**

The **_error message_** is the following:
```
webdev failed with an unexpected exception.
Unable to spawn isolate: file:///C:/Users/marco/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/build_web_compilers-0.4.1/lib/builders.dart:24:36: Error: Method not found: 'KernelBuilder'.
Builder ddcKernelBuilder(_) => new KernelBuilder(
                                   ^^^^^^^^^^^^^
file:///C:/Users/marco/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/build_web_compilers-0.4.1/lib/builders.dart:25:5: Error: No named parameter with the name 'summaryOnly'.
    summaryOnly: true,
    ^^^^^^^^^^^
```

How can be solved this issue?

Thanks,
Marco.
