### ISSUE TITLE
Can't load Kernel binary (Dart SDK dev.69.4)

### ISSUE THREAD

**Issue by Marco87Developer** [dart-lang/sdk#34017]
I have a problem after updating the Dart SDK.

* Dart SDK Version: 2.0.0-dev.69.4
* OS: Windows 10
* Browser: Chrome 68

The following is my `pubspec.yaml` file:
```
environment:
  sdk: '>=2.0.0-dev.69.4 <2.0.0'

dependencies:
  sass_builder: ^2.1.1
  angular: ^5.0.0-beta+2
  angular_components: ^0.9.0-beta+2
  angular_forms: ^2.0.0-beta+2
  angular_router: ^2.0.0-alpha+17
  js: ^0.6.1+1
  path: ^1.6.2

dev_dependencies:
  angular_test: ^2.0.0-beta+2
  build_runner: ^0.9.2
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  test: ^1.3.0
```

I runned `pub global activate webdev` and `pub upgrade` commands. After this, I runned `webdev serve`, but I received the following error message:
```
Can't load Kernel binary: File size is too small to a valid kernel file.
webdev failed with an unexpected exception.
Unable to spawn isolate: Error while initializing Kernel isolate
```

How can I solve this issue? Thanks!
