### ISSUE TITLE
dartanalyzer seems to ignore `exclude` entry

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#34053]
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "macos_x64"

Even with the following `exclude` entry in the `analysis_options.yaml` file, the CLI analyzer still reports issues over `*.g.dart` files. No such errors are reported in WebStorm.

```yaml
analyzer:
  exclude: [build/**, test/*.g.dart]
```

```console
> dartanalyzer --fatal-warnings . # cwd: examples/ng/doc/toh-6
[11:38:36] Analyzing toh-6...
  lint • Unnecessary new keyword at test/app_po.g.dart:117:22 • unnecessary_new
  lint • Unnecessary new keyword at test/dashboard_po.g.dart:106:22 • unnecessary_new
  lint • Unnecessary new keyword at test/dashboard_po.g.dart:119:22 • unnecessary_new
  lint • Unnecessary new keyword at test/hero_search_po.g.dart:82:22 • unnecessary_new
  lint • Unnecessary new keyword at test/heroes_po.g.dart:200:22 • unnecessary_new
  lint • Unnecessary new keyword at test/heroes_po.g.dart:213:22 • unnecessary_new
  hint • The value of the field '__mouse__' isn't used at test/app_po.g.dart:73:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/dashboard_po.g.dart:63:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/hero_po.g.dart:74:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/hero_search_po.g.dart:52:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/heroes_po.g.dart:118:19 • unused_field
6 lints and 5 hints found.
```

This is run over the following example code: https://github.com/angular-examples/toh-6

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
Thanks @zoechi!

Btw, using `exclude: [build/**, '**/*.g.dart']` also doesn't help (the CLI analyzer still processes `*.g.dart` files).

**Comment by zoechi** [comment]
There was a mention in one of the linked issues that imported packages still are analyzed even when excluded and that `// ignore_for_package: ...` is the best way.

I have for example in `build.yaml`
```yml
      built_value_generator|built_value:
        generate_for:
          include: ["lib/src/model/**.dart", "lib/src/client/state/**.dart"]
        options:
          header: |+
            // GENERATED CODE - DO NOT MODIFY BY HAND

            // ignore_for_file: avoid_catches_without_on_clauses
            // ignore_for_file: lines_longer_than_80_chars
```
