### ISSUE TITLE
pub upgrade never end

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#34217]
Dart SDK: 1.24.3

```yaml
name: TestProject
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=1.0.0'

dependencies:
  path: any
  http: any
  crypto: any
  matcher: any
dev_dependencies:
  test: any

```
