### ISSUE TITLE
The dartanylzer doesn't see generated files

### ISSUE THREAD

**Issue by enyo** [dart-lang/sdk#34240]
Dart 2.0.0

When I work on my angular app, all seems fine in my IDE, no warnings or errors. But when I run `dartanalyzer .` in my project directory, I get countless errors like this:

```
error • Target of URI hasn't been generated: 'overview/overview_component.template.dart' at lib/src/web/admin/angular/app/dashboard/dashboard_component.dart:17:8 • uri_has_not_been_generated
```

The file **does** exist however (in `.dart_tool/build/etc...`).

**Comment by enyo** [comment]
This is my `analysis_options.yaml`:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
  plugins:
    - angular
  # errors: # Not activated
  #   uri_has_not_been_generated: ignore
```

If I add the `uri_has_not_been_generated: ignore` config, then the errors are ignored, but I get errors due to implicit casts (since the dartanalyzer then doesn't know the classes I'm trying to use)
