### ISSUE TITLE
(pub) Feature Request: Allow importing library which dart root is in a git repo sub-directory

### ISSUE THREAD

**Issue by orbli** [dart-lang/sdk#34588]
Have just known from gitter.im that it is impossible to import a library from sub-directory of a git repo.

I am not trying to act against the idea of dart file structure, but there could be a need (e.g. I'm working on an universal API library using gRPC) for multiple-languaged git repo to use dart for part of it. (Maybe later I will work on some test projects initiating by dart-flutter)

My suggestion is having an optional field in pubspec.yaml to contain "DART_ROOT". Default is "/" (the root of git repo).

**Comment by zoechi** [comment]
Not exactly sure what you are asking for but I think it is

```yaml
dependencies:
  kittens:
    git:
      url: git://github.com/munificent/cats.git
      path: path/to/kittens
```
which was added several months ago

See also https://www.dartlang.org/tools/pub/dependencies#git-packages
