### ISSUE TITLE
Show missing @required params as an error rather than a warning

### ISSUE THREAD

**Issue by StokeMasterJack** [dart-lang/sdk#34718]

**Comment by a14n** [comment]
You can control that in `analysis_options.yaml`:

```yaml
analyzer:
  errors:
    missing_required_param: error
```
