### ISSUE TITLE
js-interop: WebApp in release mode returns runtime errors

### ISSUE THREAD

**Issue by Hexer10** [dart-lang/sdk#34875]
I'm trying to build in release mode  my dart webApp, and it builds without any errors, but when I press a button that should call this function `jQuery('#loginModal') as ModalElement).modal('show');` it gives this error in the console:
```
Uncaught TypeError: ((w.event.special[a.origType] || {}).handle || a.handler).apply is not a function
    at HTMLDivElement.dispatch (jquery-3.3.1.slim.min.js:2)
    at HTMLDivElement.v.handle (jquery-3.3.1.slim.min.js:2)
    at Object.trigger (jquery-3.3.1.slim.min.js:2)
    at HTMLDivElement.<anonymous> (jquery-3.3.1.slim.min.js:2)
    at Function.each (jquery-3.3.1.slim.min.js:2)
    at w.fn.init.each (jquery-3.3.1.slim.min.js:2)
    at w.fn.init.trigger (jquery-3.3.1.slim.min.js:2)
    at r.t.show (modal.js:117)
    at HTMLDivElement.<anonymous> (modal.js:515)
    at Function.each (jquery-3.3.1.slim.min.js:2)
```
I've included the jQuery CDN in the .html page, but it doesn't work.
This happens only when the app is built in release mode (dart2js) and not when in development (dartdevc).

JS Interop code:
```dart
@JS()
library js_helper;

import 'package:js/js.dart';

@JS('\$')
external dynamic jQuery(query);

@JS()
@anonymous
class ModalElement {

  external dynamic modal(String call);
  external dynamic on(String event, Function callback);

}
```

Dart Version : `Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"`
pubspec.yml:
```
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.3+17
  js: ^0.6.0

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <0.5.0'

```
