### ISSUE TITLE
dart:html type error while adding event listener 

### ISSUE THREAD

**Issue by drbcode** [dart-lang/sdk#35047]
index.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <script defer src="index.dart.js"></script>
</head>
<body>
</body>
</html>
```

index.dart:
```dart
import 'dart:html' as html;

void main(){
  var listener = html.window.onMouseMove.listen((e) {})
    ..onData((e) {
      var messageData = {
        'y': e.client.y,
        'x': e.client.x,
      };
      print('message data is ${messageData}');
    });
}
```

pubspec.yaml:
```yaml
name: crash_test
version: 0.0.1
description:
homepage:
documentation:
author:
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:

dev_dependencies:
  build_runner: any
  build_web_compilers: any
```

build.yaml:
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - --csp
```

steps to reproduce:
```sh
pub run build_runner build --output build
```
Run above command then open `build/web/index.html` then see console output, it will display this message:

```
js_helper.dart:1763 Uncaught Error: TypeError: Closure 'main_closure0': 
type '(MouseEvent) => Null' is not a subtype of type '(Event) => void'
    at Object.wrapException (js_helper.dart:1763)
    at Object.functionTypeCheck (js_helper.dart:3783)
    at Object.main (html_dart2js.dart:35700)
    at index.dart.js:5209
    at index.dart.js:5193
    at index.dart.js:5204
    at index.dart.js:5212
```

Above issue is resolved after passing these arguments to dart2js:
```yaml
dart2js_args:
            - --fast-startup
            - --minify
            - --omit-implicit-checks
            - --trust-primitives
            - --csp
```
