### ISSUE TITLE
Analyzer plugin should support relative path dependencies

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#35281]
(with `dart-2.1.0`)
Creating a analysis server plugin I used a relative path dependency in the bootstrap package. When I tried to use the plugin nothing worked (no analysis error, no error that the plugin loading failed).

As the bootstrap package is copied in `~/.dartServer/.plugin_manager` the relative path is wrong from this place.

Perhaps the path dependencies should be rewriten to absolute path when the bootstrap package is set up.

**Comment by a14n** [comment]
I wanted to play with the plugin system so I created a simple plugin based on the angular plugin. So I had something like:

```
my_plugin
 lib
  starter.dart
 tools
  analyzer_plugin
   bin
    plugin.dart
   pubspec.yaml
 pubspec.yaml
```

where my `my_plugin/tools/analyzer_plugin/pubspec.yaml` is:

```yaml
name: my_plugin_loader
version: 0.0.0
description: Self-loader of the plugin.
dev_dependencies:
  my_plugin:
    path: ../..
```

**Comment by bwilkerson** [comment]
And you can't reference 'my_plugin' via a package: URI because it hasn't been published yet. But you should be able to work around it for now by using an absolute path. You'll need to update it before publishing (assuming you do), and if you ever move the package on your file system, but it should otherwise be fine.

**Comment by spkersten** [comment]
We have an analyzer plugin with team-specific rules that we don't want to publish in a mono-repo with out code. Since the repo is used on many different machines, using an absolute path is inconvenient. (Now we have a bootstrap script that makes the path absolute.)

**Comment by RohitSaily** [comment]
There is a simple workaround for when the bootstrap package and the packages it depends on are in the same Git repository. It is done by specifying the dependency locations via Git using `ref: 'HEAD~0'`. This ensures that the bootstrap package always depends on the newest version of the package from the current working branch. A trade-off with this approach is that the plugin will only use the newest committed version.

This works even if the bootstrap package has a dependency which specifies its own dependencies via local relative paths.

For example, if the bootstrap package needs to depend on the "dependable" package, the "pubspec.yaml" of the bootstrap package might look like this:
```yaml
name: 'plugin'
publish_to: 'none'

environment:
      sdk: '>=3.7.0-209.1.beta<3.7.0-209.2.beta'

dev_dependencies:
      dependable:
            git:
                  url: '../../../..' #<The relative path from this file's enclosing folder to the repository root.
                  path: 'pkg/dependable' #<The path from the repository root to the "dependable" package root.
                  ref: 'HEAD~0' #<Use the newest version from the current working branch.
```

Without specifying the `ref`, the bootstrap package might not always use the most recent version. I experienced that problem even after cleaning and rebuilding ".dart_tool" folders, the "pub cache", and the "~/.dartServer" folder.
