### ISSUE TITLE
Analyzer --no-hints doesn't account for analysis_options.yaml upgrades to errors

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/sdk#35347]
## Overview of the problem
If you have upgraded a hint to an error and want it to fail analysis (in CI for instance) *and* there is a lot of other hint noise, you may want to pass the --no-hints param to quiet the noise. The analyzer appears to disables the hint checks completely and does not report the hint as an error.

## Example and how to reproduce
analysis_options.yaml
```
# analysis_options.yaml docs: https://www.dartlang.org/guides/language/analysis-options 
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: error
```
lib/file.dart
```
// TODO some comment here
... more dart code
```

Running `dartanalyzer` should report an error on the TODO
Running `dartanalyzer  --no-hints` does not report an error on the TODO

Verified to occur under Dart 2.1.0 and Dart 1.24.3 on Mac
suggested labels: analyzer-hint

## Requested changes
I would like the analyzer to include lints/hints that are upgraded to warnings or errors and not exclude them if using the --no-hints param. Alternate solutions to this issue would also be ok.
