### ISSUE TITLE
Analysis server picks up pubspec from parent directory

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#35541]
I can successfully create a new flutter app under, say ~/tmp, from the default template like this:

```console
$ cd ~/tmp
$ flutter create myapp
$ cd myapp
$ flutter analyze .
Analyzing myapp...                                              
No issues found! (ran in 0.9s)
```

Now if I try the same commands from my `flutter/website` working directory, the analyzer reports errors:

```console
$ cd ~/git/flutter/website
$ flutter create myapp
$ cd myapp
$ flutter analyze .
Analyzing myapp...                                              
  error • Target of URI doesn't exist: 'package:flutter/material.dart' • lib/main.dart:1:8 • uri_does_not_exist
  ...
  error • Undefined name 'findsOneWidget' • test/widget_test.dart:28:28 • undefined_identifier
55 issues found. (ran in 0.6s)
```

Intestingly, if I delete the `pubspec.*` files under `flutter/website` then the analyzer is happy:

```console
$ ls ../pubspec.*
../pubspec.lock ../pubspec.yaml
$ rm ../pubspec.*
$ flutter analyze .
Analyzing myapp...                                              
No issues found! (ran in 0.9s)
```

Any idea what might be going on or how I can debug this situation?

Environment:
- MacOS 10.13.6
- Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"
-  `flutter --version`
    > Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
    > Framework • revision 5391447fae (5 weeks ago) • 2018-11-29 19:41:26 -0800
    > Engine • revision 7375a0f414
    > Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

cc @DanTup @filiph @sfshaza2

**Comment by bwilkerson** [comment]
(I'm assuming that `flutter analyze` is implemented using the analysis server rather than the command-line analyzer, but I don't remember for sure whether that's true.)

> I would've expected the server to stop walking up the tree when it finds the pubspec in the newly-created Flutter app ...

As far as I know, server still looks for a `pubspec.yaml` file when deciding where to create the analysis contexts. Assuming that there are no `pubspec.yaml` files in subdirectories of 'website/ex1', then it should decide to create a single analysis context rooted in that directory. After that, it should ignore the `pubspec.yaml` files and only look for `.packages` files. (We have plans to fix the inconsistency, but haven't managed to implement those plans yet.)

One possible way to get more information is to open this directory in VSCode and then access the server's status pages. You can find a list of the analysis contexts that were created, which directories they're rooted in, and which `.packages` and `analysis_options.yaml` files it found for each such context.

> Target of URI doesn't exist: 'package:flutter/material.dart'

The error message indicates that the `.packages` file it's using doesn't have a mapping for 'flutter'. It would be interesting to know which `.packages` file it found.

**Comment by DanTup** [comment]
> I'm assuming that `flutter analyze` is implemented using the analysis server rather than the command-line analyzer

Seems so - running `flutter -v analyze` spits out the familiar JSON messages.

> One possible way to get more information is to open this directory in VSCode and then access the server's status pages. 

Good idea! @chalin, you can do this by setting the diagnostic port in your VS Code settings:

```js
"dart.analyzerDiagnosticsPort": 8123,
```

Note: Unlike the log files that overwrite, binding to a port will fail if it's already bound, so after setting this, close all VS windows then open just a single one, using the project. Then open a browser at `localhost:(port)` and click Contexts and you'll see something like this (@bwilkerson looks like someone reskinned this since I last saw it, it looks really good!):

![screenshot 2019-01-03 at 3 35 56 pm](https://user-images.githubusercontent.com/1078012/50646183-5f864e00-0f6d-11e9-8cc8-5138a61af056.png)

There's some useful info in that top half of the page, and also for me, Flutter is listed in the package map near the bottom of the page (hence no errors):

![screenshot 2019-01-03 at 3 36 35 pm](https://user-images.githubusercontent.com/1078012/50646215-72991e00-0f6d-11e9-90ae-8f3415bed7fe.png)

(Once you've done this, don't forget to remove the port in your settings to avoid the server trying to bind to the same port for VS Code window you open a Dart project in).

**Comment by chalin** [comment]
This is great, thanks for the detailed guidance. Here is what I see (this is the entire content of that page):

> <img width="756" alt="screen shot 2019-01-03 at 11 14 26" src="https://user-images.githubusercontent.com/4140793/50648335-eecd3a80-0f48-11e9-81de-44d8a1d75f63.png">

**Comment by chalin** [comment]
Note that there is no PackageMap resolver. Here are some files that @DanTup asked for:

```yaml
# step4/pubspec.yaml (the default one created by flutter create
name: step4
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

```
# step4/.packages
# Generated by pub on 2019-01-03 11:10:41.468503.
async:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/async-2.0.8/lib/
boolean_selector:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/
charcode:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.2/lib/
collection:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/
cupertino_icons:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-0.1.2/lib/
flutter:file:///Users/chalin/git/flutter/flutter/packages/flutter/lib/
flutter_test:file:///Users/chalin/git/flutter/flutter/packages/flutter_test/lib/
matcher:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.3+1/lib/
meta:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/meta-1.1.6/lib/
path:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/
quiver:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.1/lib/
sky_engine:file:///Users/chalin/git/flutter/flutter/bin/cache/pkg/sky_engine/lib/
source_span:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/source_span-1.4.1/lib/
stack_trace:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/
stream_channel:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.6.8/lib/
string_scanner:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/
term_glyph:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.0.1/lib/
test_api:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.1/lib/
typed_data:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.6/lib/
vector_math:file:///Users/chalin/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/
step4:lib/
```
