### ISSUE TITLE
The "implicit-casts: false" behaviour changed between dart 2.1 and 2.2

### ISSUE THREAD

**Issue by enyo** [dart-lang/sdk#36233]
We switched to Dart 2 as soon as it was available, and have used this `analysis_options.yaml` since then:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
```

We got a lot of warnings because of `implicit-casts: true` and fixed them by changing the offending lines to this:

```dart
// before:
final div = document.querySelector('.foo');
// after
DivElement div = document.querySelector('.foo');

callFunctionThatExpectsDivElement(div);
```

and because it was an assignment, it solved the `implicit-casts` issue.

Now suddenly with the switch to Dart 2.2, this assignment downcast is not working anymore. **There was nothing in the Changelog that explained why it isn't working anymore.**

Am I right to assume, that now, the only option I have, is to use `as` to forcefully cast in cases like this?
Is there another option, where I can have the previous behaviour, that allows me to only downcast, and warn if the types are incompatible?

**Comment by vsmenon** [comment]
fyi - @stereotype441 @leafpetersen @srawlins - was there an intended change around assignment casts?

**Comment by leafpetersen** [comment]
There was a regression in the interpretation of the implicit-casts flags in dev releases between 2.1 and 2.2 (I don't think it went out in a stable release, but could be wrong).  If you want to allow assignment/declaration casts ( as in your example code above), use the following:

```
analyzer:
  strong-mode:
    implicit-casts: false
    declaration-casts: true
    implicit-dynamic: true
```
