### ISSUE TITLE
standalone_2/io/named_pipe_script_test fails in hot reload testing mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36254]
After fixing standalone_2/io/named_pipe_script_test to pass VM options to sub-process in https://dart-review.googlesource.com/c/sdk/+/97169, the test starts failing with the following error:

```
  /====================================================================================\
  | standalone_2/io/named_pipe_script_test broke (Pass -> RuntimeError, expected Pass) |
  \====================================================================================/
  --- Command "vm" (took 04.000356s):
  DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --hot-reload-test-mode --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/named_pipe_script_test.dart
  exit code:
  255
  stdout:
  unittest-suite-wait-for-done
  stderr:
  Unhandled exception:
  Expect.fail('Unhandled exception:
  'file:///dev/fd/0': error: Unexpected tag 0 (Nothing) in ?, expected a procedure, a constructor or a function node
  #0      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
  #1      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
  ')
  #0      Expect._fail (package:expect/expect.dart:655:5)
  #1      Expect.fail (package:expect/expect.dart:272:5)
  #2      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/named_pipe_script_test.dart:42:14)
  #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
  #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
  #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
  #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
  #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
  #8      _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
  #9      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
  #10     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
  #11     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
  #12     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
  #13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
  #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
  #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
  #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
  #17     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
  #18     _StreamController._add (dart:async/stream_controller.dart:640:7)
  #19     _StreamController.add (dart:async/stream_controller.dart:586:5)
  #20     _Socket._onData (dart:io/runtime/bin/socket_patch.dart:1774:41)
  #21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
  #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
  #23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
  #24     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
  #25     _StreamController._add (dart:async/stream_controller.dart:640:7)
  #26     _StreamController.add (dart:async/stream_controller.dart:586:5)
  #27     new _RawSocket.<anonymous closure> (dart:io/runtime/bin/socket_patch.dart:1323:33)
  #28     _NativeSocket.issueReadEvent.issue (dart:io/runtime/bin/socket_patch.dart:844:14)
  #29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #31     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
  #32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
  --- Re-run this test:
  python tools/test.py -n dartk-reload-linux-debug-x64 standalone_2/io/named_pipe_script_test
```

This looks like a failure during kernel reading.
