### ISSUE TITLE
dart:html navigator.getBattery returns a Future not a Future<BatteryManager>

### ISSUE THREAD

**Issue by marcelduran** [dart-lang/sdk#36465]
When running
```dart
window.navigator.getBattery().then((battery) => print(battery.charging));
```
It returns:

```
NoSuchMethodError: method not found: 'get$charging' (battery.get$charging is not a function)
```
`battery.runtimeType` is `Interceptor`

The [`getBattery` docs](https://api.dartlang.org/stable/2.2.0/dart-html/Navigator/getBattery.html) says it returns a `Future` without referring to the actual [`BatteryManager` class](https://api.dartlang.org/stable/2.2.0/dart-html/BatteryManager-class.html) also defined on dart:html.

**Comment by kevmoo** [comment]
CC @terrylucas 

@marcelduran – what's the SDK version you're on?

**Comment by miyoyo** [comment]
This issue still exists in `Dart SDK version: 2.13.4 (stable) (Unknown timestamp) on "linux_x64"`, installed from Google's Repositories on Linux 5.4.72-microsoft-standard-WSL2.

Built with
```yaml
targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
        - web/**.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
          - -O0
          - --legacy-javascript
          - --csp
```
