### ISSUE TITLE
How to run language experiments with WebStorm? 

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#36634]
<img width="500" alt="Screen Shot 2019-04-14 at 6 42 47 PM" src="https://user-images.githubusercontent.com/1924573/56129730-43754e00-5f59-11e9-9ef1-63c89cf3bb82.png">

How do you pass in flags to enable language experiments?

**Comment by mnordine** [comment]
I see from https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md that you can enable them easily from the `analysis_options.yaml` file, but I'm not sure how to run DDC or Dart2JS with them

**Comment by sigmundch** [comment]
dart2js accepts `--enable-experiment=experiment_name` on the command-line, I believe DDC does too, but I'm not familiar with how to adjust the launch commands in webstorm to provide it.

@jwren do you have pointers to guide our users on this?

**Comment by mnordine** [comment]
I think you can set up a `build.yaml` file, and have something like:

```yaml
targets:
  $default:
    sources:
      {"exclude" : ["bin/**"]}
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        dev_options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
           # See https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
           # - --dump-info
            - --fast-startup
            - --minify
            - --no-frequency-based-minification
            - --no-source-maps
            - --show-package-warnings
            - --trust-primitives
            - --omit-implicit-checks
```

Maybe experiment flags work there for `dart2js_args`? What is the key for DDC? `ddc_args`?
