### ISSUE TITLE
Linter rules not working

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#37106]
analysis_options.yaml:

```yaml
linter:
  rules:
    - empty_statements
    - avoid_empty_else
```

example.dart:
```dart
void main(){
  if(1+2==3){}else{}
}
```

This shows no warnings or errors.

I did not test other rules but above rules are the ones that are not working.

Dart sdk: Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "linux_x64"
