### ISSUE TITLE
Migration tool should update pubspec.yaml, not analysis_options.yaml

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38347]
Currently the migration tool adds the following lines to `analysis_options.yaml`:
```yaml
analyzer:
- enable-experiment:
  - non-nullable
```
This is not what we want in the long term.  In the long term, the correct way to opt a package into NNBD will be to change its SDK constraint in `pubspec.yaml`.
