### ISSUE TITLE
Named required parameter called "required" leads to compiling error

### ISSUE THREAD

**Issue by lohanbodevan** [dart-lang/sdk#38588]
_Probably duplicated but i couldn't find any other issue related_.

If i create a class whose parameters are named-required and one of these parameters is called `required` a compile message is returned:
```
Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
```

**How to reproduce?**
Class
```dart
import 'package:meta/meta.dart';

class MyInput {
  final String label;
  final bool required;

  MyInput({@required this.label, @required this.required});
}

void main() {
  MyInput a = MyInput(label: 'hello', required: true);
  print(a.label);
}
```

pubspec.yaml
```yaml
name: required_required
description: Example of named required parameter called required
version: 0.0.1
author: John Doe <johndoe@example.com>
homepage: https://pub.dev/packages/meta

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  meta: ^1.1.7
```

But if i rename the parameter called `required` to `isRequired`, for example, then works fine.
Perhaps was thought to be like this, but i found hard and took sometime to understand what the error means.
