### ISSUE TITLE
TypeError: Cannot read property 'main' of undefined at main.dart.bootstrap.js 

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#38945]
I was using Dart 2.4.0 and my AngularDart project was working perfectly. After updating Dart to 2.5.2, the app is crashing in the browser on run webdev serve, with the following exception.

```console
TypeError: Cannot read property 'main' of undefined at main.dart.bootstrap.js 840:32                                    <fn>
```

In the production compiler (dart2js) is working normally, but in the development compiler (DDC) this exception is happening when I will run the application in the browser.

```yaml
name: siscec2browser
description: A web app that uses AngularDart Components
version: 1.0.0

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.12.0
  stream_transform: ^0.0.19
  sass_builder: ^2.1.3 
  js: ^0.6.1+1
  money: ^0.2.1
  decimal: ^0.3.4 
  c3: ^0.1.0
  dio: ^3.0.3
  essential_components: 0.1.34 

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0

```
```dart
import 'package:angular/angular.dart';
import 'package:angular_router/angular_router.dart';
import 'package:siscec2browser/app_component.template.dart' as ng;

import 'main.template.dart' as self;

@GenerateInjector(
  routerProvidersHash, // You can use routerProviders in production
)
final InjectorFactory injector = self.injector$Injector;


void main() {
  runApp(ng.AppComponentNgFactory, createInjector: injector);
}

```

.......
