### ISSUE TITLE
Recognize unused variable and import as error

### ISSUE THREAD

**Issue by shinriyo** [dart-lang/sdk#39210]
**Describe the rule you'd like to see implemented**
I want to recognize an unused variable and import as an error.

https://dart.dev/guides/language/analysis-options

**Examples**

I wrote the variable which not used.

If I just write it in `analysis_options.yaml`, but, android studio normally could be compiled.

```
analyzer:
  errors:
    unused_local_variable: error
    unused_field: error
```

And import also

for exmample,
```
import 'dart:async';
void main() {}
```

I wrote it in `analysis_options.yaml`
```
analyzer:
  errors:
    unused_import: error
```
but It can compile!
I guess it makes it can't compile
