### ISSUE TITLE
Flaky failures on co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05 on Mac

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39248]
From time to time tests from `co19_2/LibTest/io/FileSystemCreateEvent` group fail on vm-kernel-mac-product-x64 bot:

```
/=========================================================================================================\
 | co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05 broke (Pass -> RuntimeError, expected Pass) |
 \=========================================================================================================/
 --- Command "vm" (took 825ms):
 DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart
 exit code:
 255
 stdout:
 unittest-suite-wait-for-done
 stderr:
 Unhandled exception:
 Expect.isFalse(true) fails.
 #0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
 #1      Expect.isFalse (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:48:5)
 #2      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart:33:16)
 #3      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:53:7)
 #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
 #5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
 #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
 #7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
 #8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
 #9      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:776:16)
 #10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
 #11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
 #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
 #13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
 #14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
 #15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
 #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
 #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
 #18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
 #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
 --- Re-run this test:
 python tools/test.py -n dartk-mac-product-x64 co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05
```

[log1](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8897602881212935136/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0), [log2](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8898044571808941680/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0), [log3](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8898183719485764112/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0).

This failure is easy to reproduce on Mac (failure rate > 50%).
Could be related to https://github.com/dart-lang/sdk/issues/37342.

/cc @ZichangG
