### ISSUE TITLE
Is it a good practice to use third party package in path form and out of git control?

### ISSUE THREAD

**Issue by kangwang1988** [dart-lang/sdk#40656]
This is an issue related to CFE and kernel.
Recently, I found my test case for aspectd(https://github.com/alibaba-flutter/aspectd) is broken.
```shell
kylewong@KyleWongs-MacBook-Pro aspectd % pub get
Resolving dependencies... (2.8s)
Error on line 14, column 11: Invalid description in the "front_end" pubspec on the "package_config_v2" dependency: "../../third_party/pkg/package_config_v2/" is a relative path, but this isn't a local pubspec.
   ╷
14 │     path: ../../third_party/pkg/package_config_v2/
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

In short, this error is resulted from pubspec.yaml below:
```yaml
name: aspectd
description: AOP for Flutter. AspectD is an AOP(aspect oriented programming) framework for dart. It provides call&execute&inject grammar.
version: 0.9.8
homepage: https://github.com/alibaba-flutter/aspectd

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  kernel: any
  front_end: any
  args: any
  path: any
  yaml: any
  _fe_analyzer_shared: any
  analyzer: any
  mockito: 4.1.1
  test: 1.9.4

dependency_overrides:
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: edd64e6d5c7924a5fb1ef80c5226d24006e7977b
      path: pkg/kernel
  front_end:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: edd64e6d5c7924a5fb1ef80c5226d24006e7977b
      path: pkg/front_end
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: edd64e6d5c7924a5fb1ef80c5226d24006e7977b
      path: pkg/_fe_analyzer_shared
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: edd64e6d5c7924a5fb1ef80c5226d24006e7977b
      path: pkg/analyzer
```
And this commit where package_config_v2 dependency is imported for front_end:
https://github.com/dart-lang/sdk/commit/81d4ac07d488fb48383586b29f6503b674a8b917#diff-d3f8f5e7a71f390009e681bbfcc1af94

I noticed that now  front_end is depending on package_config_v2 which is out of git control. Instead, package_config_v2 is fetched by DEPS mechanism.

As the flutter is evolving in the master branch, I have to keep up with it and resolve the issue when the test is broken. However, if you depend on front_end, I have to depend on dart sdk in git form. 
It works fine before, but this time, if a third party package is imported, the test case would broken and the pub get would fail. 

For a package provided by dart-sdk, is it a good practice to use use third party package in path form and out of git control？

@jensjoha 
CC @mraleph
