### ISSUE TITLE
catch doesn't work nicely with null-safey and implicit-casts: false

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#41074]
We can't type annotate the error in a `catch` statement, so we have to manually case to `Object`, or allow implicit casts to go from `dynamic` to `Object`.

What is the expected way to write this?

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
  enable-experiment:
    - non-nullable
```

```dart
void doStuff(void Function() f) {
  try {
    f();
  } catch (o) {
    _takeObject(o); // Error: The argument type 'dynamic' can't be assigned to the parameter type 'Object'.
  }
}

void _takeObject(Object o) {}
```

```dart
void doStuff(void Function() f) {
  try {
    f();
  } on Object catch (o) { // OK statically, looks weird. Will this work the same?
    _takeObject(o);
  }
}

void _takeObject(Object o) {}
```
