### ISSUE TITLE
can't run dart bin/client.dart 

### ISSUE THREAD

**Issue by ibantoo** [dart-lang/sdk#41463]
<can't running dart client thought I don't use vscode>

<grpc 2.1.3>

## Repro steps

this is my `pubspec.yaml`:
```
name: rpc
description: Dart gRPC sample client

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc:
  protobuf: ^1.0.1
```
i have 3 directories: 
1. `bin` has a file client.dart 
2. `lib` has directory `src/generated/*.dart`
3. `blogpb`  my blog.proto here

Expected result: <i wan to test my client.dart>

Actual result: <Error: Error when reading 'bin/main.dart': No such file or directory>

Does anyone have the same issues? I tried to look up on Stackoverflow that mostly issues because of `.vscode` directory, but I don't use vscode, I use Atom

the files in my main directory have another file 
`pubspec.lock` , `.packages`,  `.dart-tool/package_config.json`;
