### ISSUE TITLE
Erroneous error about language version overrides in parts

### ISSUE THREAD

**Issue by Klikini** [dart-lang/sdk#42661]
When compiling a web application, I get the following output (repeated for every `part` statement)

```
web/main.dart:93:6:
Error: The language version override has to be the same in the library and its part(s).
part 'package:couclient/src/display/windows/go_window.dart';
     ^
```

By Googling that error, I found out that it happens when a file contains `// @dart <version>`. My project does not contain any version overrides, and the only build override in the dependencies is in `bazel_worker` at the top of `lib/src/worker_protocol.pb.dart`:

```
///
//  Generated code. Do not modify.
//  source: worker_protocol.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type
// ignore_for_file: annotate_overrides
```

I installed version 2.3 of the SDK, but webdev does not build under that version, so I had to upgrade back to the latest version.

Is there reason for this version override? Is it possible to remove it or avoid it? I'm not sure how anyone is supposed to build a project using webdev with this issue, unless I'm missing something. Any assistance is appreciated, and I'm happy to provide any more information or debugging if someone can point me in the right direction :)

# Version information

```
$ dart --version
Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "windows_x64"
```

```
$ webdev --version
2.5.9
```

## Relevant `pubspec.yaml`

```yaml
dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  json_serializable: ^3.0.0
```

## Relevant `pubspec.lock`

```yaml
packages:
  bazel_worker:
    dependency: transitive
    description:
      name: bazel_worker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.25"
```

The full source of this project is available at https://gitlab.com/ChildrenOfUr/coUclient/-/tree/dev
