### ISSUE TITLE
dart2js stack traces are wrong

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#42815]
Latest stable sdk, 2.8.4

Not sure if this is related to https://github.com/dart-lang/sdk/issues/42811

After compiling with `dart2js`, converting a javascript stack trace to a dart one results in an incorrect stack trace. For example, I'm seeing:

Dart stack trace:

```
NullError: method not found: 'sC' on null
packages/my_package/src/my/file.dart 131:5                           MyClass._myFunction
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19  _wrapJsFunctionForAsync
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5   _wrapJsFunctionForAsync.
packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19  _awaitOnObject.
packages/$sdk/lib/async/zone.dart 1128:37                           _rootRunUnary
packages/$sdk/lib/async/zone.dart 1012:12                           _CustomZone.runUnary
packages/$sdk/lib/async/future_impl.dart 129:12                     _FutureListener.handleValue
packages/$sdk/lib/async/future_impl.dart 665:13                     _Future._propagateToListeners
packages/$sdk/lib/async/future_impl.dart 468:7                      _Future._complete
```
    
JS stack trace:

```
NullError: method not found: 'sC' on null
main.dart.js 53666:3  Rt.Iw
main.dart.js 53579:3  
main.dart.js 3149:71  akC.a
main.dart.js 3424:24  akC.dart.akC.$2
main.dart.js 3420:31  ajI.dart.ajI.$1
main.dart.js 3324:35  a9_.dart.y4
main.dart.js 4668:12  ah3.nk
main.dart.js 3898:16  ahy.$0
main.dart.js 3835:42  Object.i8
main.dart.js 3758:3   B.es
```

`packages/my_package/src/my/file.dart 131:5` is actually an empty line in my source file. And I don't see any lines near it where a variable could be `null`.

**Comment by vsmenon** [comment]
fyi @sigmundch 

@mnordine - how are you running code?  E.g., `webdev`?  Calling `dart2js` by hand?

**Comment by mnordine** [comment]
`webdev`, here's my `build.yaml`:

```yaml
targets:

  $default:
    sources:
      {"exclude" : ["bin/**"]}
    builders:
      build_web_compilers|dart_source_cleanup:
        release_options:
          enabled: false
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: true
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        dev_options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
           # See https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
            - --minify
            - --show-package-warnings
            - -O2

builders:
  yaml2JsonBuilder:
    import: "package:main/builder.dart"
    builder_factories: ["yaml2JsonBuilder"]
    build_extensions: {".yaml": [".json"]}
    auto_apply: root_package
    defaults:
      generate_for:
        include:
          - web/assets/**.yaml
```
