### ISSUE TITLE
No published analyzer available for language version 2.10.0

### ISSUE THREAD

**Issue by OrlandoEduardo101** [dart-lang/sdk#42887]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer
* Common Front End (CFE) and kernel
* Dart core libraries ("dart:async", "dart:io", etc.)
* Dart VM
* dart2js
* dartfix
* dev_compiler

Some other pieces of the Dart ecosystem are maintained elsewhere. Please
file issues in their repository:

* Dart language: https://github.com/dart-lang/language
* Dart website: https://github.com/dart-lang/site-www
* Flutter: https://github.com/flutter/flutter
* Linter: https://github.com/dart-lang/linter
* dartfmt: https://github.com/dart-lang/dart_style

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

If you simply have a question, consider starting with Stack Overflow:

https://stackoverflow.com/questions/tagged/dart

For a real-time response, consider our Gitter channel:

https://gitter.im/dart-lang/sdk

**Comment by vegidio** [comment]
I'm having the same problem. I was following the problem reported in this issue: https://github.com/flutter/flutter/issues/56779#issuecomment-666540672 but that was closed without my case in specific being solved, so I think I must continue here.

More information can be found in the original issue that I linked, but to summarize, I'm trying to run `flutter pub run build_runner build` in my Flutter project, but that is failing with a message asking to file an issue here.

Here is my setup:

<details>
<summary>flutter doctor</summary>
  
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.120, on Mac OS X 10.15.6 19G73, locale en-SE)
    • Flutter version 1.21.0-6.0.pre.120 at /Users/vegidio/Development/Flutter
    • Framework revision aa1acd8e54 (51 minutes ago), 2020-07-31 01:07:18 +0800
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[!] VS Code (version 1.47.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! Error: vinicius-iphonexs is busy: Waiting for Device. Xcode will continue when vinicius-iphonexs is finished. (code -10)
```
</details>

<details>
<summary>pubspec.yaml</summary>
  
```yml
name: myapp
description: myapp

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^0.3.4
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  dio_http_cache: ^0.2.8
  firebase_analytics: ^5.0.16
  firebase_core: ^0.4.5
  flutter_mobx: ^1.1.0
  flutter_rating_bar: ^3.0.1+1
  hidden_drawer_menu: ^1.1.4
  intl: ^0.16.1
  mobx: ^1.2.1
  package_info: ^0.4.1
  provider: ^4.1.3
  retrofit: ^1.3.4
  shared_preferences: ^0.5.8
  store_redirect: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.3.0
  mobx_codegen: ^1.1.0+1
  retrofit_generator: ^1.3.7+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
        - asset: assets/fonts/CircularStd-Book.ttf
        - asset: assets/fonts/CircularStd-Medium.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
```
</details>

<details>
<summary>pubspec.lock</summary>
  
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.0"
  admob_flutter:
    dependency: "direct main"
    description:
      name: admob_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.39.14"
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.13"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.2"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.4"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.10"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.1"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.0"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.2"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.1.0"
  cached_network_image:
    dependency: "direct main"
    description:
      name: cached_network_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0+1"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0-nullsafety.2"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  chewie:
    dependency: "direct main"
    description:
      name: chewie
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.10"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0-nullsafety.2"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.2"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.6"
  dio:
    dependency: "direct main"
    description:
      name: dio
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.9"
  dio_http_cache:
    dependency: "direct main"
    description:
      name: dio_http_cache
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.8"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.2.1"
  firebase:
    dependency: transitive
    description:
      name: firebase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.3.0"
  firebase_analytics:
    dependency: "direct main"
    description:
      name: firebase_analytics
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.16"
  firebase_analytics_platform_interface:
    dependency: transitive
    description:
      name: firebase_analytics_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  firebase_analytics_web:
    dependency: transitive
    description:
      name: firebase_analytics_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.5"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+2"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.11"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.1"
  flutter_launcher_icons:
    dependency: "direct dev"
    description:
      name: flutter_launcher_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.5"
  flutter_mobx:
    dependency: "direct main"
    description:
      name: flutter_mobx
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0+1"
  flutter_rating_bar:
    dependency: "direct main"
    description:
      name: flutter_rating_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1+1"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  hidden_drawer_menu:
    dependency: "direct main"
    description:
      name: hidden_drawer_menu
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0+3"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.4"
  image:
    dependency: transitive
    description:
      name: image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.14"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.2"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  json_serializable:
    dependency: "direct dev"
    description:
      name: json_serializable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.3.0"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.4"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.9"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0-nullsafety.2"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6+3"
  mobx:
    dependency: "direct main"
    description:
      name: mobx
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1+1"
  mobx_codegen:
    dependency: "direct dev"
    description:
      name: mobx_codegen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0+1"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  node_interop:
    dependency: transitive
    description:
      name: node_interop
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  node_io:
    dependency: transitive
    description:
      name: node_io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  open_iconic_flutter:
    dependency: transitive
    description:
      name: open_iconic_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  package_info:
    dependency: "direct main"
    description:
      name: package_info
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.11"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4+3"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.2"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.13"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.1"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.4"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  retrofit:
    dependency: "direct main"
    description:
      name: retrofit
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.4"
  retrofit_generator:
    dependency: "direct dev"
    description:
      name: retrofit_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.7+5"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.24.1"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.8"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.2+1"
  shared_preferences_macos:
    dependency: transitive
    description:
      name: shared_preferences_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+10"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2+7"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.7"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2+1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.5"
  store_redirect:
    dependency: "direct main"
    description:
      name: store_redirect
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0+2"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.18"
  timing:
    dependency: transitive
    description:
      name: timing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+2"
  tuple:
    dependency: transitive
    description:
      name: tuple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0-nullsafety.2"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0-nullsafety.2"
  video_player:
    dependency: transitive
    description:
      name: video_player
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.11+2"
  video_player_platform_interface:
    dependency: transitive
    description:
      name: video_player_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  video_player_web:
    dependency: transitive
    description:
      name: video_player_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3+2"
  wakelock:
    dependency: transitive
    description:
      name: wakelock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4+2"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+15"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
sdks:
  dart: ">=2.10.0-0.0.dev <2.10.0"
  flutter: ">=1.16.0 <2.0.0"
```
</details>

**Comment by joaoalvaro** [comment]
I solved it by switching the channel to Dev.

**Comment by srawlins** [comment]
Thanks for filing an issue. Analyzer 0.39.15 is available for language version 2.10.0. https://pub.dev/packages/analyzer/changelog

**Comment by OrlandoEduardo101** [comment]
> Obrigado por registrar um problema. O analisador 0.39.15 está disponível para a versão 2.10.0 do idioma. https://pub.dev/packages/analyzer/changelog

Because build_runner 1.10.1 depends on analyzer 0.39.14 and no versions of build_runner match >1.10.1 <2.0.0, build_runner ^1.10.1 requires analyzer 0.39.14.

the build runner is't compatible with analyzer 0.39.15

**Comment by jakemac53** [comment]
You now need the latest analyzer 0.39.15 to get the latest analyzer 😢 , so the fix for flutter stable breaks the latest flutter by not allowing the latest analyzer.

This situation is really unfortunate in general... we can release a new version of build_runner which removes the pinning and sets a min sdk constraint of 2.10 to solve the problem I think.

cc @leafpetersen @scheglov @natebosch @stereotype441

**Comment by jakemac53** [comment]
Note that in the meantime the fix is to pin either analyzer to 0.39.15 or build_runner to 1.10.1

**Comment by jakemac53** [comment]
This issue cannot be resolved in the way I suggested due to https://github.com/dart-lang/pub/issues/2557, I would not be able to publish the package

**Comment by OrlandoEduardo101** [comment]
I switch dart to dev channel, conforme the friend said above, its working.

**Comment by leafpetersen** [comment]
I believe that we have unblocked the fix for this from landing, and @natebosch has landed the fix from @jakemac53 .

**Comment by larssn** [comment]
How do we get this to work with Flutter?

If I require the SDK version 2.10.0 (which is the dev channel of dart!!), I get the error:
```
Running "flutter pub get" in my_app...                  
The current Dart SDK version is 2.9.0-21.0.dev.flutter-20bf2fcf56.

Because the app depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.
pub get failed (1; Because the app depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.)
```

This is on the dev branch of Flutter.

The workaround seems to be switching to the flutter master branch: `flutter channel master`, but I'd prefer not to be there.

Any help?

**Comment by vaibhav135** [comment]
hii I am having the exact same problem   

> How do we get this to work with Flutter?
> 
> If I require the SDK version 2.10.0 (which is the dev channel of dart!!), I get the error:
> 
> ```
> Running "flutter pub get" in my_app...                  
> The current Dart SDK version is 2.9.0-21.0.dev.flutter-20bf2fcf56.
> 
> Because the app depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.
> pub get failed (1; Because the app depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.)
> ```
> 
> This is on the dev branch of Flutter.
> 
> The workaround seems to be switching to the flutter master branch: `flutter channel master`, but I'd prefer not to be there.
> 
> Any help?

**Comment by larssn** [comment]
@vaibhav135 This was the solution for us:

```
dev_dependencies:
  build_runner: 1.10.1

dependency_overrides:
  analyzer: 0.39.14
```

Allows us to run the unstable versions of flutter, but the stable version of dart.
