### ISSUE TITLE
Command-line call to dartanalyzer ignores --options related to experiment non-nullable.  

### ISSUE THREAD

**Issue by simphotonics** [dart-lang/sdk#42971]
### SDK version 2.9.0 
```Console
# dart --version
Dart VM version: 2.9.0-14.1.beta (beta) (Tue Jun 9 10:52:57 2020 +0200) on "linux_x64"

# dartanalyzer --version
dartanalyzer version 2.9.0
```
### Error Description
When calling `dartanalyzer` from the command-line, options defined in analysis_options.yaml related to experiment **non-nullable** are ignored, even though the file is being read. Similar to issue [33753](https://github.com/dart-lang/sdk/issues/33753).

```Console
# dartanalyzer -v --options=analysis_options.yaml lib/*
Analyzing lib/analyzer_test.dart...
Loaded analysis options from analysis_options.yaml
  error • This requires the 'non-nullable' language feature to be enabled. • lib/analyzer_test.dart:1:4 • experiment_not_enabled
       Try updating your pubspec.yaml to set the minimum SDK constraint to 2.9.0 or higher, and running 'pub get'.
1 error found.
```
When adding the option `--enable-experiment=non-nullable`, `dartanalyzer` reports no issues:
```Console 
dartanalyzer -v --enable-experiment=non-nullable lib/*
Analyzing lib/analyzer_test.dart...
Loaded analysis options from /home/dan/analyzer_test/analysis_options.yaml
No issues found!
```
### Reproducing The Error
To reproduce the error, one may clone the package: [analyzer_test](https://github.com/simphotonics/analyzer_test) (a console application created by `stagehand` with non-null experiment enabled) and run the command:
```Console
# dartanalyzer -v --options=analysis_options.yaml lib/*
```
 from the package root directory.

For reference the content of `analysis_options.yaml`:
```Yaml
# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
#   exclude:
#     - path/to/excluded/files/**
```
