### ISSUE TITLE
pub activate preforming duplicated precompiles.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#42974]
I've just upgraded to 2.9 however I believe this issue was also happening under 2.8.
(I had been investigating excessive memory usage under 2.8 during compilation and had noticed duplicated processes but had not seen the cli output as the process I was running was outputing to /dev/null).

At first I thought it might be a corrupted .pub-cache so I started by deleting .pub-cache.

The project I'm testing with is https://pub.dev/packages/dshell

So when I run :
```
rm -rf ~/.pub-cache/
pub global activate dshell --source=path
```

Which outputs:
```
ownloading node_interop 1.1.1...
Downloading csslib 0.16.2...
Downloading asn1lib 0.6.5...
Downloading pointycastle 1.0.2...
Got dependencies!
Precompiling executables... (1.2s)
Precompiled system_info:system_info.
Precompiled system_info:system_info.
Precompiled system_info:system_info.
Precompiled system_info:system_info.
Precompiled archive:tar.
Precompiled archive:tar.
Precompiled archive:tar.
Precompiled archive:tar.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
Precompiled test:test.
Precompiled test:test.
Precompiled test:test.
Precompiled test:test.
Installed executables dshell, dshell_complete and dshell_install.
Activated dshell 1.10.14 at path "/home/bsutton/git/dshell".
```

The pubspec.yaml is:

```
name: dshell
version: 1.10.14
homepage: https://github.com/bsutton/dshell
description: An API and dev environment for writing console apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  archive: ^2.0.13
  args: ^1.5.2
  collection: ^1.14.12
  csv: ^4.0.3
  equatable: ^1.0.1
  file: ^5.1.0
  file_utils: ^0.1.3
  glob: ^1.2.0
  ini: ^2.0.1
  intl: ^0.16.0
  logger: ^0.9.1
  meta: ^1.1.8
  money2: ^1.4.0
  path: ^1.7.0
  pedantic: ^1.6.0
  pubspec: ^0.1.3
  pub_semver: ^1.4.2
  system_info: ^0.1.3
  uuid: ^2.0.4
  validators: ^2.0.0+1
  yaml: ^2.2.0
dev_dependencies:
  test: ^1.6.0
  effective_dart: ^1.0.0
  mockito: ^4.0.0
  test_coverage: ^0.4.2
executables:
  dshell: dshell
  dshell_complete: dshell_complete
  dshell_install: dshell_install
                               
```

My system config is:
```
dshell doctor
Dshell version    1.10.14                                                

OS                linux                                                  
OS Version        Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Path separator    /                                                      

dart version      Dart SDK version: 2.9.0 (stable) (Unknown timestamp) on "linux_x64"                                      

dshell path       /<HOME>/.pub-cache/bin/dshell                          
dart exe path     /usr/bin/dart                                          
dart path         /usr/bin/dart                                           which: /usr/bin/dart                                   
dart2Native path  /usr/lib/dart/bin/dart2native               which: /usr/lib/dart/bin/dart2native                   

pub path          /usr/lib/dart/bin/pub                                   which: /usr/lib/dart/bin/pub                           
Pub cache         /<HOME>/.pub-cache                                     

Package Config    /<HOME>/git/dshell/file:/<HOME>/git/dshell/.packages   

PATH
                  /usr/local/sbin                                        
                  /usr/local/bin                                         
                  /usr/sbin                                              
                  /usr/bin                                               
                  /sbin                                                  
                  /bin                                                   
                  /usr/games                                             
                  /usr/local/games                                       
                  /snap/bin                                              
                  /usr/lib/dart/bin                                      
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/apps/flutter/bin                               
                  /<HOME>/.dshell/bin                                    
                  /usr/lib/dart/bin                                      
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/.dshell/bin                                    
                  /usr/lib/dart/bin                                      
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/.dshell/bin                                    
                  /usr/lib/dart/bin                                      
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/apps/flutter/bin                               
                  /<HOME>/.dshell/bin                                    
                  /usr/lib/dart/bin                                      
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/.dshell/bin                                    
                  /usr/lib/dart/bin                                      
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/.dshell/bin                                    

$SHELL            /bin/bash                                              
Detected SHELL    bash                                                   
                                          

Dart location(s)
                  /usr/bin/dart                                          

Permissions
HOME              rwxr-xr-x <user>:<user> /<HOME> 
.dshell           rwxrwxr-x <user>:<user> /<HOME>/.dshell 
cache             rwxrwxr-x <user>:<user> /<HOME>/.dshell/cache 
dependencies.yaml rw-rw-r-- <user>:<user> /<HOME>/.dshell/dependencies.yaml 
templates         rwxrwxr-x <user>:<user> /<HOME>/.dshell/templates 
               
```

![image](https://user-images.githubusercontent.com/900408/89590625-af38a400-d88b-11ea-93ee-7cf80349da2c.png)
