### ISSUE TITLE
Analyzer reports errors calling functions with "required" keyword in packages fetched after context was created

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#43532]
Moving from https://github.com/Dart-Code/Dart-Code/issues/2793#issuecomment-696668218. If you open a Flutter project that you haven't fetched packages for (eg. a fresh clone of a project, or deleting `.packages`/`.dart_tool`/`.pubspec.lock`) and then run `pub get` while the analyzer is open, it will not handle the `required` keyword correctly inside the Flutter packages and report spurious errors like "The named parameter 'vsync' is not defined".

To repro, create a simple Flutter "project" that creates an `AnimationController` (but don't run `pub get`):

### pubspec.yaml
```yaml
name: langtest
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
```

### lib/main.dart
```dart
import 'package:flutter/material.dart';

final a = AnimationController(vsync: null);
```

Open the project in an IDE so it's analyzed (using the SDK from Flutter - I'm using 1.22.0-12.0.pre). You'll see (expected) errors on the `package:flutter` import and `AnimationController`.

Now run `pub get`. The original errors will disappear, but the `vsync` error will appear even though the code is correct. Reloading the IDE will cause that to go away.
