### ISSUE TITLE
Import auto-complete should not suggest non-dependencies

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43678]
![image](https://user-images.githubusercontent.com/168174/95123352-abe45c00-0706-11eb-9b8f-cb13695c57ee.png)

In this particular case I _only_ depend on `package:test`, which in turn I guess transitively depends on these? 

```yaml
name: example
version: 0.0.0
environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  test: ^1.15.0
```

It seems wrong to suggest them at all.

If it would be too breaking to change this behavior might I suggest something in `analysis_options.yaml`?:

```yaml
analyzer:
  ide:
    strict-import-completion: true
```

**Comment by matanlurey** [comment]
(An _added_ 👍 if this feature hinted if packages were imported that were not dependencies)

**Comment by bwilkerson** [comment]
That sounds reasonable to me. At the very least completion ought to be ranking suggestions for direct dependencies higher than suggestions for implicit dependencies. But I definitely agree that we don't want to encourage the practice of importing from packages that are only implicitly depended on.

**Comment by modulovalue** [comment]
It would be much more pragmatic to have dependencies themselves tell the analyzer which dependencies they want to expose with for example a transitive entry in their pubspec:

```yaml
name: package_a

# private_dependency is excluded from search results by default in all packages that depend on package_a
private_dependency: some_version
# public_dependency is included in search results in packages that depend on package_a
public_dependency: some_version
  transitive: true  
```

It is difficult to track down which dependencies must be explicitly depended on if a user wants to be able to use any given package without having to unnecessarily make transitive dependencies explicit. The deeper the deepest path in the package dependency graph, the worse this issue becomes.

## Example:
Think of the following package dependency graph

(A > B means package B depends on package A)

vector_math > geometry > business_logic > ui_base > macos_application

1. A user writes tests in macos_application and needs to create an instance of a type X.
2. User has to track down where type X was declared.
3. If X is an interface he needs to look for implementations of X (e.g. XImpl)
4. Once he has found XImpl he needs to add the package where XImpl was declared to the pubspec.

instead, if all packages that the user might need would be marked as transitive and therefore included in autocompletion search results (directives as well as type autocompletion), he'd only need to type XIm... and press enter to get what he needs.

TLDR: Excluding transitive dependencies from search results without the ability to opt-out/in per package is the wrong approach.
