### ISSUE TITLE
[vm/mac] Error is wrong type: OS Error: Connection reset by peer, errno = 54

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43690]
There are new test failures on [[pkg:vm_service] ignore four deprecated member references...[CFE] Remove unreachable/unused code in constant evaluator](https://github.com/dart-lang/sdk/compare/61e97d010c98c27926b1a9d4f3d24c376adb91f5~...4db0411cbd98c21666aa288eb14bcd9b440cc44c).

The tests
```
standalone/io/https_unauthorized_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-weak-asserts-mac-debug-x64
```

Failure: `Error is wrong type: OS Error: Connection reset by peer, errno = 54` - might be an infrastructure flake.

**Comment by alexmarkov** [comment]
Failed once again:

```
/==============================================================================================================\
| dartk-strong-mac-debug-x64:standalone/io/https_unauthorized_test broke (Pass -> RuntimeError, expected Pass) |
\==============================================================================================================/

--- Command "vm" (took 11.000594s):
DART_CONFIGURATION=DebugX64 xcodebuild/DebugX64/dart --sound-null-safety --ignore-unrecognized-flags --packages=/opt/s/w/ir/.packages /opt/s/w/ir/tests/standalone/io/https_unauthorized_test.dart

exit code:
255

stdout:
Client failed
  stdout:

  stderr:
Unhandled exception:
ExpectException: Error is wrong type: OS Error: Connection reset by peer, errno = 54
#0      expect (file:///opt/s/w/ir/tests/standalone/io/https_unauthorized_client.dart:20:5)
#1      runClients.<anonymous closure> (file:///opt/s/w/ir/tests/standalone/io/https_unauthorized_client.dart:36:7)
#2      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#3      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#6      Future._completeError (dart:async/future_impl.dart:537:5)
#7      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

stderr:
Unhandled exception:
Expect.fail('Client subprocess exit code: 255')
#0      Expect._fail (package:expect/expect.dart:704:5)
#1      Expect.fail (package:expect/expect.dart:282:5)
#2      main.clientProcess.<anonymous closure> (file:///opt/s/w/ir/tests/standalone/io/https_unauthorized_test.dart:62:16)
#3      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#9      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

--- Re-run this test:
python tools/test.py -n dartk-strong-mac-debug-x64 standalone/io/https_unauthorized_test
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864045545036903984/+/steps/test_results/0/logs/new_test_failures__logs_/0
