### ISSUE TITLE
Add support for ignoring diagnostics in pubspec files

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#43740]
As pubspec analysis goes live (#43529) and we add more analyses (https://github.com/dart-lang/linter/labels/pub), we should consider support for ignoring diagnostics in pubspecs.  A natural syntax might use `#` like:

```yaml

# ignore: pub_package_names
name: _foo
version: 1.1.1
...
```
