### ISSUE TITLE
[vm/ffi] Migration to external fields for structs communication

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44024]
For the NNBD stable release we should have the error messages guide users to the migration path.

We could make the error message in field initialization say that users should use external in NNBD.

Relevant error message CFE:

```yaml
FfiFieldInitializer:
  # Used by dart:ffi
  template: "Field '#name' is a dart:ffi Pointer to a struct field and therefore cannot be initialized before constructor execution."
  external: test/ffi_test.dart
```

Relevant error message analyzer:

```dart
  static const FfiCode FIELD_IN_STRUCT_WITH_INITIALIZER = FfiCode(
      name: 'FIELD_IN_STRUCT_WITH_INITIALIZER',
      message: "Fields in subclasses of 'Struct' can't have initializers.",
      correction: "Try removing the initializer.");
```

cc @mit-mit @mkustermann @mraleph
