### ISSUE TITLE
[NNBD] Type inference regression #2

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#44297]
```dart
class Foo<Z> {
  final int Function(Bar<Z>) fn;

  const Foo(this.fn);
}

class Bar<Z> {
  final int a;
  final Z b;

  const Bar(this.a, this.b);
}

void main() {
  final value = Foo((a) => a.a); // Inferred to Foo<Object?> (via 'add type annotation'), and no analyzer error.
  final Foo<Object?> value2 = Foo((a) => a.a);
}
```

I expected the type to be inferred to `Foo<dynamic>`, which would force me to specify a type or to be explicit about the dynamic type.

**I hope this is a bug and not some new expected behavior?**

analyzer settings:
```yaml
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
    strict-raw-types: true
```

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.296, on Mac OS X 10.15.7 19H15 darwin-x64, locale de-DE)
    • Flutter version 1.24.0-8.0.pre.296 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision 6fd13e6ef1 (5 days ago), 2020-11-19 00:29:28 +0100
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)
```
