### ISSUE TITLE
JSON and serialization and sound null safety

### ISSUE THREAD

**Issue by danvallejo** [dart-lang/sdk#44360]
Following steps : https://flutter.dev/docs/development/data-and-backend/json#one-time-code-generation

I also tried the steps at unsound-null-safety.

Here's my pubspec.yaml:

```
name: test
description: Test application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^1.0.14
  shared_preferences: ^0.5.12
  http: ^0.12.2
  flutter_guid: ^0.1.0
  json_annotation: ^3.1.1

  cupertino_icons: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.6
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```

>flutter pub run build_runner build
Failed to precompile build_runner:build_runner:
/d:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.6/bin/build_runner.dart:89:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dyn
amic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:args
 - package:build_runner_core
 - package:io
 - package:logging
 - package:build_runner
 - package:build
 - package:glob
 - package:pool
 - package:crypto
 - package:watcher
 - package:build_config
 - package:build_resolvers
 - package:json_annotation
 - package:timing
 - package:graphs
 - package:package_config
 - package:yaml
 - package:code_builder
 - package:dart_style
 - package:build_daemon
 - package:pedantic
 - package:http_multi_server
 - package:shelf
 - package:pub_semver
 - package:pubspec_parse
 - package:analyzer
 - package:convert
 - package:built_value
 - package:built_collection
 - package:stream_transform
 - package:http_parser
 - package:mime
 - package:shelf_web_socket
 - package:web_socket_channel
 - package:_fe_analyzer_shared
 - package:checked_yaml
 - package:quiver
 - package:fixnum
 - package:cli_util

For solutions, see https://dart.dev/go/unsound-null-safety
pub finished with exit code 1

> dart --version
Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "windows_x64"

**Comment by mit-mit** [comment]
cc @jakemac53 @natebosch

**Comment by jakemac53** [comment]
For some reason `flutter pub run build_runner build` is running with null safety enabled when it shouldn't - I am not sure what is causing this in this particular situation?

**Comment by jakemac53** [comment]
@danvallejo what is the output of `flutter --version` for you?

**Comment by danvallejo** [comment]
D:\flutter>flutter --version
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (7 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by jakemac53** [comment]
@danvallejo are you still experiencing this issue? I am still not sure what could be causing it.... although i do wonder if somehow this line in the pubspec is causing issues `https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html`. That seems like possibly some copy/paste error.

Does `flutter pub get` succeed for you?

**Comment by sh-erfan** [comment]
For me, a clean solved the problem:
`flutter clean`
`flutter pub get`
`flutter pub run build_runner build`

**Comment by aminalaee** [comment]
I'm using openapi-generator docker image and I get the same error and here's my environment:
```
Flutter 1.24.0-10.2.pre • channel beta •
https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (3 months ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)
```

pubsec.yaml
```
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations: ^1.1.2
  cupertino_icons: ^1.0.1
  dio: ^3.0.10
  dio_http2_adapter: ^1.0.1
  provider: ^4.0.0
  contracts:
    path: lib/openapi/v1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
  build_runner: ^1.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/
```

output:
```Failed to precompile build_runner:build_runner:
../../../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.2/bin/build_runner.dart:89:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:args
 - package:build_runner_core
 - package:io
 - package:logging
 - package:build_runner
 - package:build
 - package:path
 - package:stack_trace
 - package:glob
 - package:pool
 - package:crypto
 - package:async
 - package:meta
 - package:watcher
 - package:build_config
 - package:build_resolvers
 - package:json_annotation
 - package:timing
 - package:graphs
 - package:package_config
 - package:yaml
 - package:charcode
 - package:string_scanner
 - package:code_builder
 - package:dart_style
 - package:build_daemon
 - package:pedantic
 - package:http_multi_server
 - package:shelf
 - package:pub_semver
 - package:pubspec_parse
 - package:analyzer
 - package:convert
 - package:collection
 - package:built_value
 - package:built_collection
 - package:stream_transform
 - package:http_parser
 - package:stream_channel
 - package:mime
 - package:shelf_web_socket
 - package:web_socket_channel
 - package:checked_yaml
 - package:source_span
 - package:matcher
 - package:quiver
 - package:_fe_analyzer_shared
 - package:typed_data
 - package:fixnum
 - package:term_glyph
 - package:cli_util

For solutions, see https://dart.dev/go/unsound-null-safety
```
