### ISSUE TITLE
dependency_overrides is ignored

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#44564]
While trying to overide some dependecies that where used by packages that I used I got this Warnings:

```
Warning: You are using these overridden dependencies:
! cached_network_image 2.5.0
! flutter_cache_manager 2.1.0
```

and this versions ended up in my pubspec.lock despite this entry in my paubspec.yaml

```yaml
dependency_overrides:
  cached_network_image: ^2.3.3
  flutter_cache_manager: ^2.0.0
```

you can try it on https://github.com/escamoteur/pubspec_test

currently I'm using:

```
[√] Flutter (Channel master, 1.26.0-2.0.pre.137, on Microsoft Windows [Version 10.0.18363.1256], locale de-DE)
    • Flutter version 1.26.0-2.0.pre.137 at C:\Entwicklung\flutter
    • Framework revision 8f5d0371af (3 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)
```
