### ISSUE TITLE
dart pub publish --dry-run false positive with null-safe SDK constraints

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#44711]
Consider the following `pubspec.yaml`:

```yaml
name: foo
description: The web implementation of cloud_firestore
version: 0.3.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  firebase_core: ^0.7.0-nullsafety.0
```

Executing `dart pub publish --dry-run` will warn with:

```
* Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.12.0-0, consider publishing the package as a pre-release instead.
  See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases.
* This package is opting into null-safety, but a dependency or file is not.
  
  package:firebase_core is not opted into null safety in its pubspec.yaml:
     ╷
  37 │   sdk: ">=2.1.0 <3.0.0"
     │        ^^^^^^^^^^^^^^^^
     ╵  
```

This doesn't make sense as `firebase_core: ^0.7.0-nullsafety.0` has a sdk version constraint of dart >= 2.12.x

My theory is that --dry-run picked up the SDK constraints of the non-null-safe version instead.
