### ISSUE TITLE
dartanalyzer does not respect analysis_options.yaml analyzer exclude rules

### ISSUE THREAD

**Issue by bitsydarel** [dart-lang/sdk#45000]
This tracker is for issues related to:

* Analyzer

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

* Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
* MacOSX

With the following analysis_options.yaml

```yaml
include: package:flutter_code_style/analysis_options.yaml # some package with prebuilt lint.

analyzer:
  exclude:
    - '**/*dart anslu.g.dart'
    - 'example/**/*.dart'
```

When running
```shell
dartanalyzer --options analysis_options.yaml .
```

The tool report files that are excluded.

However the command, dart analyze does not have this bug.
```shell
dart analyze
```
