### ISSUE TITLE
Dart VM tries to load native extensions with an incorrect path on Windows

### ISSUE THREAD

**Issue by blagoev** [dart-lang/sdk#45370]
Dart VM tries to load native extensions with an incorrect path on Windows

* Dart VM
* Dart SDK Version (`dart --version`) 
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "windows_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

Here are the repro steps:
* Locate this directory on the local path https://github.com/dart-lang/sdk/tree/master/samples_2/sample_extension
* Create a sample application that will be using this extension
  ```
  dart create -t console-simple mytest
  cd mytest
  ```
* add depenency to sample_extension
  ```
  dependencies:
    sample_extension: 
      path: ../
  ```

* create lib directory in `sample_extension` dir and copy `sample_synchronous_extension.dart` in it
* add pubspec.yaml in `sample_extension` dir. essentially creating a `sample_extension` dart library package
  ```
  name: sample_extension
  description: A starting point for Dart libraries or applications.
  # version: 1.0.0
  # homepage: https://www.example.com
  
  environment:
    sdk: '>=2.10.0 <3.0.0'
  
  #dependencies:
  #  path: ^1.7.0
  
  dev_dependencies:
    pedantic: ^1.9.0
    test: ^1.14.4
  ```

* do a `pub get` in mytest
* add an import to the `sample_extension` package in `bin\mytest.dart`

  ```
  import 'package:sample_extension/sample_synchronous_extension.dart';
  
  
  void main(List<String> arguments) {
    print('Hello world!');
  }
  ```

* run the app 
  ```
  dart bin\myapp.dart
  ```

* There will be an error. 
  ```
  The specified module could not be found.
  error: library handler failed
  ```
  This is normal since there is no `sample_extension.dll` in the `lib` directory of `sample_extension` library package.

* Build `sample_extension.dll` and copy it to the `lib` dir of sample_extension library

* run the app again. 

  The same error as above will be shown. 

* Using Process Monitor the issue is visible
  The Dart SDK tries to load the sample_extension.dll from an incorrect path
  
  **C:\C:\src\dart-sdk\sdk\samples_2\sample_extension\lib\sample_synchronous_extension.dartsample_extension.dll**
  
  **Notice the drive letter and the binary name are incorrect.**
  
  The correct path should be 
  **C:\src\dart-sdk\sdk\samples_2\sample_extension\lib\sample_extension.dll**
  
  If this is done on a Mac and the dylib is in the `lib` directory of the native extension the dylib is loaded and used successfully by the application.
