### ISSUE TITLE
Add an analysis option to allow specifying errors which cannot be ignored with comments.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#45404]
As a solution to https://github.com/dart-lang/sdk/issues/44237 and issues cropping up about unsafe_html, pedantic, and Flutter's web-compiled dart:ui, @bwilkerson and I are proposing an analysis option which allows for a centralized declaration of what analysis codes cannot be ignored with comments (`// ignore:` and `// ignore_for_file:`). Such codes are "un-ignorable." The proposal is a new option under the top-level `analyzer` Map, keyed to ` cannot-ignore`. For example:

```yaml
analyzer:
  errors:
    unused_import: error
  cannot-ignore:
    - error
    - unsafe_html
```

Quick notes on this option:

1. All errors can be ignored with comments, except errors listed in `cannot-ignore`.
2. The `cannot-ignore` can contain individual error codes, "unique" error codes, and the three severities which the analyzer understands: `error`, `warning`, and `info`.
3. Listing a severity like `error` will make _any_ analysis code with severity of "error" un-ignorable.
4. Listing a severity like `error` respects any severity customizations made in the `errors` section. In the example above, `unused_import` is un-ignorable.

Shortcomings and alternatives:

1. There is no complex calculus available, so there is no way to specify "all codes are un-ignorable, except a specific set of named codes." I don't think there is any ask for a concept like this; we could solve such an ask with another special format like `all_except: [list, of, codes]`.
2. This changes the default state from "errors are un-ignorable" to "nothing is un-ignorable," which is fine, as this is a broad ask. I think it would be complicated to set an option when the default is non-empty. Setting an option would not be _additive_ to "all errors;" it would replace the default.
2. Perhaps the severities should be acceptable in their plural forms? `errors`, `warnings`, and `infos`.
3. This is heading further down a path of listing "options" which include lists of codes as a top-level structure, and then codes further down. An alternative syntax would group codes together, and list all customizations of each code in one location:
   ```yaml
   analyzer:
     errors:
       unused_import:
         severity: error
         ignorable: false
         message: "{0} is an unused import; don't forget to remove from BUILD file."
       prefer_local_finals:
         include_for_declarations: true
         include_catch_declarations: true
   ```
