### ISSUE TITLE
Analyzer does not report element from deferred import used as annotation argument

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#45418]
Take these two files, `a.dart`:

```dart
const x = 0;
```

and `b.dart`

```
import 'a.dart' deferred as a;
class C { const C(int i); }
@C(a.x) main () {}
```

Analyzer reports nothing wrong, but CFE/VM complain:

```
b.dart:3:4: Error: 'a' can't be used in a constant expression because it's marked as 'deferred' which means it isn't available until loaded.
Try moving the constant from the deferred library, or removing 'deferred' from the import.

@C(a.x) main () {}
   ^
b.dart:3:2: Error: Constant evaluation error:
@C(a.x) main () {}
 ^
b.dart:3:6: Context: 'a' can't be used in a constant expression because it's marked as 'deferred' which means it isn't available until loaded.
Try moving the constant from the deferred library, or removing 'deferred' from the import.

@C(a.x) main () {}
     ^
b.dart:3:9: Context: While analyzing:
@C(a.x) main () {}
        ^
```

**Comment by lfkdsk** [comment]
It seems like that ConstEvalDeferredLibrary's corresponding analyzer code is `NON_CONSTANT_DEFAULT_VALUE_FROM_DEFERRED_LIBRARY`.


``` yaml
ConstEvalDeferredLibrary:
  template: >
    '#nameOKEmpty' can't be used in a constant expression because it's marked as
    'deferred' which means it isn't available until loaded.
  tip: >
    Try moving the constant from the deferred library, or removing 'deferred'
    from the import.
  analyzerCode: NON_CONSTANT_DEFAULT_VALUE_FROM_DEFERRED_LIBRARY

```
