### ISSUE TITLE
dart fix - addParameter - required_named - not working

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#45475]
Found in https://github.com/flutter/flutter/pull/79057
That PR is the first `addParameter` that is `required_named` that we've done in flutter/flutter. No transform is applied at all.

Here is the rule (it's a short one):
```
# Changes made in https://github.com/flutter/flutter/pull/73510
  - title: "Provide BuildContext to buildTextSpan"
    date: 2021-01-28
    element:
      uris: [ 'material.dart', 'widgets.dart', 'cupertino.dart' ]
      method: 'buildTextSpan'
      inClass: 'TextEditingController'
    changes:
      - kind: 'addParameter'
        index: 0
        name: 'context'
        style: required_named
        argumentValue:
          expression: 'context'
```
