### ISSUE TITLE
Migration Tool treats local file as an external package that hasn't migrated

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#45780]
Please see this screenshot:
![image](https://user-images.githubusercontent.com/16635729/115529389-2899ea80-a293-11eb-83dd-34327ef85e26.png)

```yaml
name: listenable_collections
description: A collection of Dart collections that behave like ValueNotifier if their data changes.
version: 0.0.5
author: Thomas Burkhart
homepage: https://github.com/escamoteur/listenable_collections

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
```
this is the repo I try to migrate https://github.com/escamoteur/listenable_collections
