### ISSUE TITLE
List.from -> List.of

### ISSUE THREAD

**Issue by PiN73** [dart-lang/sdk#45840]
This code compiles without warnings and fails in runtime:

```dart
final strings = ['hello', 'world'];

List<int> f() => List.from(strings);
final copy = List<int>.from(strings);
List<int> ints = List.from(strings);
```

Even with strong mode, analysis_options.yaml:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

Is it true that `List.of` is typed equivalent of `List.from`?

If it is, is there an option to to deprecate `from` in favor of `of`? Or generate an analyzer/lint warning when `from` used?

Dart 2.12.3
