### ISSUE TITLE
Null check operator used on a null value when running flutter build_runner

### ISSUE THREAD

**Issue by 0x-cell** [dart-lang/sdk#45866]
I've decided to update Moor (https://github.com/simolus3/moor) to latest version and now I'm getting following crash when trying to run `flutter packages pub run build_runner build --delete-conflicting-outputs -v`.

Again, any help appreciated. Any information of what I might be looking for.

According to the Moor owner (https://github.com/simolus3/moor/issues/1166) it's an issue in **Dart analyzer**.

```
...
[FINE] moor_generator:moor_generator on lib/home.dart:Running DaoGenerator - 2 of 2
[FINE] moor_generator:moor_generator on lib/instagram/constants.dart:Running MoorGenerator - 1 of 2
[SEVERE] moor_generator:moor_generator on lib/animations/popup.route.dart:

Null check operator used on a null value
#0      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:418:48)
#1      LibraryContext.isLibraryUri (package:analyzer/src/dart/analysis/library_context.dart:95:27)
#2      LibraryAnalyzer._isLibrarySource (package:analyzer/src/dart/analysis/library_analyzer.dart:511:25)
#3      LibraryAnalyzer._resolveDirectives (package:analyzer/src/dart/analysis/library_analyzer.dart:552:36)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:128:5)
#5      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:12)
#6      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1590:63)
#7      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1565:20)
#9      AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1644:26)
#10     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1266:20)
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2296:24)
<asynchronous suspension>

package:analyzer/src/dart/analysis/driver.dart 1619:9             AnalysisDriver._computeAnalysisResult.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1565:20            AnalysisDriver._computeAnalysisResult
package:analyzer/src/dart/analysis/driver.dart 1644:26            AnalysisDriver._computeErrors
package:analyzer/src/dart/analysis/driver.dart 1266:20            AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2296:24            AnalysisDriverScheduler._run

[INFO] Heartbeat:19.0s elapsed, 31/47 actions completed.
[INFO] Heartbeat:20.1s elapsed, 31/47 actions completed.
[INFO] Heartbeat:21.1s elapsed, 31/47 actions completed.
[INFO] Heartbeat:22.2s elapsed, 31/47 actions completed.
```

flutter doctor
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)
```

flutter --version
```
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (13 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

dart --version
```
Dart SDK version: 2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "windows_x64"
```

pubsec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  http: ^0.13.0
  shimmer: ^1.1.1
  moor_flutter: ^4.0.0
  moor: ^4.2.1
  provider: ^4.2.0
  cached_network_image: ^3.0.0
  flutter_inapp_purchase: ^4.0.2
  rate_my_app: ^0.6.1+6
  simple_auth: ^2.0.7
  simple_auth_flutter: ^2.0.7
  dio: ^4.0.0
  sprintf: "^4.0.0"
  url_launcher: ^6.0.3
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  package_info: ^0.4.3
  modal_bottom_sheet: ^2.0.0
  another_flushbar: ^1.10.17
  flutter_svg: ^0.22.0
  webview_flutter: ^1.0.7
  delayed_display: ^1.1.0
  lottie: ^1.0.1
  launch_review: ^3.0.0
  smooth_page_indicator: ^0.2.0
  auto_size_text: ^2.1.0
  flutter_markdown: ^0.6.1
  google_nav_bar: ^5.0.3
  preload_page_view: ^0.1.6
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.2.2
  build_runner: ^2.0.1
```
