### ISSUE TITLE
Allow url in "include" section of analysis_options.yaml

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#47184]
This will allow to have something like :

```yaml
# all lints or a custom set of lints I want on all my project
include: https://raw.githubusercontent.com/dart-lang/linter/1.11.0/example/all.yaml 
linter:
  rules:
    avoid_shadowing_type_parameters: false
```

Related to https://github.com/dart-lang/linter/issues/1765 and https://github.com/dart-lang/linter/issues/1889
