### ISSUE TITLE
Regression in how `dart pub` handles paths to folders in dependency

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#47199]
* Dart SDK Version: 2.14.1
* OS: Windows 10

I apologize if this is the wrong repository, but I couldn't find the correct one for `dart pub`, `pub dev` seems to be for the website only. 

In my `pubspec.yaml`, I have the following dependency:
```yaml
dependencies:
  my_git_package:
    git:
      url: git@github.com:my-name/my-package.git
      path: client/my_package
```

On previous versions of Dart, running the `dart pub run build_runner build` command works perfectly fine. However, ever since updating to Dart 2.14.1, the command fails with the failing error message:
```
Could not find a file named "pubspec.yaml" in "C:\Users\my_name\Documents\flutter\.pub-cache\git\my-package/-24c1cc683c7b5e6a54dadb6cb52391a301a4cf8a\client%5Cmy_package".
```

Appending a `/` at the end of `path: client/my_package` in the pubspec.yaml seems to fix the issue. Nevertheless, it seems to be a regression and a potential source of confusion for new developers trying to use their git repository as a dependency.
