### ISSUE TITLE
Dart compiler exits when running flutter test

### ISSUE THREAD

**Issue by nyck33** [dart-lang/sdk#47327]
```
Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 10:3  throwToolExit
  package:flutter_tools/src/compile.dart 778:9     DefaultResidentCompiler._compile.<fn>
  dart:async/zone.dart 1436:47                     _rootRunUnary
  dart:async/zone.dart 1335:19                     _CustomZone.runUnary
```
Sometimes I was getting fast scrolling errors sometthing about Dart but the output window of VSCode would fill up and keep scrolling with the same-ish error.  And now this.  What is happening?  
I am on Ubuntu 20.04 `Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "linux_x64"`

**Comment by lrhn** [comment]
This looks like an error reported by [`flutter_tools/src/compile.dart`](https://github.com/flutter/flutter/blob/367531447c8035e2a1e9b6b54a81fab354355235/packages/flutter_tools/lib/src/compile.dart#L776) after the dart compiler exits with an error number greater than zero. That can have any number of causes, it's impossible to tell why without further information.

If you can capture any of the other error messages, we might be able to figure out more.

**Comment by nyck33** [comment]
```
(base) nobu@nobu-IdeaPad-3-15IIL05:/media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app$ flutter test
00:03 +0: loading /media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app/test/dummy_test.dart                     lib/views/coupons_screen/coupons_screen.dart:10:8: Error: Error when reading
'repositories/fastapi_providers.dart': No such file or directory
import '../../../repositories/fastapi_providers.dart';
       ^
lib/views/coupons_screen/coupons_screen.dart:11:8: Error: Error when reading 'models/data_layer.dart': No
such file or directory
import '../../../models/data_layer.dart';
       ^
lib/views/details_screen/details_screen.dart:11:8: Error: Error when reading 'models/data_layer.dart': No
such file or directory
import '../../../models/data_layer.dart';
       ^
lib/views/coupons_screen/coupons_screen.dart:12:8: Error: Error when reading 'providers.dart': No such file
or directory
import '../../../providers.dart';
       ^
lib/views/details_screen/details_screen.dart:12:8: Error: Error when reading 'providers.dart': No such file
or directory
import '../../../providers.dart';
       ^
lib/controllers/controller.dart:8:8: Error: Error when reading 'type_enums/enum_exports.dart': No such file
or directory
import '../../type_enums/enum_exports.dart';
       ^
lib/repositories/shared_prefs_repo.dart:3:8: Error: Error when reading 'models/data_layer.dart': No such
file or directory
import '../../models/data_layer.dart';
       ^
00:04 +2: ... /media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app/test/golden_widget_test.dart                 lib/views/coupons_screen/coupons_screen.dart:44:8: Error: Type 'Coupon' not found.
  List<Coupon> combineOldNewCoupons(
       ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:45:32: Error: Type 'Coupon' not found.
      Response? response, List<Coupon> oldCoupons) {
                               ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:72:3: Error: Type 'Coupon' not found.
  Coupon convertJsonToCoupon(Map<String, dynamic> newCoupon) =>
  ^^^^^^
lib/views/details_screen/details_screen.dart:44:3: Error: Type 'Coupon' not found.
  Coupon? getThisCouponFromState(List<Coupon> couponsList) {
  ^^^^^^
lib/views/details_screen/details_screen.dart:44:39: Error: Type 'Coupon' not found.
  Coupon? getThisCouponFromState(List<Coupon> couponsList) {
                                      ^^^^^^
lib/controllers/controller.dart:40:29: Error: Type 'CurrentScreen' not found.
  void updateCurrentScreen({CurrentScreen? screen}) {
                            ^^^^^^^^^^^^^
lib/repositories/shared_prefs_repo.dart:10:26: Error: Type 'User' not found.
  Future<void>? saveUser(User user) async {
                         ^^^^
00:05 +2: ... /media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app/test/golden_widget_test.dart                 lib/views/coupons_screen/coupons_screen.dart:45:32: Error: 'Coupon' isn't a type.
      Response? response, List<Coupon> oldCoupons) {
                               ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:56:10: Error: 'Coupon' isn't a type.
    List<Coupon> combinedCoupons = [...oldCoupons];
         ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:58:12: Error: 'Coupon' isn't a type.
      for (Coupon oldC in oldCoupons) {
           ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:68:38: Error: The getter 'couponId' isn't defined for the class
'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'couponId'.
    combinedCoupons.sort((a, b) => a.couponId.compareTo(b.couponId));
                                     ^^^^^^^^
lib/views/coupons_screen/coupons_screen.dart:68:59: Error: The getter 'couponId' isn't defined for the class
'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'couponId'.
    combinedCoupons.sort((a, b) => a.couponId.compareTo(b.couponId));
                                                          ^^^^^^^^
lib/views/coupons_screen/coupons_screen.dart:73:7: Error: The getter 'Coupon' isn't defined for the class
'_CouponsScreenState'.
 - '_CouponsScreenState' is from 'lib/views/coupons_screen/coupons_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Coupon'.
      Coupon.fromJson(newCoupon);
      ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:109:16: Error: 'Coupon' isn't a type.
          List<Coupon> coupons = combineOldNewCoupons(response, oldCoupons);
               ^^^^^^
lib/views/coupons_screen/coupons_screen.dart:78:15: Error: The getter 'userProvider' isn't defined for the
class '_CouponsScreenState'.
 - '_CouponsScreenState' is from 'lib/views/coupons_screen/coupons_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
        .read(userProvider.notifier)
              ^^^^^^^^^^^^
lib/views/coupons_screen/coupons_screen.dart:80:27: Error: The getter 'userProvider' isn't defined for the
class '_CouponsScreenState'.
 - '_CouponsScreenState' is from 'lib/views/coupons_screen/coupons_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
    final user = ref.read(userProvider.notifier).state;
                          ^^^^^^^^^^^^
lib/views/coupons_screen/coupons_screen.dart:89:32: Error: The method 'fastApiRespJsonProvider' isn't
defined for the class '_CouponsScreenState'.
 - '_CouponsScreenState' is from 'lib/views/coupons_screen/coupons_screen.dart'.
Try correcting the name to the name of an existing method, or defining a method named
'fastApiRespJsonProvider'.
    final response = ref.watch(fastApiRespJsonProvider(path));
                               ^^^^^^^^^^^^^^^^^^^^^^^
lib/views/coupons_screen/coupons_screen.dart:111:20: Error: The getter 'userProvider' isn't defined for the
class '_CouponsScreenState'.
 - '_CouponsScreenState' is from 'lib/views/coupons_screen/coupons_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
          ref.read(userProvider.notifier).updateUserCoupons(coupons);
                   ^^^^^^^^^^^^
lib/views/coupons_screen/coupons_screen.dart:248:15: Error: The getter 'userProvider' isn't defined for the
class '_CouponsScreenState'.
 - '_CouponsScreenState' is from 'lib/views/coupons_screen/coupons_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
        .read(userProvider.notifier)
              ^^^^^^^^^^^^
lib/views/details_screen/details_screen.dart:38:14: Error: The getter 'userProvider' isn't defined for the
class '_DetailsScreenState'.
 - '_DetailsScreenState' is from 'lib/views/details_screen/details_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
    ref.read(userProvider.notifier).updateCoupon(targetCouponId: couponId);
             ^^^^^^^^^^^^
lib/views/details_screen/details_screen.dart:39:14: Error: The getter 'userProvider' isn't defined for the
class '_DetailsScreenState'.
 - '_DetailsScreenState' is from 'lib/views/details_screen/details_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
    ref.read(userProvider.notifier).updateUserOnServer();
             ^^^^^^^^^^^^
lib/views/details_screen/details_screen.dart:44:39: Error: 'Coupon' isn't a type.
  Coupon? getThisCouponFromState(List<Coupon> couponsList) {
                                      ^^^^^^
lib/views/details_screen/details_screen.dart:45:10: Error: 'Coupon' isn't a type.
    for (Coupon c in couponsList) {
         ^^^^^^
lib/views/details_screen/details_screen.dart:54:28: Error: The getter 'userProvider' isn't defined for the
class '_DetailsScreenState'.
 - '_DetailsScreenState' is from 'lib/views/details_screen/details_screen.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named
'userProvider'.
    final user = ref.watch(userProvider.notifier).state;
                           ^^^^^^^^^^^^
lib/views/first_screen/first_screen.dart:28:14: Error: 'userProvider' is imported from both
'package:coupon_app/providers.dart' and 'lib/providers.dart'.
    ref.read(userProvider.notifier).initializeUser(user);
             ^^^^^^^^^^^^
lib/views/first_screen/first_screen.dart:30:15: Error: 'userProvider' is imported from both
'package:coupon_app/providers.dart' and 'lib/providers.dart'.
        .read(userProvider.notifier)
              ^^^^^^^^^^^^
lib/views/first_screen/first_screen.dart:32:32: Error: 'userProvider' is imported from both
'package:coupon_app/providers.dart' and 'lib/providers.dart'.
    final checkUser = ref.read(userProvider.notifier).state;
                               ^^^^^^^^^^^^
lib/controllers/controller.dart:34:38: Error: The argument type 'User/*1*/' can't be assigned to the
parameter type 'User/*2*/'.
 - 'User/*1*/' is from 'lib/models/user.dart'.
 - 'User/*2*/' is from 'package:coupon_app/models/user.dart' ('lib/models/user.dart').
      sharedPreferencesRepo.saveUser(user);
                                     ^
lib/controllers/controller.dart:40:29: Error: 'CurrentScreen' isn't a type.
  void updateCurrentScreen({CurrentScreen? screen}) {
                            ^^^^^^^^^^^^^
lib/repositories/shared_prefs_repo.dart:10:26: Error: 'User' isn't a type.
  Future<void>? saveUser(User user) async {
                         ^^^^
lib/repositories/shared_prefs_repo.dart:31:14: Error: The getter 'User' isn't defined for the class
'SharedPreferencesRepo'.
 - 'SharedPreferencesRepo' is from 'lib/repositories/shared_prefs_repo.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'User'.
      return User.fromJson(userJson);
             ^^^^
00:08 +2 -1: loading /media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app/test/golden_widget_test.dart [E]      
  Failed to load "/media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app/test/golden_widget_test.dart": Compilation failed for testPath=/media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app/test/golden_widget_test.dart
00:08 +2 -1: Some tests failed.                                                                            
(base) nobu@nobu-IdeaPad-3-15IIL05:/media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app$ 
```
All of those errors are wrong.  My app runs and I have zero red squigglies anywhere in my app code (VSCode).  Android Studio throws same errors. I will try to capture those scrolling errors I mentioned. when I see them next..  Is there a workaround for the time being?  Ie. downgrade Flutter and Dart?  I am using the newest Flutter 2.5.1 or something and I know the latest Dart SDK comes with it.

**Comment by nyck33** [comment]
If you have time to try it out in my full app, here it is: https://drive.google.com/drive/folders/1DoUbj3S3bhkUKS8CIRuBctDp0lbIi5NV?usp=sharing  Running flutter test from the project root leads to the original errors above.

**Comment by nyck33** [comment]
Does not having dart in my PATH have any relevance?
```
(base) nobu@nobu-IdeaPad-3-15IIL05:~$ env | grep PATH
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
WINDOWPATH=2
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PATH=/home/nobu/.rbenv/shims:/home/nobu/.rbenv/bin:/home/nobu/.rbenv/shims:/home/nobu/.kusanagi/bin:/home/nobu/anaconda3/bin:/home/nobu/anaconda3/condabin:/home/nobu/.rbenv/shims:/home/nobu/.rbenv/shims:/home/nobu/.rbenv/bin:/home/nobu/.poetry/bin:/home/nobu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/nobu/go/bin:/usr/local/go/bin:/home/nobu/go/bin:/usr/local/go/bin:/home/nobu/go/bin
GOPATH=/home/nobu/go
```

**Comment by nyck33** [comment]
I removed `golden_toolkit` package and it is fine now.  
My former golden test file under folder test
```


import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'package:golden_toolkit/golden_toolkit.dart';
import '../lib/views/views_layer.dart';
import '../lib/dummy_data/dummy_user.dart' as dummy;
import '../lib/models/data_layer.dart';

final User mockUser = User(userId: -100, name: 'mock', email: "mock@mock.com");
final User copyUser = dummy.dummyUser.copyWith(userId: -100);
void main() {
  testGoldens('FirstScreen has DeathStar', (WidgetTester tester) async {
    await tester.pumpWidget(FirstScreen(user: mockUser));
    await screenMatchesGolden(tester, 'firstscreen_deathstar');
  });
}
```
and my pubspec.yaml
```
name: coupon_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^1.0.0-dev.7
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  
  uuid:
  http: 

  sqflite: ^2.0.0+4
  path: 
  
  #json_annotation: ^4.0.1
  #freezed: ^0.14.0
  freezed_annotation: ^0.14.3
  #json_serializable: ^5.0.0
  built_value: 
  shared_preferences: 2.0.7
  #golden_toolkit: ^0.10.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  enum_to_string: ^2.0.1

dev_dependencies:
  
  freezed: ^0.14.5
  #https://github.com/rrousselGit/freezed/issues/86#issuecomment-593936459
  json_serializable: ^5.0.0
    #options:
      #explicit_to_json: true
  build_runner: #^1.11.0
  built_value_generator: 
  mockito: ^5.0.16 
  test: ^1.17.10
  flutter_driver: 
    sdk: flutter 
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter

#dependency_overrides:
  #meta: ^1.3.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/no-img.png
    - assets/images/starwars/
    - assets/images/coupons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
