### ISSUE TITLE
Weird inheritance behavior

### ISSUE THREAD

**Issue by MbIXjkee** [dart-lang/sdk#47792]
Hi! I found weird inheritance behavior. Using interfaces, you can expose protected methods of the parent class. I am attaching a sample code that will demonstrate the problem.

* Dart SDK Version Dart SDK version: 2.14.0 (stable) (Mon Sep 6 13:47:59 2021 +0200) on "macos_x64"

Sample:

file A contains
```
import 'package:meta/meta.dart';

abstract class IA {}

class A implements IA {
  @protected
  void someProtectedMethod() {}
}
```

file B contains

```
void main() {
  var b = B();
  
  b.someProtectedMethod();
}

abstract class IB extends IA {
  void someProtectedMethod();
}

class B extends A implements IB {}
```

**Comment by eernstg** [comment]
Just noticed this issue in passing, and checked it locally: On Linux I get the following hint message (when the example program is stored in `n016.dart` and `n016lib.dart`):

```
Analyzing n016.dart...                 1.4s

   info • n016.dart:6:5 • The member 'someProtectedMethod' can only be used
          within instance members of subclasses of
          'package:n016/n016lib.dart'. •
          invalid_use_of_protected_member

1 issue found.
```

You wouldn't by any chance have disabled that hint?

```yaml
// analysis_options.yaml, or a file x.yaml together with `--options=x.yaml`
analyzer:
  errors:
    invalid_use_of_protected_member: ignore
```

**Comment by MbIXjkee** [comment]
> Just noticed this issue in passing, and checked it locally: On Linux I get the following hint message (when the example program is stored in `n016.dart` and `n016lib.dart`):
> 
> ```
> Analyzing n016.dart...                 1.4s
> 
>    info • n016.dart:6:5 • The member 'someProtectedMethod' can only be used
>           within instance members of subclasses of
>           'package:n016/n016lib.dart'. •
>           invalid_use_of_protected_member
> 
> 1 issue found.
> ```
> 
> You wouldn't by any chance have disabled that hint?
> 
> ```yaml
> // analysis_options.yaml, or a file x.yaml together with `--options=x.yaml`
> analyzer:
>   errors:
>     invalid_use_of_protected_member: ignore
> ```

In my case invalid_use_of_protected_member is not disabled.

my rules:
```
include: package:surf_lint_rules/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    one_member_abstracts: false
    public_member_api_docs: true
```

package:surf_lint_rules also not disable this rule.
