### ISSUE TITLE
I need an error, not just a warning (@immutable) 

### ISSUE THREAD

**Issue by ChannelYu** [dart-lang/sdk#47997]
See [here](https://github.com/flutter/flutter/issues/86770)

**Comment by julemand101** [comment]
Add the following to your `analysis_options.yaml`:
```yaml
analyzer:
  errors:
    must_be_immutable: error
```
