### ISSUE TITLE
Invalid argument(s): Missing library when run build_runner

### ISSUE THREAD

**Issue by wondertalik** [dart-lang/sdk#48007]
Hello, cant run build to generate json models. After run comman 

```flutter pub run build_runner build --delete-conflicting-outputs```

got en error

```
Invalid argument(s): Missing library: package:syncfusion_flutter_pdf/src/pdf/implementation/primitives//pdf_name.dart
Available libraries: [dart:typed_data, dart:convert, dart:math, dart:core, dart:_internal, dart:collection, dart:async, dart:isolate, dart:developer, dart:ffi, dart:_js_embedded_names, dart:_js_names, dart:_recipe_syntax, dart:_rti, dart:_foreign_helper, dart:_js_helper, dart:_interceptors, dart:_native_typed_data, dart:web_gl, dart:js_util, dart:_metadata, dart:html_common, dart:indexed_db, dart:svg, dart:web_audio, dart:html, dart:io, dart:_http, dart:js, dart:_js, dart:mirrors, dart:nativewrappers, dart:cli, dart:_late_helper, dart:_dart2js_runtime_metrics, dart:_js_primitives, dart:_async_await_error_codes, dart:_js_annotations, dart:_spirv, dart:ui]
...
```
Full log in [error.txt](https://github.com/dart-lang/sdk/files/7768094/error.txt)

Perhaps because the path with two // at the end.

```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-AD)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)

• No issues found!
```

```
Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
```

pubspec.yaml

```
name: employee_app
description: A new Flutter project.
publish_to: none
version: 1.16.1+45
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  dropdown_button2: ^1.0.7
  email_validator: ^2.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  formz: ^0.4.0
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  mocktail: ^0.2.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.5
  scrollable_positioned_list: ^0.2.2
  sentry_flutter: ^6.0.0
  share_plus: ^3.0.2
  shared_preferences: ^2.0.7
  signature: ^4.1.1
  string_extensions: ^0.4.0
  syncfusion_flutter_pdf: ^19.4.38-beta
  syncfusion_flutter_pdfviewer: ^19.4.38-beta
  
dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  lints: ^1.0.1
flutter_icons:
  android: launcher_icon
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/app_icon.png
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/svg/

```

```
 git:(main) ✗ flutter pub outdated                                                                                                          
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name         Current   Upgradable  Resolvable  Latest  

direct dependencies:
signature            *4.1.1    *4.1.1      5.0.0       5.0.0   

dev_dependencies: all up-to-date.

transitive dependencies:
_fe_analyzer_shared  *31.0.0   *31.0.0     *31.0.0     32.0.0  
analyzer             *2.8.0    *2.8.0      *2.8.0      3.0.0   
coverage             *1.0.3    *1.0.3      *1.0.3      1.0.4   
js                   *0.6.3    *0.6.3      *0.6.3      0.6.4   
path                 *1.8.0    *1.8.0      *1.8.0      1.8.1   
test                 *1.17.12  *1.17.12    *1.17.12    1.20.1  
test_api             *0.4.3    *0.4.3      *0.4.3      0.4.9   
test_core            *0.4.2    *0.4.2      *0.4.2      0.4.11  
vm_service           *7.5.0    *7.5.0      *7.5.0      8.1.0  
```
