### ISSUE TITLE
Unexpected analyze argument_type_not_assignable error

### ISSUE THREAD

**Issue by cyliale** [dart-lang/sdk#48395]
Hello i have the some analyze errors on use of fnString() and fnInt() when i use this sample test code. Comments in code.

Type seems not promoted in lambda function arguments.

Source code is

```dart
bool fnString(final String s) => s == 'text';
bool fnInt(final int i) => i == 1;
void main() {
  test('DART bug : analyze error in expect lambda function', () {
    Object? o = 'text';
    if (o is! String) {
      fail('o should be a String');
    }
    // Ok: unrelated_type_equality_checks lint error for "o == 1" as expected
    expect(o == 1, false);
    // Ok: o is seen as a String
    expect(o == 'text', true);
    // Ok: o is seen as a String
    expect(() => o == 'text', true);
    // Bug: argument_type_not_assignable analyze error
    // o is seen as an Object? instead of a String !!!
    expect(() => fnString(o), true);

    o = 1;
    if (o is! int) {
      fail('o should be an int');
    }
    // Ok: unrelated_type_equality_checks lint error for "o == 'text'" as expected
    expect(o == 'text', false);
    // Ok: o is seen as a int
    expect(o == 1, true);
    // Ok: o is seen as a int
    expect(() => o == 1, true);
    // Bug: argument_type_not_assignable analyze error
    // o is seen as an Object? instead of an int !!!
    expect(() => fnInt(o), true);
  });
}
```

Dart SDK version: 2.16.1 (stable) (Unknown timestamp) on "linux_x64"

**Comment by cyliale** [comment]
If i write "final s = o;" just before then "expect(() => fnString(s), true);" has no analyze error.
If i write "final i = o;" just before then "expect(() => fnInt(i), true);" has no analyze error.

But it would be nice to not be obliged to write these additional lines.

**Comment by cyliale** [comment]
If you need my yaml config.

```
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.8.1
  matcher: '>=0.12.3 <0.14.0'
  test: ^1.16.0
```

and my analysis options.

```
include: all_lint_rules.yaml
analyzer:
  exclude:
  #- '**.freezed.dart'

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    todo: ignore

linter:
  rules:
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_final_parameters: false
    prefer_double_quotes: false
    require_trailing_commas: false
    sort_constructors_first: false
    unnecessary_final: false
```
