### ISSUE TITLE
`Object.hash` on type used in static map constructor causes JS error in dart2js builds

### ISSUE THREAD

**Issue by jorgenpt** [dart-lang/sdk#48442]
> Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"

Trying to construct a `static final` map with a type that uses `Object.hash` in its `hashCode` implementation will throw a .js error when running in release mode.

Repro:
1. `dart create -t web-simple object_hashcode_repro`
2. Enter the below snippet into `object_hashcode_repro/web/main.dart`
3. Run with `webdev serve --launch-in-chrome  --release` (or switch the debug configuration in `build.yaml` to use dart2js and omit `--debug`)

Output:
```
Uncaught TypeError: $.$get$_hashSeed is not a function
    at Object_hash (object.dart:202:67)
    at Foo.get$hashCode (main.dart:12:23)
    at Object.get$hashCode$ (main.dart.js:2769:42)
    at Object.fillLiteralMap (linked_hash_map.dart:289:43)
    at Object.LinkedHashMap_LinkedHashMap$_literal (collection_patch.dart:541:12)
    at staticFields (main.dart.js:3568:19)
    at dartProgram (main.dart.js:3569:5)
    at js_helper.dart:2666:31
```

main.dart:
```dart
import 'dart:html';

class Foo {
  static const bar = Foo();
  const Foo();

  static final map = {
    bar: "bar",
  };

  @override
  int get hashCode => Object.hash(0, 1);

  @override
  bool operator ==(other) => other is Foo;
}


void main() {
  querySelector('#output')?.text = Foo.map[const Foo()];
}
```

Optional build.yaml to reproduce in debug builds too:
```yaml
targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
        - web/**.dart
        options:
          compiler: dart2js
```
