### ISSUE TITLE
feature request: dart create template for FFI packages

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#48653]
I have found myself making FFI wrapper packages quite a lot lately. 

So I have been some repetitive steps setting up each package with a few common steps to set up FFI on top of the `package-simple` template, so it would be nice to have this as a template as I suspect that this is becoming a more common use case for Dart packages as FFI has matured into a very useful feature. I think this would also be a good opportunity to provide developers with FFI "best practises" in the template.

Some of the things that I do pretty consistently for all new FFI package projects are:
* add ffi package dependency
* add `ffigen` dev dependency and a basic ffigen config in pubspec.yaml, eg.
```
ffigen:
  name: "libgit2"
  output: "lib/src/libgit2_generated_bindings.dart"
  headers:
    entry-points:
      - "/usr/include/git2.h"
  llvm-path:
    - "/usr/lib/llvm-13"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
```
* add a analyzer exclusion for the generated file:
```
analyzer:
  exclude:
    - "lib/src/libgit2_generated_bindings.dart"
```
Create a wrapper file that calls the generated code, eg:
```
final git2 = libgit2(DynamicLibrary.open(libPath));
```
Create example file with a main calling the above:
```
void main(List<String> args) {
  final v = LibGit2().version();
  print('libgit2 version: $v');
}
```

Having a template to do all the above would be nice.

Above examples are from [one of my recently started FFI binding packages](https://github.com/maks/dart_libgit2) but of course you can see my cargo-culting the above sort of recipe on several other FFI wrapper packages I have made.
