### ISSUE TITLE
[analyzer] todo and fixme ignored by analyzer

### ISSUE THREAD

**Issue by lowski** [dart-lang/sdk#49061]
I want to have the dart static analyzer show a warning if there are open TODO items. I have configured the analysis_options.yaml accordingly:

```yaml
include: package:lints/recommended.yaml
analyzer:
  errors:
    todo: warning
```

Now VSCode does highlight the todos as warnings and they do appear in the Problems panel. However, if I run `dart analyze` they don't show up. Same thing with FIXME (and appropriate analysis_options.yaml). I could not find any documentation, that this is on purpose and I think these errors should be configurable the same way as other errors.

I tested this on a fresh dart project and I'm using Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64" (Apple Silicon).
