### ISSUE TITLE
**Socket error: FileSystemException: Directory watcher closed unexpectedly**

### ISSUE THREAD

**Issue by RB-93** [dart-lang/sdk#49286]
Whenever I try to run or build my project, the above issue occurs. (see screenshot)

The **build/** directory gets updated which is usually normal.

But the issue causes the build time to get longer.

Flutter Doctor output:
flutter doctor -v
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 3.0.2 at C:\Users\rohit\Documents\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (9 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3       
    • DevTools version 2.12.2   

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\rohit\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.0)
    • VS Code at C:\Users\rohit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • Moto Z2 Play (mobile) • 192.168.29.253:5555 • android-arm    • Android 8.0.0 (API 26)
    • Windows (desktop)     • windows             • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)          • chrome              • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)            • edge                • web-javascript • Microsoft Edge 102.0.1245.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

![174237004-91018422-6228-41cc-baa2-fe714c00ac64.png](https://user-images.githubusercontent.com/29726705/174416901-73b9918e-8dd1-439b-a532-eeb1cd4b6b67.png)

_Originally posted by @RB-93 in https://github.com/dart-lang/sdk/issues/38853#issuecomment-1158531992_

**Comment by keertip** [comment]
@DanTup , have you seen this before?

**Comment by kevinxxq** [comment]
I have this issue after deleting the whole build folder. I tried to reload the IDE and build it again, it works now.

**Comment by DanTup** [comment]
@kevinxxq can you reproduce this? Does it occur just when you delete the `build` folder while the editor is open?

**Comment by kevinxxq** [comment]
Hi Danny, I just trided again, it didn't take place again. Yes, the eidtor is open. Thank you.

**Comment by alphapokedex** [comment]
@DanTup I've been encountering this same issue since after 18th June as far as I can remember.

![image](https://user-images.githubusercontent.com/52071686/178923037-d567b6cb-aadc-47f9-8d0c-1cfe44aae235.png)

In M1 and Win 11 both, in all of the flutter projects.

It occurred this time when I cloned ran for the first time using VSC, closed the application instance from my device recents.

**Comment by DanTup** [comment]
@alphapokedex

> On restarting the machine, did not see it again for Win11.

Do you mean you can no longer reproduce it with the same project? If you can, does it occur only with that project, or also with a new project created with the **Flutter: New Project** command? If not, could you share the pubspec of the project that does trigger it?

Can you also confirm if the error message _exactly_ the same when it occurs on macOS, or different?

**Comment by alphapokedex** [comment]
Hi @DanTup I encountered this issue for the same project right now.

I had just booted up my machine and started VSC for this project, after few seconds of debug session startup...

I checked the outputs section

```
[Error - 9:32:22 am] Socket error: FileSystemException: Directory watcher closed unexpectedly, path = 'c:\Users\alpha\Documents\GitHub\Spidr': FileSystemException: Directory watcher closed unexpectedly, path = 'c:\Users\alpha\Documents\GitHub\Spidr'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:354:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:232:30)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#3      _rootRunUnary (dart:async/zone.dart:1442:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#9      _StreamController._add (dart:async/stream_controller.dart:648:7)
#10     _StreamController.add (dart:async/stream_controller.dart:596:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1846:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

I'll try to recreate with the new project as well.
Yes the error message is exactly the same for all the devices, I've noticed for my colleague's VSC as well.
Thank you

**Comment by DanTup** [comment]
@alphapokedex if you can repro this in a clean new project, could you try the following _in the new project_:

- Run **Preferences: Open Workspace Settings (JSON)** command from the command palette
- Paste in `"dart.analyzerInstrumentationLogFile": "logs/analyzer.txt",` inside the JSON object
- Wait a few moments for the analysis server to restart - you should see the `logs/analyzer.txt` file created in your project
- Run the app to trigger the issue
- Confirm the log file includes the error text "Directory watcher closed unexpectedly" and attach it here / in a [gist](https://gist.github.com/)

**Comment by alphapokedex** [comment]
Hi @DanTup I was unable to find exact steps to reproduce this issue every time, but here are the steps to reproduce it occasionally.

1. Run **Flutter: New Project** from VSC Command Palette.
2. Create a clean flutter project.
3. Update the `pubspec.yaml
``` yaml
  cloud_firestore: ^3.1.18
  country_code_picker: ^2.0.1
  dio: ^4.0.6
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.2
  firebase_core: ^1.19.2
  flutter_bluetooth_serial: ^0.4.0
  firebase_database: ^9.0.19
  flutter_pin_code_fields: ^1.1.0
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^3.2.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  geolocator: ^9.0.1
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  syncfusion_flutter_charts: ^20.2.38
  intl: ^0.17.0
  permission: ^0.1.7
  csv: ^5.0.1
  share: ^2.0.4
  filesystem_picker: ^2.0.1
  geocoding: ^2.0.4
  app_settings: ^4.1.8
  flutter_typeahead: ^4.0.0
  firebase_messaging: ^12.0.0
  sqflite: ^2.0.3
  provider: ^6.0.3
  horizontal_data_table: ^4.1.1+1
  syncfusion_flutter_gauges: ^20.2.38
  url_launcher: ^6.0.20
  timeago: ^3.2.2
  android_intent_plus: ^3.1.1
  logger: ^1.1.0
  flutter_timer_countdown: ^1.0.3
```

4. Update minSdkVersion to 19
5. Run `flutter pub get`
6. Press `F5` or Start project in debug mode.
7. After the application successfully starts up in your device.
8. Terminate the debug mode.
9. Run `flutter clean && exit`
10. Close project folder.
11. Close all VSC windows.
12. Open VSC & open the same project.
13. Press `F5` or Start project in debug mode.
14. You'll see a message box with `Socket error: FileSystemException: Directory watcher closed unexpectedly` message.

here is the gist for [analyzer.txt](https://gist.github.com/alphapokedex/cbc57838c4b3f138846ad092d913662b.js)

Hope you are able to see the same on your machine.

Thank you
