### ISSUE TITLE
[analysis_server] provide a fix to disable a lint rule in `analysis_options.yaml`

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#49572]
**Description**
Provide a fix to disable a lint rule in `analysis_options.yaml` that is similar to ignore diagnostic fixes. The ignore diagnostic fixes can either ignore a line or an entire file by adding a comment above the line to be ignored or the top of the file for the entire file to be ignored (e.g. `// ignore:  public_member_api_docs` for a line). 

A fix to disable a specific lint rule would instead disable the lint rule in the `analysis_options.yaml` file such as:

```yaml
include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    public_member_api_docs: false  # <~~~~~~~ add here by the quick fix
```

**Additional Context** 
This feature request is necessary for an downstream feature request in the VS Code extension repo which can be found here: https://github.com/Dart-Code/Dart-Code/issues/4079

**Comment by MarlonJD** [comment]
Is there any news about this?

**Comment by bwilkerson** [comment]
> Is there any news about this?

No, I'm sorry, but there isn't. While we agree that this would be a good feature to have, it isn't currently at the top of the priority list.

**Comment by osaxma** [comment]
CL submitted at: https://dart-review.googlesource.com/c/sdk/+/352220 

Though unlike the example I provided above, the CL adds `ignore` fix  to the `analyzer.errors` label such that:

```yaml
analyzer: 
  errors:
     public_member_api_docs: ignore
```

I believe the above works for any kind of warning/error.  For instance, `unused_import` cannot only be ignored when added `analyzer.errors`.

I hope I am not missing anything out and any feedback/review is appreciated.
