### ISSUE TITLE
`dart fix` doesn't add optional parameters in subclasses

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#49854]
I was attempting to make a `dart fix` entry for a change made to the Flutter repo ([flutter/flutter#109808]([https://github.com/flutter/flutter/pull/109808])) where we added a parameter to the abstract class member function `SliderTrackShape.paint`. The parameter is an optional (nullable) named parameter that was `Offset? secondaryOffset`.

To author this fix, I wrote this in the `fix_data.yaml` file:

```yaml
  # Changes made in https://github.com/flutter/flutter/pull/109808
  - title: "Add secondaryOffset to paint() in subclasses of 'SliderTrackShape'"
    date: 2022-08-29
    element:
      uris: [ 'material.dart' ]
      method: 'paint'
      inClass: 'SliderTrackShape'
    changes:
    - kind: 'addParameter'
      index: 6
      name: 'secondaryOffset'
      style: optional_named
      argumentValue:
        expression: ''
```

When I ran this on the following dart file with `dart fix test.dart`, dart responded with "Nothing to fix!":

```dart
import 'package:flutter/material.dart';

class MyTrackShape extends SliderTrackShape {
  @override
  Rect getPreferredRect({
    required RenderBox parentBox,
    Offset offset = Offset.zero,
    required SliderThemeData sliderTheme,
    bool isEnabled = true,
    bool isDiscrete = false,
  }) {
    throw UnimplementedError();
  }

  @override
  void paint(
    PaintingContext context,
    Offset offset, {
    required RenderBox parentBox,
    required SliderThemeData sliderTheme,
    required Animation<double> enableAnimation,
    required Offset thumbCenter,
    bool isEnabled = true,
    bool isDiscrete = false,
    required TextDirection textDirection,
  }) {
    throw UnimplementedError();
  }
}
```

I would have expected it to modify the file to include the missing parameter:

```dart
import 'package:flutter/material.dart';

class MyTrackShape extends SliderTrackShape {
  @override
  Rect getPreferredRect({
    required RenderBox parentBox,
    Offset offset = Offset.zero,
    required SliderThemeData sliderTheme,
    bool isEnabled = true,
    bool isDiscrete = false,
  }) {
    throw UnimplementedError();
  }

  @override
  void paint(
    PaintingContext context,
    Offset offset, {
    required RenderBox parentBox,
    required SliderThemeData sliderTheme,
    required Animation<double> enableAnimation,
    required Offset thumbCenter,
	Offset? secondaryOffset,  // Expected this line to be added in this position
    bool isEnabled = true,
    bool isDiscrete = false,
    required TextDirection textDirection,
  }) {
    throw UnimplementedError();
  }
}
```

Also, the YAML analysis in VSCode seemed to think that the `argumentValue` key needed to be added, but I think that for optional parameters it should also be optional (also because it's unclear if the value should be `'null'` or `''` if the value should not have an initializer).

The documentation implies that this kind of change ought to be supported: "The index key is ... used to know where to add new parameters in overrides ...".

Dart SDK Version: 2.19.0 (build 2.19.0-147.0.dev)
OS: Debian GNU/Linux 5.17.11-1rodete2-amd64
cc @bwilkerson
