### ISSUE TITLE
[analyzer][docs] `messages.yaml`: `comment` should have same number of parameters as in `problemMessage`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49857]
As shown here:

[messages.yaml](https://github.com/dart-lang/sdk/blob/9292afa710b646cb2233524753a9153a2652a317/pkg/analyzer/messages.yaml#L8252-L8256)

```
  MISSING_DEFAULT_VALUE_FOR_PARAMETER:
    problemMessage: "The parameter '{0}' can't have a value of 'null' because of its type, but the implicit default value is 'null'."
    correctionMessage: "Try adding either an explicit non-'null' default value or the 'required' modifier."
    hasPublishedDocs: true
    comment: No parameters.
```

The `comment` shows "no parameters" although the `problemMessage` has one.

I guess there should be a test to ensure both are in sync.
