### ISSUE TITLE
dart fix 'operator ==' generated incorrect code

### ISSUE THREAD

**Issue by shirne** [dart-lang/sdk#49913]
**Describe the issue**
lints rule `always_declare_return_types` make a notice `should have a return type` on `operator ==`.
When click `quick fix` or run `dart fix --apply`，It generated incorrect codes

**To Reproduce**
```dart
class MyObject extends Object {
  MyObject(this.value);

  final int value;

  @override
  operator ==(Object other) {
    if (other is! MyObject) return false;
    return value == other.value;
  }

  @override
  int get hashCode => value.hashCode;
}
```

**Expected behavior**
code should fixed to
```dart
@override
  bool operator ==(Object other) {
    if (other is! MyObject) return false;
    return value == other.value;
  }
```
when I click `quick fix` or run `dart fix --apply`

but `quick fix` generated code
```dart
@override
  operator bool ==(Object other) {
    if (other is! MyObject) return false;
    return value == other.value;
  }
```
`dart fix --apply` generated code
```dart
@override
  operator @override
  bool ==(Object other) {
    if (other is! MyObject) return false;
    return value == other.value;
  }
```

**Additional context**
Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [版本 10.0.19044.1889], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.17)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

pubsec.yaml
```
name: dtest
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
```
