### ISSUE TITLE
`replacedBy` fix isn't migrating constructors

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#50011]
Working on https://github.com/flutter/flutter/pull/111711, I was trying to write a fix for it, but no transforms are being applied.

The original fix modified some parameters, but I found just simply trying to replace the class constructor was not working.
Simplified fix for debugging:

```yaml
- title: "Migrate to 'RenderConstraintsTransformBox'"
    date: 2021-03-24
    element:
      uris: [ 'rendering.dart' ]
      constructor: ''
      inClass: 'RenderUnconstrainedBox'
    changes:
      - kind: 'replacedBy'
        newElement:
          uris: ['rendering.dart']
          constructor: ''
          inClass: 'RenderConstraintsTransformBox'
```

Unmigrated code:
```dart
RenderUnconstrainedBox renderBox = RenderUnconstrainedBox(
    alignment: Alignment.center,
    textDirection: TextDirection.ltr,
  );
```

Expected transform:
```dart
RenderConstraintsTransformBox renderBox = RenderConstraintsTransformBox(
    alignment: Alignment.center,
    textDirection: TextDirection.ltr,
  );
```

**Comment by mraleph** [comment]
(I am not sure about correct `area-*` label for `dart fix`. Let me know if analyzer is the wrong one @srawlins)

**Comment by Piinks** [comment]
I saw an email response to this issue, but it does not appear here. It mentioned a test case that currently shows this type of fix working. I am not sure if this is an exception or edge case, but the test case above does not work. I also came across another `replacedBy` constructor not working today in https://github.com/flutter/flutter/pull/108052

Are we using it wrong? I do not see a difference in the tested rule versus the rule that is not working. 😞 

cc @bwilkerson

**Comment by bwilkerson** [comment]
I saw the response in email too. The response was from @asashour. It might have been deleted, but I don't know how to get history for the issue to confirm that. I can paste it back in if the deletion wasn't intentional.

I don't see any problem with the code above, except that as Ahmed saw in his test case, the transform is specifying a replacement for a constructor, not for the type, so I wouldn't expect the type annotation before `renderBox` to be replaced.

I'd need to do further investigating to understand more about the problem. But one question you might be able to answer: does the code simply not get transformed at all, or is it transformed but not in the way you expected?

**Comment by Piinks** [comment]
> does the code simply not get transformed at all, or is it transformed but not in the way you expected?

Thanks @bwilkerson! There is no transformation at all in the example here and in https://github.com/flutter/flutter/pull/108052

**Comment by asashour** [comment]
Sorry for the disturbance. After writing the first comment, and investigating further, there are some results which made the first comment not to the point, that's why it was deleted, to implicitly say: please ignore it.

The test case that doesn't trigger anything is far below.

However, there is some transformation done if the deprecation is not at `Old` class, but at the constructor, e.g.

```dart
class Old {
  @deprecated
  Old({String? a, String b,});
}
```

which was the result of the deleted comment.

The current test cases put the `@deprecated` at the constructor, possibly not detecting the case in question.

Having a minimal complete case is crucial (at least for me), to quickly see see how things work, and using Flutter code may impose a challenge, specially when someone is new to the area.

I would dig a little more based on my current understandings. Thanks.

```dart
  Future<void> test_constructor() async {
    setPackageContent('''
@deprecated
class Old {
  Old({String? a, String b,});
}
class New {
  New({String? a, String b,});
}
''');
    addPackageDataFile('''
version: 1
transforms:
  - title: 'Migrate constructor'
    date: 2022-05-12
    element:
      uris: ['$importUri']
      constructor: ''
      inClass: 'Old'
    changes:
      - kind: 'replacedBy'
        newElement:
          uris: ['$importUri']
          constructor: ''
          inClass: 'New'
''');
    await resolveTestCode('''
import '$importUri';

f() {
  Old abc = Old(
    a: 'a',
    b: 'b',
  );
  return abc;
}
''');
    await assertHasFix('''
import '$importUri';

f() {
  New abc = New(
    a: 'a',
    b: 'b',
  );
  return abc;
}
''', errorFilter: (error) => error.offset == 41);
  }
```

**Comment by asashour** [comment]
The reason seems to be that Flutter [disables](https://github.com/flutter/flutter/blob/463ee3d58ccf089c92e3c51d302b2796b9d43a66/analysis_options.yaml#L25) deprecation errors, and so `dart fix` doesn't find any relevant fixes for them.

For the time being, this can be handled by temporarily removing the disablement before running the `fix`. On the other hand, the data driven fix could be changed to consider all lints/errors (even if disabled).

I hope this clarifies, since potentially more issues would arise based on the that.

**Comment by Piinks** [comment]
> The reason seems to be that Flutter [disables](https://github.com/flutter/flutter/blob/463ee3d58ccf089c92e3c51d302b2796b9d43a66/analysis_options.yaml#L25) deprecation errors, and so dart fix doesn't find any relevant fixes.

@asashour this is not the case. I was not trying to fix a deprecation, as I was deleting the deprecated code when I wrote the fix. `RenderUnconstrainedBox` did not exist anymore, and dart fix still was not fixing the code.

Also, we test the fixes in an environment different from the analysis options you fixed, specifically for the reasons you mentioned:

https://github.com/flutter/flutter/blob/master/packages/flutter/test_fixes/analysis_options.yaml

**Comment by Piinks** [comment]
For reference, here is where the API was being deleted and the transformation not working: https://github.com/flutter/flutter/pull/111711

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/260761

Thanks for the explanation.

On looking on the PR, I thought that the fix was applied before the commit, so the "old" class and constructor were existing and are deprecated, and this was already supported (if the deprecation error is enabled)

The proposed CL handles the case where the "old" class is removed, and `replacedBy` to handle accordingly.

**Comment by bernaferrari** [comment]
I think I still have the same issue, I'm on:

Dart SDK version: 2.19.0-288.0.dev (dev) (Thu Oct 6 20:22:42 2022 -0700) on "macos_x64"

If I add this rule to fixes:
```dart
# Changes made in https://github.com/flutter/flutter/pull/108052
  - title: 'Replace with ShapeDecoration'
    date: 2022-10-07
    element:
      uris: [ 'painting.dart', 'rendering.dart', 'widgets.dart', 'material.dart', 'cupertino.dart' ]
      inClass: 'BoxDecoration'
      constructor: ''
    oneOf:
    - if: "shape == 'BoxShape.circle'"
      changes:
        - kind: 'replacedBy'
          newElement:
            uris: [ 'painting.dart', 'rendering.dart', 'widgets.dart', 'material.dart', 'cupertino.dart' ]
            inClass: 'ShapeDecoration'
            constructor: ''
        - kind: 'addParameter'
          index: 1
          name: 'shape'
          style: optional_named
          argumentValue:
            expression: '{% CircleBorder %}()'
            requiredIf: "shape == 'BoxShape.circle'"
            variables:
              CircleBorder:
                kind: 'import'
                uris: [ 'painting.dart', 'rendering.dart', 'widgets.dart', 'material.dart', 'cupertino.dart' ]
                name: 'CircleBorder'
        - kind: 'removeParameter'
          name: 'boxShadow'
        - kind: 'addParameter'
          index: 4
          name: 'shadows'
          style: optional_named
          argumentValue:
            expression: '{% boxShadow %}'
            requiredIf: "boxShadow != ''"
        - kind: 'removeParameter'
          name: 'shape'
        - kind: 'removeParameter'
          name: 'borderRadius'
    variables:
      shape:
        kind: 'fragment'
        value: 'arguments[shape]'
      boxShadow:
        kind: 'fragment'
        value: 'arguments[boxShadow]'
```

and test with:
```dart
import 'package:flutter/painting.dart';

void main() {
  BoxDecoration(
    shape: BoxShape.circle,
    color: Color(0xFFFF0000),
    boxShadow: [],
  );
}
```

the output is not `ShapeDecoration`. The output is the same.

**Comment by Piinks** [comment]
@bernaferrari are you applying this rule in a branch where `shape` is deprecated?

**Comment by bwilkerson** [comment]
It's possible that the fix has not made it into the latest dev branch and that you might need to use a newer version of the Dart SDK. I'm not sure how to verify that.

It's also possible that the fix missed a case.

**Comment by bernaferrari** [comment]
I wish there were a simple way to test these fixes, maybe a playground of some sort. I can't even share with you "everything" (like the Container class) because each thing is in a different place. The person that's going to test is going to spend more time than needed.

I think it is, because the commit was from 2 weeks ago and the dev commit is from yesterday, so I guess it has had enough time to be there. But I don't know.

**Comment by asashour** [comment]
The [commit] seems to be available since [2.19.0-262.0.dev](https://github.com/dart-lang/sdk/releases/tag/2.19.0-262.0.dev) (as shown in its tags).

The change was handling the case where the the `old` (`BoxDecoration` in this case) doesn't exist at all.

Having the BoxDecoration in the code (deprecated or not) is outside of the fix scope.

To find a way forward, a minimal test case would be really helpful, preferably outside Flutter code base (as it is big and is continuously changing).

**Comment by asashour** [comment]
To make a minimal case:

1. Clone/fork flutter (`packages/flutter` is used below)
2. In Flutter, replace `lib/fix_data.yaml` with
<details>
<summary>fix_data.yaml</summary>

```yaml
version: 1
transforms:
  - title: 'Replace with C_new'
    date: 2022-10-07
    element:
      uris: [ 'abc.dart' ]
      inClass: 'C_old'
      constructor: ''
    changes:
      - kind: 'replacedBy'
        newElement:
          uris: [ 'abc.dart' ]
          inClass: 'C_new'
          constructor: ''
```
</details>

2. In Flutter lib, have `abc.dart` with:
```dart
class C_old {
  @deprecated
  C_old();
}

class C_new {
  C_new();
}
```

4. In another project, where it uses this cloned Flutter: 
```dart
import 'package:flutter/abc.dart';

void f() {
  C_old();
}

```
5. In your IDE (IntelliJ with me), right click on the `C_old` in the other project, and you will have `Replace with C_new` where it is changed.

From this point, add to the `fix_data.yaml`, step by step, to reach your desired behavior, and when the minimal scenario it doesn't work, please post it here.

**Comment by asashour** [comment]
@bernaferrari your case works. Make sure you don't have the test class in Flutter, because it [ignores](https://github.com/flutter/flutter/blob/23f22cb8535c0e8746badef943c8c178d30b5f07/analysis_options.yaml#L25) `@deprecation`, which is required to produce an `error`, which is required to trigger the data-driven fixes.

Steps:
1. Using Flutter [master](https://github.com/flutter/flutter/commit/ae98ec53ac9b13faaf4c2d4be3b1320f9067feb0)
2. Deprecated `BoxDecoration` class
3. Replace `packages/flutter/lib/fix_data.yaml` with:
<details>

<summary>fix_data.yaml</summary>

```yaml
version: 1
transforms:
  - title: 'Replace with ShapeDecoration'
    date: 2022-10-07
    element:
      uris: [ 'painting.dart', 'rendering.dart', 'widgets.dart', 'material.dart', 'cupertino.dart' ]
      inClass: 'BoxDecoration'
      constructor: ''
    oneOf:
      - if: "shape == 'BoxShape.circle'"
        changes:
          - kind: 'replacedBy'
            newElement:
              uris: [ 'painting.dart', 'rendering.dart', 'widgets.dart', 'material.dart', 'cupertino.dart' ]
              inClass: 'ShapeDecoration'
              constructor: ''
          - kind: 'addParameter'
            index: 1
            name: 'shape'
            style: optional_named
            argumentValue:
              expression: '{% CircleBorder %}()'
              requiredIf: "shape == 'BoxShape.circle'"
              variables:
                CircleBorder:
                  kind: 'import'
                  uris: [ 'painting.dart', 'rendering.dart', 'widgets.dart', 'material.dart', 'cupertino.dart' ]
                  name: 'CircleBorder'
          - kind: 'removeParameter'
            name: 'boxShadow'
          - kind: 'addParameter'
            index: 4
            name: 'shadows'
            style: optional_named
            argumentValue:
              expression: '{% boxShadow %}'
              requiredIf: "boxShadow != ''"
          - kind: 'removeParameter'
            name: 'shape'
          - kind: 'removeParameter'
            name: 'borderRadius'
    variables:
      shape:
        kind: 'fragment'
        value: 'arguments[shape]'
      boxShadow:
        kind: 'fragment'
        value: 'arguments[boxShadow]'
```
</details>

4. With the below on an **external** project:

```dart
import 'package:flutter/painting.dart';

void main() {
  BoxDecoration(
    shape: BoxShape.circle,
    color: Color(0xFFFF0000),
    boxShadow: [],
  );
}
```

It is converted to:

```dart
  ShapeDecoration(
    shape: CircleBorder(),
    color: Color(0xFFFF0000), shadows: [],
  );
```

Just check that you have a deprecation warning, something like the below (`const` was added to not have many warnings, but it doesn't have an effect):

![image](https://user-images.githubusercontent.com/2410127/194696123-d5a22af5-aeec-417c-ab46-e3b84e84273a.png)
