### ISSUE TITLE
Diagnostic message "missing_return" does not appear for the example code

### ISSUE THREAD

**Issue by chykon** [dart-lang/sdk#50147]
The diagnostic message "missing_return" does not appear for the [example code](https://dart.dev/tools/diagnostic-messages#missing_return). It shows "body_might_complete_normally" instead.

Code to reproduce:

```dart
// main.dart
int f(int x) {
  if (x < 0) {
    return 0;
  }
}

void main() {
  print(f(1));
}
```

```yaml
# analysis_options.yaml
analyzer:
  errors:
    missing_return: error
    body_might_complete_normally: ignore
```

About Dart:

```text
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"
```
