### ISSUE TITLE
Add analyzer support for pubspec screenshots

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#50179]
Pubspecs now support a `screenshots` field that we should support with analyzer.

For example:

```yaml
screenshots:
 - description: 'Examples of the container transform pattern.'
   path: example/screenshots/container_transform_lineup.webp
 - description: 'Examples of the fade pattern.'
   path: example/screenshots/fade_lineup.webp
```

Specifically,

- [ ] code completion (`screenshot`,`description` and `path`)
- [ ] path validation (`PubspecWarningCode.PATH_DOES_NOT_EXIST`)
- [ ] ... ?

/fyi @szakarias @jonasfj @sigurdm
