### ISSUE TITLE
[analyzder] data-driven fix for `replacedBy` for constructor doesn't consider the `uris`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50363]
As discovered in #50358, it seems matching the constructor doesn't consider the `uris`, which is incorrect.

In other words: the `uris` below works as a wildcard, without matching its value.

```yaml
  - title: "Remove 'brightness'"
    date: 2020-12-10
    element:
      uris: [ 'cupertino.dart' ]
      constructor: ''
      inClass: 'CupertinoTextThemeData'
    changes:
      - kind: 'removeParameter'
        name: 'brightness'
```

The issue was introduced in https://github.com/dart-lang/sdk/commit/8eb8e61e1ee79910322210f8eabb3b67a443855a
