### ISSUE TITLE
Problem trying to run web compilers (ddc) on some code that works in flutter.

### ISSUE THREAD

**Issue by Pacane** [dart-lang/sdk#50377]
I am getting an error when running `dart run build_runner build` with `build_web_compilers` on.

We have some code that we want to run tests against DDC and dart2js. 

The same code runs perfectly against the dartvm.

We're using the following `build.yaml` file.

```
targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: true
        generate_for:
          exclude:
            - test/**
          include:
            - lib/**
      build_web_compilers|entrypoint:
        generate_for:
          - test/**_test.dart
          - web/**.dart
        options:
          compiler: dartdevc
        enabled: true
```

### dart version
``````
λ ~/job/dart/* dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +02
``````

### pubspec used

```
name: braver_patient
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.1.2
  collection: ^1.16.0
  uuid: ^3.0.2
  tuple: ^2.0.0
  pointycastle: ^3.5.0

  ### bunch of internal packages
  
dev_dependencies:
  build_runner: ^2.3.0
  built_value_generator: ^8.1.1
  build_test: ^2.1.5
  build_web_compilers: ^3.2.5
  drift_dev: ^1.6.0
  mockito: ^5.3.2
  faker: ^2.0.0
  freezed: ^2.2.0
  test: ^1.21.4
```

I needed to truncate the error message because `dart run build_runner build` never finishes, but here's a sample of what it looks like.

https://gist.github.com/matehat/5468de837d5ac9ced826a2437cfe7c24

In the sample you can see there's a crash in a file called ``...braver_patient/delegates.dart`` Which is just a barrel export file. Here's a sample of what it looks like.`

```
export 'src/delegates/patient_query_delegate.dart';
```

And then there are a bunch of errors for files that depend on the broken file I believe.

I'm not sure how to reproduce this bug with a minimal project, but I can take pointers to try to reproduce it in a more localized way.
