### ISSUE TITLE
`replacedBy` won't replace getter with method

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#50699]
Working on a change in flutter/flutter, I deprecated a getter in favor of a new method.

I've tried this a couple of ways now, but the transform has never worked:

I deprecated

```dart
@Deprecated('Use tabHasTextAndIconFor...')
bool get tabHasTextAndIcon => ...

/// Replacement
bool tabHasTextAndIconFor(BuildContext context) {...}
```

with this transform

```yaml
# Changes made in TBD
  - title: "Migrate to 'tabHasTextAndIconFor'"
    date: 2022-12-12
    element:
      uris: ['material.dart']
      getter: 'tabHasTextAndIcon'
      inClass: 'TabBar'
    changes:
    - kind: 'replacedBy'
      newElement:
        uris: ['material.dart']
        method: 'tabHasTextAndIconFor'
        inClass: 'TabBar'
    - kind: 'addParameter'
      index: 0
        name: 'context'
        style: required_positional
        argumentValue:
          expression: 'context'
          requiredIf: 'true'
```

And I guess I expected this change:

```dart
// Before
tabBar.tabHasTextAndIcon;

// After
tabBar.tabHasTextAndIconFor(context);
```

But nothing happened.

Is this possible? Or is there another way?

Related: https://github.com/dart-lang/sdk/issues/50698
