### ISSUE TITLE
dart migrate's adding dependencies works different with flutter/dart add

### ISSUE THREAD

**Issue by EarlGreytea16** [dart-lang/sdk#50795]
My pubspec.yml looks like this:
```yml
version: 6.5.0+1400

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    shared_preferences: ^2.0.15 
    provider: ^6.0.5
    device_info: ^2.0.3
    path_provider: ^2.0.11
    package_info: ^2.0.2
    external_path: ^1.0.3
    permission_handler: ^10.2.0 
    file_picker: ^5.2.4
    path: ^1.8.2
```
This yml uses 4 space as a saparator.
```yml
    path: ^1.8.2
1234path
```

while using ```flutter add``` it works without problem:
```
PS C:\Users\Administrator\Desktop\SongTube-App\SongTube-App-development> C:\flutter\bin\flutter.bat pub add line_icons  Resolving dependencies...
  collection 1.16.0 (1.17.0 available)
Warning: You are using these overridden dependencies:
! flutter_math_fork 0.5.0 (0.6.3+1 available)
! html 0.15.1
! platform 3.1.0
Downloading line_icons 2.0.1...
Changed 1 dependency!
The plugin `flutter_screen` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2
embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.
```
```dart add``` also works without problem.
```
PS C:\Users\Administrator\Desktop\SongTube-App\SongTube-App-development> C:\flutter\bin\flutter.bat pub add line_icons  Resolving dependencies...
  collection 1.16.0 (1.17.0 available)
  xml 5.4.1 (6.2.2 available)
Warning: You are using these overridden dependencies:
! flutter_math_fork 0.5.0 (0.6.3+1 available)
! html 0.15.1
! platform 3.1.0
Downloading line_icons 2.0.1...
Changed 1 dependency!
```

This changes the code like this:
```yml
    flutter_markdown: ^0.6.13
    md2_tab_indicator:
        git:
            url: https://github.com/abdelrahmanelmarakby/md2_tab_indicator
            ref: patch-1
    line_icons: ^2.0.1
```
but migrating dart always add package as two spaces like this:
```yml
    flutter_markdown: ^0.6.13
    md2_tab_indicator:
        git:
            url: https://github.com/abdelrahmanelmarakby/md2_tab_indicator
            ref: patch-1
  collection: ^1.15.0-nullsafety.4

dependency_overrides:
```
This will give on dart/flutter pub get
```
PS C:\Users\Administrator\Desktop\SongTube-App\SongTube-App-development> C:\flutter\bin\flutter.bat pub get
Error detected in pubspec.yaml:
Error on line 140, column 3: Expected a key while parsing a block mapping.
    ╷
140 │   collection: ^1.15.0-nullsafety.4
    │   ^
    ╵
Please correct the pubspec.yaml file at
C:\Users\Administrator\Desktop\SongTube-App\SongTube-App-development\pubspec.yaml
```
