### ISSUE TITLE
dart 2.19 beta.4 reports incorrect version range

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#51020]
I have the following pubspec.yaml
```
name: library
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.19.0-beta.1 <3.0.0'
dependencies: 
  dcli: 1.36.0
dev_dependencies: 
  lint_hard: ^1.0.0

```
Note the max sdk is < 3.0.0

When I run dart pub get

```
dart pub get
Resolving dependencies... 
The current Dart SDK version is 2.19.0-444.4.beta.

Because library requires SDK version >=2.19.0-beta.1 <4.0.0, version solving failed.

```

Note the upper version is displayed as < 4.0.0 rather than the expected < 3.0.0

FYI:
```
 dart --version
Dart SDK version: 2.19.0-444.4.beta (beta) (Tue Jan 10 10:24:44 2023 +0000) on "linux_x64"
```
