### ISSUE TITLE
dart fix not applying for static method rename, parameter changes

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#51198]
Noticed in https://github.com/flutter/flutter/pull/119187

With this transform rule:

```yaml
- title: "Migrate to 'routeInformationUpdated'"
    date: 2023-01-30
    element:
      uris: [ 'services.dart' ]
      method: 'routeUpdated'
      inClass: 'SystemNavigator'
    changes:
      - kind: 'removeParameter'
        name: 'previousRouteName'
      - kind: 'renameParameter'
        oldName: 'routeName'
        newName: 'location'
      - kind: 'rename'
        newName: 'routeInformationUpdated'
```

The expectation is that this will be the result:

```dart
/// Before, deprecated method
SystemNavigator.routeUpdated(routeName: 'foo', previousRouteName: 'bar');

/// After
SystemNavigator.routeInformationUpdated(location: 'foo');
```

Instead the result is only a partial transformation:
```dart
/// Actual result
SystemNavigator.routeInformationUpdated(routeName: 'foo');
```
