### ISSUE TITLE
[analyzer] Non-exhaustive switch error even though all cases are in place

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/sdk#51805]
The code compiles just fine with, however, the analyzer throws an error:

```
The type 'A' is not exhaustively matched by the switch cases.
Try adding a default case or cases that match A.
```

even though all cases a clearly there

```dart
sealed class A {}

class B implements A {}
class C implements A {}

void main() {
  final A a = B();

  final msg = switch (a) {
    B _ => 'got B',
    C _ => 'got C'
  };
  
  print(msg);
}
```

#### Dart version

Dart SDK version: 3.0.0-233.0.dev (dev) (Mon Feb 13 09:47:39 2023 -0800) on "macos_arm64"

#### analysis_options.yaml

```yaml
include: package:lints/recommended.yaml

analyzer:
  enable-experiment:
    - sealed-class
    - patterns
```
