### ISSUE TITLE
Add support for context links to `dart fix`

### ISSUE THREAD

**Issue by pdblasi-google** [dart-lang/sdk#51987]
There are plenty of reasons that a fix isn't supported by `dart fix`:

* The fix is too complex
* The original API has to many usage variations
* `dart fix` doesn't support a fix yet

In these cases, and possibly as an addition to automatible cases, it'd be nice to be able to provide a context link that could drive users to a migration doc.

## Proposal

Add a new `context` field to the `transform` object. This field will accept a list of `contextLink` objects consisting of a `title` and `uri`. The titles of the links would be displayed in the context menu. They would show as an external link (with the appropriate icon and semantics) and clicking on them would open the link in a browser.

When fixes are applied through the terminal, either nothing would happen, or fixes with context would have the location of the error and the `contextLink` printed to `stdout`.

To support fixes that we can only provide context for, the requirements of `transform` would expand to allow:
* `changes`
* `oneOf`
* `context`
* `changes` and `context`, or 
* `oneOf` and `context`

#### Adding context to an automated fix
```yaml
version: 1
transforms:
  - title: 'Migrate to collate'
    date: 2023-03-29
    element:
      uris: [ 'flutter_test.dart' ]
      method: 'display'
      inClass: 'AnimationSheetBuilder'
    context:
      - title: 'Migration guide'
        uri: 'https://docs.flutter.dev/release/breaking-changes/animation-sheet-builder-display'
      - title: 'Deprecation PR'
        uri: 'https://github.com/flutter/flutter/pull/83337'
    changes:
      - kind: 'rename'
        newName: 'collate'
      - kind: 'removeParameter'
        name: 'key'
      - kind: 'addParameter'
        index: 0
        name: 'cellsPerRow'
        style: 'required_positional'
        argumentValue:
          expression: '1'
```

##### Context Menu

![Screenshot 2023-04-07 at 2 07 14 PM](https://user-images.githubusercontent.com/109253501/230673361-be6a7cdd-e6f9-4e3b-b113-cc795820ebf8.png)

#### Adding context to a un-automated fix

```yaml
version: 1
transforms:
  - title: 'Remove sheetSize'
    date: 2023-03-29
    element:
      uris: [ 'flutter_test.dart' ]
      method: 'sheetSize'
      inClass: 'AnimationSheetBuilder'
    context:
      - title: 'Migration guide'
        uri: 'https://docs.flutter.dev/release/breaking-changes/animation-sheet-builder-display'
      - title: 'Deprecation PR'
        uri: 'https://github.com/flutter/flutter/pull/83337'
```

##### Context Menu

![Screenshot 2023-04-07 at 2 20 19 PM](https://user-images.githubusercontent.com/109253501/230675617-8f473a81-e48d-4796-a545-6af9a5b10a81.png)
