### ISSUE TITLE
`dart fix` command should output yaml issues if they exist

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#52108]
I heard from a contributor today that they were writing a fix rule and the ran

- `dart fix --compare-to-golden`

to test the fix rule they had written.
The tool failed all the tests with the output: `original code was unchanged`

The issue was that there was a formatting error in the .yaml file, but the output from the tool was no help in pointing this out.

Can the tool give feedback in this case when there is an issue in the .yaml file?

**Comment by Piinks** [comment]
cc @bwilkerson and @keertip this one popped up today that might be an easy improvement.

**Comment by bwilkerson** [comment]
We do have some analysis support for the data file (we produce diagnostics). I thought it was wired up so that those diagnostics would be displayed in the IDE. It's possible that that's not happening. It's also possible that we aren't catching enough cases and need to enhance the error checking in `TransformSetParser`.

Could you get a reproduction case from them, or a description of the kind of formatting error that caused the problem?

**Comment by Piinks** [comment]
Sure! They do appear in the IDE's dart analysis pane, but are less apparent inline in the IDE. @loic-sharma may be able to provide an example of the formatting issue they were seeing.

**Comment by loic-sharma** [comment]
Apologies, I'm not able to reproduce the issue any more and I didn't save the code that caused the issue.

From my understanding, these diagnostics are only produced on IntelliJ - is that correct? Would it be possible to also output these diagnostics from `dart fix` itself and in VS Code?

**Comment by bwilkerson** [comment]
I'm not sure why they're not visible in VS Code; I expected them to be. @DanTup 

Did you mean `dart analyze` instead of `dart fix`?

**Comment by loic-sharma** [comment]
I'm following [Flutter's data-driven fixes](https://github.com/flutter/flutter/wiki/Data-driven-Fixes#testing) guide. I would like to create a fix that migrates this code:

```
Clipboard.setData(ClipboardData());
Clipboard.setData(ClipboardData(text: null));
```

Into:

```
Clipboard.setData(ClipboardData(text: ''));
Clipboard.setData(ClipboardData(text: ''));
```

My data-driven fix looks like this:

```
  # Changes made in https://github.com/flutter/flutter/pull/122446
  - title: "Migrate to empty 'text' string"
    date: 2023-04-19
    element:
      uris: [ 'services.dart' ]
      constructor: ''
      inClass: 'ClipboardData'
    oneOf:
      - if: "text == ''"
        changes:
          - kind: 'addParameter'
            index: 0
            name: 'text'
            style: required_named
            argumentValue:
              expression: "''"
              requiredIf: "text == ''"
```

However, my data-driven fix does nothing and I'm unable to figure out why. VS Code doesn't output any warnings/errors for the fix's YAML file. Furthermore, running `dart fix --compare-to-golden` in Flutter's `packages/flutter/test_fixes/` directory does not produce any warnings/errors and does not migrate the code above.
