### ISSUE TITLE
dart fix `required_named` is not working

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#52113]
@loic-sharma was sharing with me some strange behavior from dart fix.

A change was made where

```dart
ClipboardData({ String? this.text });
```

became 

```dart
ClipboardData({ required String text });
```

The planned fix was to add the `text` parameter where users may not have already been using it.

```dart
// Before
ClipboardData();

// After
ClipBoardData(text: '');
```

This was the defined rule:

```yaml
# Changes made in https://github.com/flutter/flutter/pull/122446
  - title: "Replace null 'text' with empty string"
    date: 2023-04-19
    element:
      uris: [ 'services.dart' ]
      constructor: ''
      inClass: 'ClipboardData'
    oneOf:
      - if: "text == ''"
        changes:
          - kind: 'addParameter'
            index: 0
            name: 'text'
            style: required_named
            argumentValue:
              expression: "''"
              requiredIf: "text == ''"
```

But no transformation is applied.
