### ISSUE TITLE
analyzer support for pub "topics"

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#52256]
Pubspecs will soon support "topics". For example:

```yaml
name: retry
version: 3.1.1
description: |
  Utility for wrapping an asynchronous function in automatic retry logic with
  exponential back-off, useful when making requests over network.
homepage: https://github.com/google/dart-neats/tree/master/retry
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:retry
dev_dependencies:
  test: ^1.16.0-nullsafety.13
  lints: ^1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
topics:
 - network
 - http
```

Minimally we should add "topics" to code completions in pubspecs.

@szakarias, @sigurdm, @jonasfj: any validation we should consider?
