### ISSUE TITLE
Exclude for folder does not work

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#52283]
I tried to exclude lint for a folder but it did not take effect:

```
include: ../../../../analysis_options.yaml

linter:
  rules:
    avoid_web_libraries_in_flutter: false
```

Context: https://github.com/flutter/devtools/pull/5440#discussion_r1175493116
