### ISSUE TITLE
[Dart Fix] dart fix `addParameter` and `removeParameter` changes don't apply to method overrides

### ISSUE THREAD

**Issue by LongCatIsLooong** [dart-lang/sdk#52646]
I have not tested other change kinds, but the following transform does not transform method overrides:

transform:
```yaml

  - title: "Use 'textScaler' instead"
    date: 2023-06-08
    element:
      uris: ['widgets.dart']
      method: 'build'
      inClass: 'WidgetSpan'
    changes:
      - kind: 'addParameter'
        index: 1
        name: 'textScaler'
        style: optional_named
        defaultValue: 'TextScaler.noScaling'
      - kind: 'removeParameter'
        name: 'textScaleFactor'

```

original code
```dart
import 'package:flutter/widgets.dart';

void main() {
  WidgetSpan(child: widget)
    ..build(builder, textScaleFactor: 1234);
}

class MyWidgetSpan extends WidgetSpan {
  const MyWidgetSpan({required super.child});
  @override
  void build(ui.ParagraphBuilder builder, {
    double textScaleFactor = 1.0,
    List<PlaceholderDimensions>? dimensions,
  }) {
    super.build(builder, textScaleFactor: textScaleFactor, dimensions: dimensions);
  }
}
```
Expected output:
```dart
import 'package:flutter/widgets.dart';

void main() {
  WidgetSpan(child: widget)
    ..build(builder);
}

class MyWidgetSpan extends WidgetSpan {
  const MyWidgetSpan({required super.child});
  @override
  void build(ui.ParagraphBuilder builder, {
    TextScaler textScaler = TextScaler.noScaling,
    List<PlaceholderDimensions>? dimensions,
  }) {
    // Not sure what should happen here.
    super.build(builder, dimensions: dimensions);
  }
}
```

Actual output:
```dart
import 'package:flutter/widgets.dart';

void main() {
  WidgetSpan(child: widget)
    ..build(builder);
}

class MyWidgetSpan extends WidgetSpan {
  const MyWidgetSpan({required super.child});
  @override
  void build(ui.ParagraphBuilder builder, {
    double textScaleFactor = 1.0,
    List<PlaceholderDimensions>? dimensions,
  }) {
    super.build(builder, textScaleFactor: textScaleFactor, dimensions: dimensions);
  }
}
```
