### ISSUE TITLE
`dart pub add` fails when using `dependency_overrides.yaml` with empty version constraint 

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/sdk#52895]
Running `dart pub add <dependency>` e.g `dart pub add collection` fails with given

`pubspec.yaml`

```yaml
name: pub_add_bug
description: Pub Add Bug
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  local_package:
```

`pubspec_overrides.yaml`

```yaml
dependency_overrides:
  local_package:
    path: local_package
```

A minimal reproducible sample an be found [here](https://github.com/jtdLab/pubAddBug).

Hint:

Adding the dependency manually and  running `dart pub get` works.
