### ISSUE TITLE
[Dart fix] Support top-level variable `replacedBy` field in class

### ISSUE THREAD

**Issue by guidezpl** [dart-lang/sdk#52902]
Support converting a top-level variable such as `standardEasing`.

where the class looks like
```
class Easing {
  static const Curve legacy = ...;
}
```
this
```
const Curve curve = standardEasing;
```

would become 

```
const Curve curve = Easing.legacy;
```

with the following fix

```
  - title: "Migrate to 'Easing.legacy'"
    date: 2023-07-04
    element:
      uris: [ 'material.dart' ]
      variable: 'standardEasing'
    changes:
      - kind: 'replacedBy'
        newElement:
          uris: [ 'material.dart' ]
          field: legacy
          inClass: Easing
```
