### ISSUE TITLE
`dart fix` bug with static fields in a Class

### ISSUE THREAD

**Issue by CoderDake** [dart-lang/sdk#53101]
# Issue
While trying to create a dart fix for https://github.com/flutter/flutter/pull/131634 I ran into issues. The situation below doesn't make any modification when running `dart fix --compare-to-golden`

# Information 
## Rule
```
  - title: "Migrate to 'debugShowWidgetInspectorOverrideNotifier'"
    date: 2023-03-13
    element:
      uris: [ 'widgets.dart', 'material.dart', 'cupertino.dart' ]
      field: 'debugShowWidgetInspectorOverride'
      inClass: 'WidgetsApp'
    changes:
      - kind: 'rename'
        newName: debugShowWidgetInspectorOverrideNotifier
```
## Input
```
import 'package:flutter/widgets.dart';

void main() {
  WidgetsApp.debugShowWidgetInspectorOverride = true;
}
```
## Expected
```
import 'package:flutter/widgets.dart';

void main() {
  WidgetsApp.debugShowWidgetInspectorOverrideNotifier = true;
}

```

**Comment by CoderDake** [comment]
I also tried doing `replaceBy` without any luck:
```
 - title: "Migrate to 'debugShowWidgetInspectorOverrideNotifier'"
    date: 2023-03-13
    element:
      uris: [ 'widgets.dart', 'material.dart', 'cupertino.dart' ]
      field: 'debugShowWidgetInspectorOverride'
      inClass: 'WidgetsApp'
    changes:
      - kind: 'replacedBy'
        newElement:
          uris: [ 'widgets.dart', 'material.dart', 'cupertino.dart' ]
          field: 'debugShowWidgetInspectorOverrideNotifier.value'
          inClass: 'WidgetsApp'
```

**Comment by srawlins** [comment]
CC @keertip

**Comment by keertip** [comment]
Taking a look

**Comment by keertip** [comment]
@CoderDake , try this transform.

```
version: 1
transforms:
  - title: "Migrate to 'debugShowWidgetInspectorOverrideNotifier'"
    date: 2023-03-13
    element:
      uris: [ 'widgets.dart', 'material.dart', 'cupertino.dart' ]
      field: 'debugShowWidgetInspectorOverride'
      inClass: 'WidgetsApp'
      static: true
    changes:
      - kind: 'replacedBy'
        newElement: 
          uris:[ 'widgets.dart', 'material.dart', 'cupertino.dart' ]
          field: 'debugShowWidgetInspectorOverrideNotifier.value'
          inClass: 'WidgetsApp'   
          static: true 

```
