### ISSUE TITLE
[analyzer] Break-up sections of diagnostic documentation

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#53176]
### Background

Currently in the [analyzer's `messages.yaml`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/messages.yaml) and the [CFE's `messages.yaml`](https://github.com/dart-lang/sdk/blob/main/pkg/front_end/messages.yaml), the documentation used to generate https://dart.dev/diagnostics is grouped into one field, with the headers (description, example, and common fixes) manually specified. This makes it harder for consumers of this file to configure the generation, since the headers are already specified at specific level. Beyond that, some of the analyzer's test tooling splits up the sections as well. 

<details>
  <summary>Currently it looks roughly like this</summary>

  ```yaml
DIAGNOSTIC_EXAMPLE:
    ...
    hasPublishedDocs: true
    documentation: |-
      #### Description

      Description goes here....

      #### Examples

      Example 1 goes here...

      Example 2 goes here...

      #### Common fixes

      Common fix 1 goes here...

      Common fix 2 goes here....
      
```
</details>

### Proposal

To make it easier for tools/generators to choose the output format and tests to look at individual sections:

- Split the three documentation categories into their own key-value pairs under `documentation` (or top-level)
- To solve the lack of "Example" vs "Examples" with this change, we could either have two separate pairs or instead accept a list of examples.
- Move generation of the headers and combination of examples/fixes to the generator

I'm not 100% sure the list for examples and fixes makes sense or is worth it, so perhaps you have some thoughts.

<details>
  <summary>Depending on what direction seems best, it could look something like this:</summary>

  ```yaml
DIAGNOSTIC_EXAMPLE:
    ...
    hasPublishedDocs: true
    documentation:
      description: |-
        Description goes here....
      examples:
        - |-
          Example 1 goes here...
          Example 1 continues here...
        - |-
          Example 2 goes here...
          Example 2 continues here...
      fixes:
        - |-
          Fix 1 goes here...
        - |-
          Fix 2 goes here...
```
</details>

**Comment by bwilkerson** [comment]
The other aspect of this, IIRC, was a thought that we might want more than just the three existing sections. For example, we might want `justification` or `seeAlso` sections for the proposed pages that help users decide which lints they want to enable. There was even a mention (though not necessarily a plan) to allow the sections to be mixed and matched to some extent, such as by including the `seeAlso` text in both locations.

What I don't know is which pieces really make sense to mix and match. I'm absolutely in favor of avoiding duplication. But if being able to more easily change the heading levels in generated output were the only goal then I'd be skeptical that it was worth the effort.

> Split the three documentation categories into their own key-value pairs under `documentation` (or top-level)

If we're going to split them, it's definitely better to have them under `documentation`; it removes the possibility of conflicts between doc needs and other needs.

**Comment by parlough** [comment]
> If we're going to split them, it's definitely better to have them under documentation; it removes the possibility of conflicts between doc needs and other needs.

That sounds good to me 👍 

> The other aspect of this, IIRC, was a thought that we might want more than just the three existing sections. For example, we might want justification or seeAlso sections for the proposed pages that help users decide which lints they want to enable.

Sorry, you're right. I was focusing on the existing diagnostic structure here, since we haven't exactly determined the "justification" part of linter rules, but especially for the linter rules, there will definitely be other information we'll want to include within the `documentation` map.

You mention `seeAlso`, and I think that would be useful for lints like you mentioned, but potentially diagnostics as well, such as pointing to related docs or even videos describing how to address commonly hit diagnostics.

> What I don't know is which pieces really make sense to mix and match.

I think at this point, it's probably fine not to worry about what exactly will be mixed and matched, and focus on being consistent with the current diagnostics while we are still migrating since that is the primary benefit of this work. Splitting up the categories now will allow us to use those entries for the justification docs if/when it makes sense relatively easily.

----

As a note, one thing I did not address in this issue since it's a bit unrelated, but may reside in the linter equivalent file or sibling file(s), is extra information such as version support information and quick fix status.

**Comment by parlough** [comment]
As for modifying the existing messages and the generator, I'd be happy to do that work once we determine a structure we're happy with. Do you know if there are any other consumers of the `documentation` part of these files? If not, it's pretty low cost to adjust as needed.

**Comment by bwilkerson** [comment]
> ... since we haven't exactly determined the "justification" part of linter rules ...

It might be worth thinking about it a bit before we choose an initial split. For example, would we want to use the same examples in both places? The current lint docs include both bad and good examples, but the diagnostic messages page format only has the bad. So do we need something like

```
documentation:
  description:
  examples:
  commonFixes:
  justification:
  goodExamples:
  badExamples:
```

Or would `badExamples` be sharable between the two?

Maybe an incremental approach is fine and I'm just overthinking this, but that _is_ kind of what I get paid to do. :-)

> You mention `seeAlso`, and I think that would be useful for lints like you mentioned, but potentially diagnostics as well ...

(Minor nit: lints are diagnostics too. :-) But yes, that seems like it might be a sharable piece, unless the links are specific to the user journey that brings users to that page.

> Do you know if there are any other consumers of the `documentation` part of these files?

As far as I know, there aren't any clients outside of the analyzer (though I believe the "parsing" code is shared with the front end).

> If not, it's pretty low cost to adjust as needed.

It will become higher cost if we move the generator out of the SDK repo because it's always harder when there are multiple repos involved.
