### ISSUE TITLE
Implement extending patches for a library in libraries.yaml

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#53205]
Currently in libraries.yaml if I define a set of patches for a library and then include the target in another target, the including target cannot extend the patch files. Adding the same library again in the including target overrides the patch files. Example from current `main` branch:

```yaml
wasm_common:
  libraries:
    core:
      uri: core/core.dart
      patches:
        - _internal/wasm/lib/boxed_double.dart
        - _internal/wasm/lib/boxed_int.dart

wasm_base:
  include:
    - target: "wasm_common"
  libraries: ...                 # Does not override core

wasm:
  include:
    - target: "wasm_base"
  libraries:
    core:
      uri: core/core.dart
      patches: ...               # This list overrides `wasm_common` patches for `core`.
                                 # We have to copy/paste patches in `wasm_common` to extend it.
```

As far as I know the intended behavior is that the included library patches should be extended.

cc @johnniwinther
