### ISSUE TITLE
[Extension type] disallow `@override`s on extension type members

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#53240]
Extension type members can't override, so an `@override` annotation is always invalid.

Minimally we could produce an `INVALID_ANNOTATION_TARGET` diagnostic.  Alternatively we could create a new diagnostic with more specific documentation.

See also: #53121

**Comment by pq** [comment]
Quick stab at minimal docs for a new diagnostic:

```
  INVALID_EXTENSION_TYPE_MEMBER_OVERRIDE:
    problemMessage: Extension type members don't override superinterface members.
    correctionMessage: Try removing the annotation or replacing it with a redeclare annotation.
    comment: No parameters.
```

A good document to link to would be great here. The nuances are slippery!

/fyi @bwilkerson @MaryaBelanger
