### ISSUE TITLE
Ffigen doesn't generate typedefs compatible with NativeCallable's APIs 

### ISSUE THREAD

**Issue by Piero512** [dart-lang/sdk#53414]
Hello!

Today I was trying out the new [NativeCallable](https://api.dart.dev/stable/3.1.0/dart-ffi/NativeCallable-class.html) APIs and stumbled upon on a kinda annoying issue.

NativeCallable T generic parameter has this problem with ffigen that it requires specifying a function that only uses dart:ffi types, but there isn't currently a way to get one of these, since the generated typedefs usually come from pointer functions.

I think the NativeCallable API should not need to be changed, but say, a static function that removes the pointer and nativefunction from the signature would be useful? Although I do believe that the API should have bound T type to extend [NativeFunction](https://api.dart.dev/stable/3.1.0/dart-ffi/NativeFunction-class.html). 

I haven't checked if ffigen's config section functions -> expose-typedefs would generate the required callbacks, but if it does, it should be documented in the NativeCallable class too.

**Comment by Piero512** [comment]
Hello!

So I checked ffigen's config functions -> expose-typedefs summary and it still would not generated the required typedefs

The usecase I'm currently using to test this is using the [whisper.h](https://github.com/ggerganov/whisper.cpp/blob/master/whisper.h) file with the following ffigen.yaml

```yaml
output: 'lib/src/whisper_bindings.dart'
headers:
  entry-points:
    - 'whisper.h'
  include-directives:
    - '**whisper.h'
name: 'WhisperBindings'
structs:
  dependency-only: opaque
functions:
  include:
    - '.*'
  symbol-address:
    include:
      - '.*'
  expose-typedefs:
    include:
      - 'whisper_.*_callback'
description: 'Bindings to OpenAI Whisper model in cpp' 
comments:
  style: any
  length: full
```
I would think that maybe a similar option but in the typedefs section of the config would probably work for this issue.
