### ISSUE TITLE
[Analyzer] `textDocument/publishDiagnostics` doesn't output LSP diagnostics after saving a file

### ISSUE THREAD

**Issue by powpingdone** [dart-lang/sdk#53475]
After saving a file (modified or unmodified, doesn't matter), the language server will very likely output a blank diagnostic even if the file has errors or warnings:

```jsonrpc
{
  jsonrpc = "2.0",
  method = "textDocument/publishDiagnostics",
  params = {
    diagnostics = {},
    uri = "file:///run/host/var/home/powpingdone/extern/miogenes/frontend/lib/mainpage/toplevel.dart"  
  }
}
```

This automatically will fix itself after editing the buffer, but it will re-appear upon saving. 

## Dart info
```md
#### General info

- Dart 3.1.1 (stable) (Tue Sep 5 12:20:14 2023 +0000) on "linux_x64"
- on linux / Linux 6.4.14-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep  2 16:36:06 UTC 2023
- locale is C.UTF-8

#### Process info

| Memory |  CPU | Elapsed time | Command line                                               |
| -----: | ---: | -----------: | ---------------------------------------------------------- |
| 537 MB | 0.6% |        29:17 | dart language-server --protocol=lsp --diagnostic-port=8084 |
```

[dart_analyzer_diagnostics_report.json](https://github.com/dart-lang/sdk/files/12566410/dart_analyzer_diagnostics_report.json.txt)

NOTE: This was using `akinsho/flutter-tools.nvim` on Neovim 0.9.1 to load the dart language server.

**Comment by bwilkerson** [comment]
Is the file inside the directory that's open in the IDE? Is it excluded from analysis in the `analysis_options.yaml` file?

**Comment by powpingdone** [comment]
Yes. The file is the one currently open, and the `analysis_options.yaml` has no such exclusion.

```yaml
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
```
