### ISSUE TITLE
support a comment syntax to allow for ignoring lints in pubspec.yaml files

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#53565]
See https://github.com/dart-lang/lints/issues/59#issuecomment-1726209345; we have lints for pubspec files, but no way to allow the user to ignore lints for specific diagnostics. We should have the equivalent of `// ignore: foo_bar` for dart files.

```yaml

dev_dependencies:
  collection: ^1.17.0
  # ignore: foo_bar_pub_lint
  http: ^1.0.0
  path: ^1.8.0
  yaml: ^3.1.0
```
