### ISSUE TITLE
Using `dart run` conflicts with `flutter pub get`

### ISSUE THREAD

**Issue by ziqq** [dart-lang/sdk#53696]
Every time after running `dart run build_runner build --delete-conflicting-outputs` command you have to run `flutter pub get` to remove the error below.

<img width="704" alt="image" src="https://github.com/dart-lang/build/assets/20646071/ade27df0-1e94-43bc-bece-c6a1f78104a2">

**Comment by natebosch** [comment]
I think this is because `dart run build_runner` runs a `dart pub get`.

`dart pub get` conflicts with `flutter pub get` because the latter creates a synthetic `package:flutter_gen` into the solve.

cc @mit-mit

**Comment by jakemac53** [comment]
I didn't think you could do a `dart pub get` inside of a flutter package?

**Comment by ziqq** [comment]
> I think this is because `dart run build_runner` runs a `dart pub get`.
> 
> `dart pub get` conflicts with `flutter pub get` because the latter creates a synthetic `package:flutter_gen` into the solve.
> 
> cc @mit-mit

Yep `flutter run build_runner` working fine, but `build_runner` requires `dart run build_runner`

<img width="395" alt="image" src="https://github.com/dart-lang/sdk/assets/20646071/6b10763e-7ad0-4d80-8b5c-4f720d2e1525">

**Comment by mit-mit** [comment]
cc @jonasfj @sigurdm

**Comment by sigurdm** [comment]
Yeah - this is a real problem.

A workaround is to run `flutter pub get` first to create the flutter_gen package.

But we should really find a solution for the flutter_gen package (either avoid it, or create proper support for it in pub) it keeps on creating problems in different places.

@christopherfujino I recently mentioned that we should look into this soon.

**Comment by lucavenir** [comment]
As mentioned in [here](https://github.com/dart-lang/build/issues/2835) the conflicts stands because flutter might generate (or not) l10 files.

Personally I stumbled on this because I've generated files in a custom folder with the following l10n configuration:
```yaml
arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/gen
synthetic-package: false
nullable-getter: false
```

If it can help, there are two workarounds:

1. Run `packages get` instead of just `get`, aka:
```shell
flutter clean && flutter pub get && dart run build_runner build -d
```
2. Just add `flutter_gen` as a dev dependency - idk why, but it works (probably this package is used somewhere in between the chain, or maybe one of its inner dependencies, idk)

**Comment by bwilkerson** [comment]
@jacob314 FYI

**Comment by dovahkrid** [comment]
> Hi and thx everyone, my problem is resolved in `Flutter 3.16.1`. Now `dart run build_runner` work correctly.

I'm on Flutter 3.16.5 and still got this issue

**Comment by markbeij** [comment]
@natebosch can we reopen this issue?

**Comment by rydmike** [comment]
Using `Flutter 3.16.9` and a setup very much like https://github.com/dart-lang/sdk/issues/53696#issuecomment-1833593144 with its `l10n.yaml´ file.

I'm having this issue as well. The weird workaround (option 2) of adding `flutter_gen` as a dev dep, worked for me too, using it as temp workaround for now.

**Comment by ziqq** [comment]
I stopped receiving this error message, unfortunately I don’t remember exactly what led to this, but here is my configuration.

Flutter: `3.19.1`

<details>
  <summary>l10n.yaml</summary>
  
  ``` yaml
arb-dir: lib/src/core/localization/translations
template-arb-file: app_en.arb
output-localization-file: app_localizations.g.dart
preferred-supported-locales:
  - en

nullable-getter: false
use-deferred-loading: true
  ```
</details>

<details>
  <summary>Command</summary>
  
  ``` yaml
  dart --disable-analytics && dart run build_runner build --delete-conflicting-outputs --release
  ```
</details>

**Comment by ziqq** [comment]
If any more can't catch this error, then i think maybe close this issue.

**Comment by rydmike** [comment]
I will check with my case as on Flutter `3.19.1` as well, I'll be back soon.

**Comment by rydmike** [comment]
Tested with Flutter `3.19.1`. No change, still fails.

If I remove the known workaround of having `flutter_gen:` as a dev dependency, build runner fails as before, with error:


```console
Unhandled exception:
Bad state: Unable to generate package graph, no `/Users/rydmike/dev/code/talo/.dart_tool/flutter_gen/pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:268:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:242:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:120:33)
<asynchronous suspension>
#3      main (file:///Users/rydmike/.pub-cache/hosted/pub.dev/build_runner-2.4.8/bin/build_runner.dart:27:30)
<asynchronous suspension>
```

My `l10n.yaml` file:

```yaml
arb-dir: lib/core/localization/translations
template-arb-file: app_en.arb
output-dir: lib/core/localization/generated
nullable-getter: false
synthetic-package: false
use-deferred-loading: true
```

Putting `flutter_gen` back, fixes the issue, and build runner works again.
