### ISSUE TITLE
Update "Import library" correction to account for linter rules

### ISSUE THREAD

**Issue by Mike278** [dart-lang/sdk#53819]
Dart SDK version: 3.3.0-48.0.dev (dev) (Fri Oct 20 09:02:07 2023 -0700) on "windows_x64"

Steps to reproduce:

- Create a new dart project
- Replace the contents of `analysis_options.yaml` with
```yaml
linter:
  rules:
    prefer_relative_imports: false
    avoid_relative_lib_imports: true # Probably redundant
    always_use_package_imports: true # Probably redundant
```
- Create a new file `lib/foo.dart` with contents `const hello = 'world';`
- Create a new file `lib/bar.dart` with contents `const greeting = hello;`
- Open the project in IntelliJ and enable Dart support (I haven't tested this in any other editor)
- Navigate to `lib/bar.dart`, place the cursor on `hello`, and generate suggestions with alt+enter
- Expected: `Import library 'package:import_bug/foo.dart'` is the first (and ideally, only) suggestion 
- Actual: 
![image](https://github.com/dart-lang/sdk/assets/17344144/b3fc2241-5b8f-42ad-9d7e-b7169c0d5d5f)

[This function](https://github.com/dart-lang/sdk/blob/7d66c0ed53933c855764b93b909748b54bd439bd/pkg/analysis_server/lib/src/services/correction/dart/import_library.dart#L224) seems to suggest the order depends on the value of `prefer_relative_imports`, but changing this value doesn't change the order.

Might be related to https://github.com/dart-lang/sdk/issues/32916 where support for relative imports was added?
