### ISSUE TITLE
[native_assets][ffi] Make `build.dart` path configurable

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54111]
@mit-mit proposed the idea of using `build.dart` for other things besides native assets.
Apparently, users are already doing this: https://github.com/flutter/flutter/issues/138727#issuecomment-1820571783

This means the native assets feature needs to know whether to run not based on the existence of a top-level `build.dart`, but instead on a pubspec config.
Moreover, we might want to then also support running a script with a different name.

Possible pubspec config:

```yaml
native_assets: #optional
  build: build.dart #optional
  link: link.dart #optional
```
