### ISSUE TITLE
[dart fix] inEnum does not apply transform

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#54188]
I want to rename a deprecated enum value in https://github.com/flutter/flutter/pull/139257

For example:

```dart
enum WidgetInspectorServiceExtensions {
  @Deprecated(use add instead)
  setPubRootDirectories,
  addPubRootDirectories,
  // ...
}
```

I wrote the following rule to try to rename uses of the deprecated enum:

```yaml
  - title: "Use WidgetServiceExtensions.addPubRootDirectories"
    date: 2023-11-29
    element:
      uris: ['widgets.dart', 'material.dart', 'cupertino.dart']
      enum: 'setPubRootDirectories' # also tried constant?
      inEnum: 'WidgetInspectorServiceExtensions'
    changes:
    - kind: 'rename'
      newName: 'addPubRootDirectories'
```

The transformation I expected in the test was:
```dart
// Before
WidgetInspectorServiceExtensions.setPubRootDirectories;

// After
WidgetInspectorServiceExtensions.addPubRootDirectories;
```

But nothing happened.
This is the first `inEnum` fix for the framework, so there could be a bug?
The [docs](https://github.com/flutter/flutter/wiki/Data-driven-Fixes#element) mention `enum` or `constant` for the element when using `inEnum`, neither of those worked. I tried `field` as well for good measure.
