### ISSUE TITLE
Declarations tracking is done twice at LSP startup and is slow with large build folders

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#54513]
I've been investigating slow server startup performance in https://github.com/dart-lang/sdk/issues/52947. We had some theories that the slow startup was due to file watchers (because it gets worse with larger .dart_tool/build folders) but they might not be the culprit.

Looking at the [directory listing sent to me](https://github.com/dart-lang/sdk/issues/52947#issuecomment-1875924441) I found the build folder has 54,000 items, most of which seem related to compiling plugins for Android. I created a Flutter app the the following set of dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter
  background_fetch:
  firebase_analytics:
  firebase_app_check:
  firebase_core:
  firebase_crashlytics:
  firebase_messaging:
  firebase_remote_config:
  flutter_local_notifications:
  flutter_native_splash:
  flutter_secure_storage:
  google_mobile_ads:
  home_widget:
  iabtcf_consent_info:
  in_app_purchase_android:
  in_app_review:
  package_info_plus:
  path_provider_android:
  posthog_flutter:
  sensors_plus:
  share_plus:
  url_launcher_android:
  video_player_android:
  webview_flutter_android:
```

And then I ran/compiled the app in debug, profile and release mode. I ended up with 33,000 items and around 12 seconds attributed to the `initialized` event in the server diagnostic pages. Adding additional logging did not show time attributed to watchers, but rather various other parts of the startup.

Using a script to start the server with the VM service enabled and then pausing to allow me to attach the CPU profiler before initialisation, I got the following flame chart. It appears to show that we're setting up the declarations tracker twice (once as we set up the contexts, and then again after we've created all contexts). This work also seems to be very slow when the build server is large.

![image](https://github.com/dart-lang/sdk/assets/1078012/ad80748b-3542-469b-a720-cd927f55ce95)

For comparison, if I delete the build folder, the time shown against the initialize notification is less than 2s instead of 12. (it's not clear to me why the CPU profiler seems to report around 8s when I consistently see 12 in the diagnostic pages, but I can't easily get both timings from the same run).
