### ISSUE TITLE
_fe_analyzer_shared issue on version 3.4.0-24.0.dev

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#54643]
Hitting this issue with the SDK downloaded from archive, version `3.4.0-24.0.dev`, on Linux:

```
Bad state: Expected an int but found a DataKind.oneByteString
#0      ByteDataDeserializer._expectInt (package:_fe_analyzer_shared/src/macros/executor/serialization.dart:521:9)
#1      ByteDataDeserializer.expectInt (package:_fe_analyzer_shared/src/macros/executor/serialization.dart:477:22)
#2      DeserializerExtensions.expectRemoteInstance (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:9:14)
#3      DeserializerExtensions._expectIdentifierMetadataAnnotation (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:293:21)
#4      DeserializerExtensions.expectRemoteInstance (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:51:28)
#5      DeserializerExtensions._expectClassDeclaration (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:265:21)
#6      DeserializerExtensions.expectRemoteInstance (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:28:28)
#7      RemoteInstance.deserialize (package:_fe_analyzer_shared/src/macros/executor/remote_instance.dart:46:34)
#8      new ExecutePhaseRequest.deserialize (package:_fe_analyzer_shared/src/macros/executor/protocol.dart:293:33)
#9      new ExecuteDeclarationsPhaseRequest.deserialize (package:_fe_analyzer_shared/src/macros/executor/protocol.dart:332:15)
#10     MacroExpansionClient._handleMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/executor/client.dart:133:19)
```

**Comment by jakemac53** [comment]
> Hitting this issue with the SDK downloaded from archive, version `3.4.0-24.0.dev`, on Linux:

Most likely, this is a version mismatch issue between your running analyzer version (via analysis server presumably?) and the local version solve you have in your package. Specifically, it would be the `_fe_analyzer_shared` version.

**Comment by jakemac53** [comment]
You can use git or path dependencies to depend on _fe_analyzer_shared from the SDK that you are using to work around this.

**Comment by jakemac53** [comment]
We also might want to consider at what point it makes sense to get the real dependencies published here, exporting directly some dart: APIs from the SDK, which won't have this problem.

**Comment by jakemac53** [comment]
I am going to close this for now at least, but lmk if you need help setting up the git or path deps.

**Comment by jwren** [comment]
Still hitting the issue, my pub.lock file reads:

```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: "direct main"
    description:
      name: _fe_analyzer_shared
      sha256: "36a321c3d2cbe01cbcb3540a87b8843846e0206df3e691fa7b23e19e78de6d49"
      url: "https://pub.dev"
    source: hosted
    version: "65.0.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: d584fa6707a52763a52446f02cc621b077888fb63b93bbcb1143a7be5a0c0c04
      url: "https://pub.dev"
    source: hosted
    version: "1.11.0"
sdks:
  dart: ">=3.4.0-edge <4.0.0"
```

This is using a downloaded SDK, or using a locally built SDK.

**Comment by DanTup** [comment]
I don't think those packages on Pub are new enough. I'm using a `pubspec.yaml` with overrides that just point back at my local SDK checkout:

```
# Override to the latest version of the in progress api.
dependency_overrides:
  _fe_analyzer_shared:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/_fe_analyzer_shared
  _js_interop_checks:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/_js_interop_checks
  analyzer:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/analyzer
  build_integration:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/build_integration
  compiler:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/compiler
  dart2js_info:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/dart2js_info
  dart2wasm:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/dart2wasm
  dev_compiler:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/dev_compiler
  front_end:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/front_end
  frontend_server:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/frontend_server
  js_ast:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/js_ast
  js_runtime:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/js_runtime
  js_shared:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/js_shared
  kernel:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/kernel
  mmap:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/mmap
  vm:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/vm
  wasm_builder:
    path: C:/Dev/Google/dart-sdk/sdk/pkg/wasm_builder
```

(I took this from [the example here](https://github.com/dart-lang/language/blob/main/working/macros/example/pubspec.yaml) but changed to a local SDK so it wasn't cloning another copy during `pub get`!)
