### ISSUE TITLE
Package executable fails when activated from local path.

### ISSUE THREAD

**Issue by schultek** [dart-lang/sdk#55216]
I'm trying to activate a local package and then run the executable. This works fine on macos (local and ci) and windows (local), but fails in windows ci (github actions) with:

`'l' is not recognized as an internal or external command, operable program or batch file.`

This is my ci workflow, which also contains the commands to reproduce this issue:

```yaml
on:
  workflow_dispatch:
  push:
    branches:
      - wintest
    paths:
      - '.github/workflows/test_win.yml'

name: Test Pipeline

jobs:
  test1:
    name: Global Cli Test
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - name: Run
        run: |
          dart create -t cli cli_test
          echo "executables:\n  cli_test:" >> cli_test/pubspec.yaml
          dart pub global activate cli_test --source=path
          dart pub global run cli_test --version

  test2:
    name: Standalone Cli Test
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - name: Run
        run: |
          dart create -t cli cli_test
          echo "executables: {cli_test: }" >> cli_test/pubspec.yaml
          dart pub global activate cli_test --source=path
          cli_test --version
```

It defines two jobs and their only difference is using either

`dart pub global run cli_test --version`

or

`cli_test --version`

to execute the package.

The first one works fine, the second one fails with the above error.

See the full error log here: https://github.com/schultek/jaspr/actions/runs/8317209836

I suspect this is something todo with how dart links or runs these activated executables, but I couldn't find anything useful.
