### ISSUE TITLE
Dart fix not working with part files if the main file has nothing to fix

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#55520]
I got back to work in [this package](https://github.com/FMorschel/floating_overlay) I've created.

And nowadays I use a different `analysis_options.yaml`.

<details>

<summary> Here is the new full file </summary>

```yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/generated_plugin_registrant.dart"
    - "**.g.dart"
  errors:
    missing_required_param: error

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_double_and_int_checks: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    empty_constructor_bodies: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    noop_primitive_operations: true
    prefer_collection_literals: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    void_checks: true

dart_code_metrics:
  rules:
    - double-literal-format
    - format-comment
    - member-ordering-extended:
        alphabetize: false
        order:
          - constructors
          - named-constructors
          - factory-constructors
          - static-getters-setters
          - static-const-public-fields
          - static-const-private-fields
          - static-final-public-fields
          - static-final-private-fields
          - static-late-final-public-fields
          - static-late-final-private-fields
          - static-late-public-fields
          - static-late-private-fields
          - static-public-fields
          - static-private-fields
          - const-public-fields
          - const-private-fields
          - final-public-fields
          - final-private-fields
          - late-final-public-fields
          - late-final-private-fields
          - late-public-fields
          - late-private-fields
          - public-fields
          - private-fields
          - overridden-public-fields
          - overriden-public-methods
          - static-public-methods
          - static-private-methods
          - public-methods
          - private-methods
          - getters-setters
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-immediate-return
    - prefer-last

    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets:
        ignored-names:
          - testFunction
        ignored-annotations:
          - allowedAnnotation
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
```

</details>

After changing that and running pub upgrade I did the following:

- Running `dart --version`

```
Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "windows_x64"
```

- Running `dart fix --dry-run`

```
Computing fixes in floating_overlay (dry run)...

14 proposed fixes in 7 files.

lib\src\cursor_resizing.dart
  unused_element • 1 fix
  use_super_parameters • 1 fix

lib\src\floating_overlay.dart
  directives_ordering • 1 fix
  use_super_parameters • 1 fix

lib\src\floating_overlay_controller.dart
  prefer_int_literals • 2 fixes

lib\src\floating_overlay_offset.dart
  unnecessary_parenthesis • 1 fix

lib\src\floating_overlay_scale.dart
  prefer_int_literals • 3 fixes

lib\src\reposition.dart
  unused_element • 1 fix
  use_super_parameters • 1 fix

lib\src\rescale.dart
  unused_element • 1 fix
  use_super_parameters • 1 fix

To fix an individual diagnostic, run one of:
  dart fix --apply --code=directives_ordering 
  dart fix --apply --code=prefer_int_literals 
  dart fix --apply --code=unnecessary_parenthesis 
  dart fix --apply --code=unused_element 
  dart fix --apply --code=use_super_parameters 

To fix all diagnostics, run:
  dart fix --apply
```

- Running one of the suggested fixes: `dart fix --dry-run --code=unnecessary_parenthesis`

```
Computing fixes in floating_overlay (dry run)...
Nothing to fix!
```

### Edit

Tested in two different machines. Maybe is something in my project but I'm not sure haven't tested it with other projects yet.

### Edit 2

Created a bare new project with the default counter app and added those same options. It warned me about `always_put_required_named_parameters_first` and I gave it a run, it worked. I'm not sure what is different in that project.

**Comment by bwilkerson** [comment]
I don't know for sure why you're seeing the behavior you're seeing, but I can think of one possibility that I'll mention for anyone that might look into addressing this issue.

`dart fix` (effectively) runs the analyzer over the code to be fixed looking for diagnostics that it knows how to fix. If it finds any it applies the fixes and then loops back to re-analyze the code and see whether there are any new diagnostics that could be fixed. When there are no more fixable diagnostics being reported it prints out (or applies) the changes that were found.

The effect of the `--code` option is that only diagnostics with the given name are fixed on any given iteration of the loop.

It's quite possible that the `unnecessary_parenthesis` diagnostics weren't reported on the first run (because all of the parentheses were required at that point) and that it wasn't until one of the other diagnostics was fixed that it became possible to remove some of the parentheses in the code. But when you specified the code the (hypothetical) other diagnostic wasn't fixed, so there was no `unnecessary_parenthesis` diagnostic to fix.

This is still a poor UX that needs to be supported, but I think I've explained one possible path to reproducing the problem.

**Comment by FMorschel** [comment]
That would not explain why does 

```
dart fix --apply --code=prefer_int_literals
```

would not run since inside `lib/src/floating_overlay_controller.dart` in line 40 there is a "1.0" written and the output is the same: `nothing to fix`.

Also, I've reviewed and inside `lib/src/floating_overlay_offset.dart` in line 78 there is currently an unnecessary parenthesis. So what you said might be a problem for someone else, but it's not my case, unfortunately.

**Comment by FMorschel** [comment]
I've tested all of the suggested code fixes with `dry-run` and only `directives_ordering` (1st suggestion) and `use_super_parameters` (last suggestion) find something to run.

**Comment by FMorschel** [comment]
I think I got it. All my other files are parts of that `lib/floating_overlay.dart` file. 

Since it could not find any problems (of all other codes specifically) inside that one file, maybe it didn't go to any other file?

**Comment by FMorschel** [comment]
Yes, that was it.

Create a base empty dart project and add `prefer_int_literals` to `analysis_options.yaml`:

```yaml
linter:
  rules:
    prefer_int_literals: true
```

In `main.dart`:

```dart
part 'b.dart';

class A {
  const A(this.a);

  final double a;
}

void a() {
  const A(1.0);
}
```

In `b.dart`:

```dart
part of 'main.dart';

class B extends A {
  const B() : super(2.0);
}
```

Run `dart fix --dry-run`:

```
Computing fixes in bug (dry run)...

2 proposed fixes in 2 files.

lib\b.dart
  prefer_int_literals • 1 fix

lib\main.dart
  prefer_int_literals • 1 fix

To fix an individual diagnostic, run one of:
  dart fix --apply --code=prefer_int_literals

To fix all diagnostics, run:
  dart fix --apply
```

Now, comment out/remove the second to last line in `main.dart` and run it again:

```
Computing fixes in bug (dry run)...
Nothing to fix!
```
