### ISSUE TITLE
Dart 3.3.4 docker error

### ISSUE THREAD

**Issue by aquinary** [dart-lang/sdk#55598]
I use docker-compose.yml:

The first time I run, I create a project:
```yaml
  generator:
    image: dart:3.3.4
    container_name: am-generator
    working_dir: /app
    volumes:
      - ../services/generator:/app
    command: ["dart", "create", "-t", "console", ".", "--force"]
    depends_on:
      db_olap:
        condition: service_healthy
```
The second launch I change the command to `command: ["dart", "run"]` and get errors:
```
am-generator  | Could not find a file named "pubspec.yaml" in "/root/.pub-cache/hosted/pub.dev/_fe_analyzer_shared-67.0.0".
am-generator  | #0      new Pubspec.load (package:pub/src/pubspec.dart:224:7)
am-generator  | #1      new Package.load (package:pub/src/package.dart:131:29)
am-generator  | #2      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:180:36)
am-generator  | <asynchronous suspension>
am-generator  | #3      Entrypoint.resolveExecutable (package:pub/src/entrypoint.dart:556:8)
am-generator  | <asynchronous suspension>
am-generator  | #4      getExecutableForCommand (package:pub/src/executable.dart:350:16)
am-generator  | <asynchronous suspension>
am-generator  | #5      RunCommand.run (package:dartdev/src/commands/run.dart:349:20)
am-generator  | <asynchronous suspension>
am-generator  | #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
am-generator  | <asynchronous suspension>
am-generator  | #7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:18)
am-generator  | <asynchronous suspension>
am-generator  | #8      runDartdev (package:dartdev/dartdev.dart:57:16)
am-generator  | <asynchronous suspension>
am-generator  | #9      main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
am-generator  | <asynchronous suspension>
am-generator  | 
am-generator exited with code 1
```
