### ISSUE TITLE
Improve solve traces when packages are from workspaces

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#56514]
With a workspace containing a and b:

```yaml
name: b
environment: 
  sdk: ^3.5.0-259.0.dev
resolution: workspace
```

Then, inside A, I tried to depend on B with:

```yaml
name: a
environment: 
  sdk: ^3.5.0-259.0.dev
resolution: workspace
dependencies:
  b: ^1.0.0
```

But got:

```
Because _ depends on a which depends on b ^1.0.0, b ^1.0.0 is required.
So, because _ depends on b, version solving failed.
```

Maybe we could improve the `pub get` error message when the constraint issue point to a package from the workspace?

Such as:

```
Because A depends B ^1.0.0 from workspace, B ^1.0.0 is required.
Because B from workspace has no version, no B ^1.0.0 version is found.
So, because A depends on B, version solving failed
```
