### ISSUE TITLE
dart/runtime/vm/kernel_binary.h: 435: error: Legacy nullability is not supported.

### ISSUE THREAD

**Issue by LefebvreIlyas** [dart-lang/sdk#56548]
Hello 

After updating to Flutter 3.24.0, which uses Dart 3.5, I now get the error “Legacy nullability is not supported.

I'm creating the ticket here because I think it's really language specific.

I don't think it's due to a bug in the SDK or Flutter tooling but rather due to a dependency of a package I use in all my projects, because without it, the code compiles. I can't find the problem. I've tried deleting some dependencies and trying to compile, sometimes it ends up working and sometimes it doesn't (with dependencies for which it worked in previous tests and vice versa). 
All dependencies are marked `Compatible with Dart 3`. I've also been unable to produce a minimal example reproducing the error.

What exactly is the meaning of this error and what approach should be taken when it occurs?

**The error**
```
[  +11 ms] √ Built build\windows\x64\runner\Debug\application.exe
[+3061 ms] VM Service URL on device: http://127.0.0.1:56742/ZEzGNwrISD8=/
[   +1 ms] Caching compiled dill
[  +41 ms] Connecting to service protocol: http://127.0.0.1:56742/ZEzGNwrISD8=/
[  +54 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:56742/ZEzGNwrISD8=/.
[   +3 ms] ../../../flutter/third_party/dart/runtime\vm/kernel_binary.h: 435: error: Legacy nullability is not supported.
[        ] version=3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "windows_x64"
[        ] pid=8600, thread=13368, isolate_group=main(00000177FE22D0B0), isolate=(nil)(0000000000000000)
[        ] os=windows, arch=x64, comp=no, sim=no
[        ] isolate_instructions=7fff872fc640, vm_instructions=7fff872fc650
[        ] fp=50d0ffdbe8, sp=50d0ffdbe8, pc=7fff870ebad2
[   +6 ms]   pc 0x00007fff870ebad2 fp 0x00000050d0ffdbe8 InternalFlutterGpu_Texture_AsImage+0x12bc76
[        ] -- End of DumpStackTrace
[ +697 ms] Warning: Failed to start DDS: Failed to start Dart Development Service
[        ] Fail to connect to service protocol: http://127.0.0.1:56742/ZEzGNwrISD8=/: DartDevelopmentServiceException: Failed to start Dart Development Service
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:56742/ZEzGNwrISD8=/
```

**The dependencies**
```yaml
environment:
  sdk: '>=3.5.0 <4.0.0'

  flutter: '>=3.10.0'

dependencies:
  after_init: ^0.2.0

  after_layout: ^1.2.0

  alice: ^1.0.0-dev.10

  alice_dio: ^1.0.4

  alice_http: ^1.0.4

  app_localizations:

  auto_route: ^8.3.0

  auto_size_text: ^3.0.0

  expandable_page_view: ^1.0.17

  file: ^7.0.0

  file_picker: ^8.0.7

  fl_chart: ^0.68.0

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6

  flutter_colorpicker: ^1.1.0

  flutter_ioc_container: ^1.0.12

  flutter_json_view: ^1.1.5

  flutter_localizations:
    sdk: flutter

  flutter_speed_dial: ^7.0.0

  flutter_sticky_header: ^0.6.5

  flutter_svg: ^2.0.10+1

  flutter_typeahead: ^5.2.0

  form_builder_validators: ^11.0.0

  go_router: ^14.2.3

  graphview: ^1.2.0

  html: ^0.15.4

  html_editor_enhanced: ^2.6.0

  js: ^0.7.1

  keyboard_actions: ^4.2.0

  package_info_plus: ^8.0.1

  path_provider: ^2.1.4

  posthog_flutter: ^4.5.0

  provider: ^6.1.2

  responsive_builder: ^0.7.1

  screenshot: ^3.0.0

  sentry_flutter: ^8.7.0

  # shared_preferences: ^2.3.1

  signature: ^5.5.0

  spaces:
    git: https://github.com/LefebvreIlyas/spaces

  syncfusion_flutter_datagrid: ^26.2.10

  talker_flutter: ^4.4.0

  tinycolor2: ^3.0.1

  transparent_image: ^2.0.1

  two_dimensional_scrollables: ^0.3.1

  universal_html: ^2.2.4

  universal_io: ^2.2.2

  universal_platform: ^1.1.0

  url_launcher: ^6.3.0

  url_strategy: ^0.3.0

  video_player: ^2.9.1

  web: ^0.5.1

dependency_overrides:
  # Required by flutter_inappwebview_web used by html_editor_enhanced
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
```
