### ISSUE TITLE
Macros: Serialisation issue from different file

### ISSUE THREAD

**Issue by varunbhalerao56** [dart-lang/sdk#56646]
#### 1. Create a Flutter project with macros enabled, in the Flutter and Dart versions mentioned below.

> flutter & dart version
```
Flutter 3.25.0-1.0.pre.252 • channel master • https://github.com/flutter/flutter.git
Framework • revision ab143f147e (2 hours ago) • 2024-09-04 05:12:25 -0400
Engine • revision 68214414d3
Tools • Dart 3.6.0 (build 3.6.0-198.0.dev) • DevTools 2.39.0
```

#### 2. Enable the macros.

> pubspec_yaml
```
environment:
    sdk: ">=3.6.0-0 <4.0.0"

...

dependencies:
    json: ^0.20.2

```

> analysis_options.yaml
```
include: package:flutter_lints/flutter.yaml

analyzer:
    errors:
        non_nullable_equals_parameter: ignore
    enable-experiment:
        - macros
        - enhanced-parts

```
`enhanced-parts` will be required now due to the following https://github.com/dart-lang/language/pull/4072

#### 3. Create two files `model.dart` and `model_two.dart`

(check code in code sample)

#### 4. Run

After running to project and hot reloading it. The following error will appear.

```
lib/playground/model.dart:14:9: Error: Unable to deserialize type, it must be a native JSON type or a type with a `fromJson(Map<String, Object?> json)` constructor.
  final TestTwo testTwo;
        ^
lib/playground/model.dart:14:9: Error: Unable to serialize type, it must be a native JSON type or a type with a `Map<String, Object?> toJson()` method.
  final TestTwo testTwo;
        ^
Restarted application in 1,592ms.
```

## Issue

But currently the model that is being imported from the `model_two.dart` file gives a the serialization error. 

The same model when placed in the same file as `model.dart` does not give the error. The error only seems to occur on models that are being imported from outside files. 

`MainModel` contains `TestOne` model which is located in the `model.dart` file and a `TestTwo` model which is located in the `model_two.dart` file. The error is only given on the `TestTwo` model.

## Code Sample

<details open><summary>Code sample</summary>

> model.dart
```dart
import 'package:json/json.dart';
import 'package:np_combine/model_two.dart';

@JsonCodable()
class TestOne {
  String name;
  int age;
  TestOne({required this.name, required this.age});
}

@JsonCodable()
class MainModel {
  final TestOne testOne;
  final TestTwo testTwo;

  MainModel({required this.testOne, required this.testTwo});
}
```

> model_two.dart
```dart
import 'package:json/json.dart';

@JsonCodable()
class TestTwo {
  String name;
  int age;
  TestTwo({required this.name, required this.age});
}
```

</details>
