### ISSUE TITLE
Move class to file not considering `directives_ordering`

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56657]
Reproduce:

1. Create an empty project
2. Make sure under `analysis_options.yaml` you have `directives_ordering: true`
3. Add some dependency (eg `Equatable`)
4. Under `main.dart` create `class A {}` and `abstract class C extends A with EquatableMixin {}`
5. Move `C` to a new file under a folder `f`
6. See the output:

```dart
import '../main.dart';
import 'package:equatable/equatable.dart';  // <- directives_ordering

abstract class C extends A with EquatableMixin {}
```

---

// CC: @DanTup 

### Edit

My `main.dart` was written as `bug.dart` that's why the bot wrote it that way.

--- 

This should only apply when in `analysis_options.yaml`:

```yaml
linter:
  rules:
    directives_ordering: true
    always_use_package_imports: false
    prefer_relative_imports: true
```

When using package imports it sorts them alphabetically and it should be right.
