### ISSUE TITLE
[analyzer] Missing/incorrect completion for analysis_options (in some cases)

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#57077]
Hi, this is probably related to yaml parser, but still.

1. When invoking the completion suggestions manually (in my case, `option + esc`), top level entries are suggested even when they are already in the list:
  <img width="475" alt="Screenshot 2024-11-13 at 14 15 16" src="https://github.com/user-attachments/assets/07bb3982-ea99-4d71-aaa5-4432927a1104">

  To reproduce:
  ```yaml
  analyzer:
    // <-- call the completion here
    exclude:
  ```
2. Typing anything under the first entry (when there are other entries below it) does not trigger the completion at all
```yaml
analyzer:
  // <-- start typing here
  exclude:
```
<img width="291" alt="Screenshot 2024-11-13 at 14 17 03" src="https://github.com/user-attachments/assets/d563a115-dde6-493e-a0e8-82ed8a5c2802">

Expected suggestions:
<img width="327" alt="Screenshot 2024-11-13 at 14 17 20" src="https://github.com/user-attachments/assets/5fc57feb-2e17-4073-9fe1-2a4b0ffc08f3">
