### ISSUE TITLE
pubspec: detect two identical keys

### ISSUE THREAD

**Issue by guillermooo** [dart-lang/sdk#57187]
I think pubspec-related linting is going to be handled by `linter`. If so, it could detect cases like this:

```
name: dart_sample_console
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  semver: '>=1.0.0 <2.0.0'
  semver: '>=0.1.0 <1.0.0'
dev_dependencies:
  unittest: any
```

However, I'm not sure how `linter` is intended to run (on demand, constantly in the background...). In this particular case, it would be useful if the user got instant feedback, as the analysis server provides for .dart files.
