### ISSUE TITLE
Exclude should take precedence over include in config

### ISSUE THREAD

**Issue by dikmax** [dart-lang/sdk#57246]
In config file:

``` yaml
files:
  include:
    - 'test/**'
  exclude:
    - test/data/**
```

Should process all files in `test` except those in `test/data`.

``` yaml
files:
  include: test/_data/p2/src/ignored/**
  exclude: test/_data/p2/src/ignored/**
```

Should process nothing.

Reason behind is that the only way to exclude small set files from larger set.

Use case: lint all source files except those which were autogenerated. Now it's only possible by manually listing all included files and updating list every time set of files changed.
