### ISSUE TITLE
Excluding rules in config not working

### ISSUE THREAD

**Issue by dikmax** [dart-lang/sdk#57244]
I've added to pubspec.yaml linter options

``` yaml
linter:
  rules:
    style_guide:
      implementation_imports: false
```

Then trying to run linter:

``` bash
 pub run linter --config pubspec.yaml lib/generators/entities_generator.dart
```

It still shows error "Don't import implementation files from another package."
