### ISSUE TITLE
False positive "Specify type annotations"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#57288]
``` dart
@TestOn('vm')
library bwu_ng_quick_nav.test.sample;

import 'dart:async' show Future, Stream;
import 'package:test/test.dart';
import 'package:logging/logging.dart' show Logger, Level;
import 'package:quiver_log/log.dart' show Appender, BASIC_LOG_FORMATTER, PrintAppender;

final Logger _log = new Logger('');

///
void main() {
  Logger.root.level = Level.FINEST;
  Appender appender = new PrintAppender(BASIC_LOG_FORMATTER);
  // ^ ^ ^ ^ ^ ^ 
  // no hint with
  // PrintAppender appender = new PrintAppender(BASIC_LOG_FORMATTER);
  appender.attachLogger(Logger.root);

  group('x', () {
    setUp(() {

    });

    tearDown(() {});

    test('basic', () {
      // set up
      // exercise
      // verification
      expect('', equals(''));
      // tear down
    });
  });
}
```

``` yaml
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_return_types_on_setters
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - public_member_api_docs
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
    - package_names

```
