### ISSUE TITLE
Allow lints to accept configurations

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#57673]
It would be useful and nice to be able to customize some lints with parameter/configuration.

For instance:

```yaml
linter:
  rules:
    - file_headers:
        pattern: '// Copyright 2015 The Chromium Authors. All rights reserved.\n// Use of this source code isgoverned by a BSD-style license that can be\n// found in the LICENSE file.'
    - prefer_const_declarations:
        local_variables: false
```
