### ISSUE TITLE
Add a lint: avoid_circular_package_deps

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#57787]
This would be useful as a lint in a [mono_repo](https://github.com/dart-lang/mono_repo) type package, where you may have several sub-packages inside of a single repository (and sharing a single `analysis_options.yaml`), but want to prevent packages from accidentally having circular dependencies on each other.

Consider:

```yaml
# a/pubspec.yaml
name: a
dependencies:
  // LINT: avoid_ciaruclar_package_deps: Package b (../b) has a dependency on this package.
  b:
```

```yaml
# b/pubspec.yaml
name: b
dependencies:
  // LINT: avoid_ciaruclar_package_deps: Package a (../a) has a dependency on this package.
  a:
```

We might want to allow `dev_dependencies`, since that is normally for tests only.

WDUT @natebosch @kevmoo?
