### ISSUE TITLE
Exclude not working when opening a file

### ISSUE THREAD

**Issue by marius-h** [dart-lang/sdk#57854]
Excluding files in the analyzer options and restarting the server afterwards, hides the errors in those files as intended. However, whenever you open up an excluded file, the errors show up in the console as long as you don't restart the analysis server.

### Steps to reproduce

1. Change your analysis_options.yaml file to look like this:
```yaml
analyzer:
  exclude:
    - lib/**.g.dart # exclude generated JSON models

linter:
  rules:
    - always_specify_types
```
2. Add a file which ends with ".g.dart" and use the 'var' keyword in there.
3. Restart the analysis server => no error shows up; as intended
4. Open up the file you've created in Step 2 => errors show up in the analysis console, despite the file being excluded in analysis_options.yaml

### Environment

- IntelliJ IDEA 2018.3 (Ultimate Edition) Build #IU-183.4284.148
- Dart plugin v183.4733
- Flutter plugin v31.3.4
- Dart VM version: 2.1.0-dev.9.4.flutter-f9ebf21297
- Flutter version: Flutter 1.0.0 revision 5391447fae
