### ISSUE TITLE
`avoid_web_libraries_in_flutter` lint is not detecting plugins correctly

### ISSUE THREAD

**Issue by harryterkelsen** [dart-lang/sdk#58117]
The `avoid_web_libraries_in_flutter` lint attempts to detect if the library is a Flutter web plugin and disable the lint, since `dart:html` is allowed in Flutter web plugins. However, it seems to be detecting:

```yaml
flutter:
  plugin:
    web:
```

when the pubspec syntax for a web plugin is actually:

```yaml
flutter:
  plugin:
    platforms:
      web:
```

The code to try to detect web plugins is here: https://github.com/dart-lang/linter/blob/master/lib/src/rules/avoid_web_libraries_in_flutter.dart#L91

This issue came to my attention here: https://github.com/flutter/flutter/issues/48639
