### ISSUE TITLE
VSCode: '{avoid_print: false}' is not a recognized lint rule

### ISSUE THREAD

**Issue by larssn** [dart-lang/sdk#58519]
**Describe the issue**
`avoid_print` is a real lint rule, but not recognized.

**To Reproduce**
I get this error with the following analysis_options.yaml file:

```
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - use_rethrow_when_possible
    - avoid_print: false
```

**Expected behavior**
I expect it to respect me trying to turn off that lint. :-)
