### ISSUE TITLE
`invariant_booleans` rule showing a false positive on indirect variable change

### ISSUE THREAD

**Issue by alexrintt** [dart-lang/sdk#58678]
**Describe the issue**

> I noticed that this is a duplicated of [#3260](https://github.com/dart-lang/sdk/issues/58669) but this one has no description or details so I'll keep this current issue open.

This is a false positive where the lint warn about a invalid boolean expression that is not invalid.

```dart
class MyClass {
  final List<String> _mylist = ['a', 'b', 'c', 'd', 'a'];

  var _i = 0;

  int _next() => _i++;

  String _current() => _mylist[_i];

  void unexpectedBehaviorSample() {
    if (_current() == 'a') {
      /// ...

      _next(); // Changes the value of `current()` to `b`

      if (_current() != 'a') {
        /// ...
      }

      /// ...
    }
  }
}
```

**To Reproduce**

> Make sure you have setup the environment (See environment section in the next section).

1. [Clone this repository](https://github.com/lakscastro/invariant-booleans-dart-issue) (Reproducible Sample).
2. [Install VS Code](https://code.visualstudio.com/) and [Dart VSCode extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code).
3. Open `lib/main.dart`.

**Expected behavior**

Do not show the false positive warning

**Additional context (Environment)**

- Dart SDK.

```
Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "windows_x64"
```

- Visual Studio Code.

```
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

- `pubspec.yaml` [`lint: ^1.8.2`](https://pub.dev/packages/lint)

```yaml
name: abc
description: "Abc Defghij"
version: 0.1.0
homepage: https://myhomepage.com
repository: https://myrepo.com
issue_tracker: https://myrepo.com/issues
documentation: https://myrepo.com
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:

dev_dependencies:
  lint: ^1.8.2
```

- `analysis_options.yaml`

```yaml
# This file configures the analyzer to use the lint rule set from `package:lint`

# For apps, use the default set
include: package:lint/analysis_options.yaml

# Packages, that may be distributed (i.e. via pub.dev) should use the package
# version, resulting in a better pub score.
# include: package:lint/analysis_options_package.yaml

# You might want to exclude auto-generated files from dart analysis
analyzer:
  exclude:
    #- '**.freezed.dart'

# You can customize the lint rules set to your own liking. A list of all rules
# can be found at https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_use_package_imports: false
    prefer_relative_imports: true
```

- Use Case:

I'm writing a basic programming language where I need to iterable over an **1. array of tokens 2. String (source-code)** as the same way of the above reproducible example.
