### ISSUE TITLE
proposal: dev_only_dependency

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#59079]
## Description

If a package specifies that it is a development only dependency, then you should only include it in the `dev_dependencies` section of your pubspec.yaml, and not the regular `dependencies` section.

The one exception to this rule is if your package is also listed as a development only dependency.

## Details

Some packages, like `lints`, `test`, and `build_runner` should only be depended on as `dev_dependencies` by most users. Adding them to the regular `dependencies` section is not only unnecessary but creates real issues around version lock in the ecosystem, as those dependencies release breaking versions.

As an example, no two packages should fail to version solve together just because they are on a different major version of the `lints` package - those lints only apply for local development of the package.

### New pubspec opt in

This would require the ability to specify a package as "development only". We can bikeshed on what that should be called, but it should probably just be a new top level field in the package, something like:

```yaml
name: my_package
dev_only: true
...
```

## Kind

This guards the ecosystem against version lock and bloated downloads for packages.

## Bad Examples

```yaml
name: my_package
dependencies:
  # These should be `dev_dependencies`.
  lints: <version>
  test: <version> 
```

## Good Examples

```yaml
name: my_package
dev_dependencies:
  lints: <version>
  test: <version> 
```

```yaml
name: flutter_test
dev_only: true
dependencies:
  # Allowed because flutter_test it itself a dev_only dependency
  test: <version> 
```

## Discussion

cc @sigurdm @jonasfj for thoughts on adding something to the pubspec. This may not have to be something official either.

### Discussion checklist

- [ ] List any existing rules this proposal modifies, complements, overlaps or conflicts with.
- [ ] List any relevant issues (reported here, the [SDK Tracker], or elsewhere).
- [x] If there's any prior art (e.g., in other linters), please add references here.
- [ ] If this proposal corresponds to [Effective Dart] or [Flutter Style Guide] advice, please call it out. (If there isn't any corresponding advice, should there be?)
- [ ] If this proposal is motivated by real-world examples, please provide as many details as you can.  Demonstrating potential impact is _especially valuable_.

[Writing Lints]: https://github.com/dart-lang/linter/blob/main/doc/writing-lints.md
[Effective Dart]: https://dart.dev/guides/language/effective-dart
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[SDK Tracker]: https://github.com/dart-lang/sdk/issues
