### ISSUE TITLE
avoid_types_on_closure_parameters false positive

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/sdk#59229]
https://dart.dev/tools/linter-rules/avoid_types_on_closure_parameters has false positives. Consider the following `analysis_options.yaml`:
```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_types_on_closure_parameters
```
The following code:

```dart
void main() {
  final closure = (s) { doSomething(s); };
}

void doSomething(String s) {}
```
triggers the error:
```
The argument type 'dynamic' can't be assigned to the parameter type 'String'.
```
When I change the code so that there is no error:
```dart
void main() {
  final closure = (String s) { doSomething(s); }; // <= Type annotation in closure added.
}

void doSomething(String s) {}
```
it triggers the lint, and seemingly the only way to get rid of it is to add an ignore.

Would it be possible for the lint to be triggered only when the type is not necessary, but when it is, the lint should not be triggered?
