### ISSUE TITLE
Flutter app not runing on ios app

### ISSUE THREAD

**Issue by MumtazAli123** [dart-lang/sdk#59769]
Thank you for taking the time to file an issue! This tracker is for issues related to the Dart analyzer and linter, the Dart core libraries (`dart:async`, `dart:io`, etc.), the Dart native and web compilers, and the Dart VM.

When reporting an issue, please include:

- The Dart version and tooling diagnostic info (`dart info`)
- Whether you are using Windows, macOS, or Linux (if applicable)
- Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Other pieces of the Dart ecosystem are maintained elsewhere; please file issues in their respective repositories:

- Flutter: https://github.com/flutter/flutter
- Dart language: https://github.com/dart-lang/language
- Dart website: https://github.com/dart-lang/site-www
- `dart format`: https://github.com/dart-lang/dart_style
- `dart pub`: https://github.com/dart-lang/pub
- `dart test`: https://github.com/dart-lang/test
- Dart & Flutter DevTools: https://github.com/flutter/devtools

If you have a question, instead of using this issue tracker, please refer to the community resources at: https://dart.dev/community#join-the-conversation.

**Comment by Quving** [comment]
I have the same issue here! :-)

**Comment by gabrieluca** [comment]
Same issue here!

```
Semantic Issue (Xcode): Use of undeclared identifier 'FIRVectorValue'
/Users/gabrieluca/.pub-cache/hosted/pub.dev/cloud_firestore-5.6.0/ios/cloud_firestore/Sources/cloud_firestore/FLTFirebaseFirestoreWriter.m:34:35
```

Specs:
- Flutter `3.27.1`
- `$FirebaseSDKVersion = '10.29.0'` in Podfile.

```yaml
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6
  firebase_remote_config: ^5.2.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  cloud_functions: ^5.2.0
  ```
