### ISSUE TITLE
Difference in output for `DECLARES_INSTANCE_FIELD` in extension and extension type

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#59847]
I was working on https://dart-review.googlesource.com/c/sdk/+/402622 (https://github.com/dart-lang/sdk/issues/59831) and I got to this code:

```dart
extension E on int {
  final int foo = 1, bar = 2;
}
```

Which has a similar case as:

```dart
extension type A(int i) {
  final int foo = 1, bar = 2;
}
```

But we have different outputs here:

To start, the error on `extension type` is a `CompileTimeErrorCode` and the error on `extension` is a `ParserErrorCode`. I'm unsure of what is the differentiation between them but I don't see any semantic differentiation here that would make them different. 

But the problem I opened this to discuss is actually the following:

![image](https://github.com/user-attachments/assets/e4677aee-5ed1-4db4-9434-1261750f3790)

Why do we get more errors on one than on the other? That doesn't seem coherent to me.

CC @bwilkerson @scheglov @srawlins

**Comment by bwilkerson** [comment]
A `ParserErrorCode` is used for errors produced by the parser; a `CompileTimeErrorCode` is used for errors produced by later stages of the compiler. From a semantic perspective they're both errors and hence there's no interesting difference. Both will prevent code from being compiled.

Yes, the differences in reporting these diagnostics is a bit odd. I suspect that the only reason they're different is because they're being reported in different pieces of code written by different people. There's certainly no inherent reason for the differences.

**Comment by bwilkerson** [comment]
The diagnostic `extension_declares_instance_field` is being produced by the `Parser` which is in `sdk/pkg/_fe_analyzer_shared/lib/src/parser/parser_impl.dart`. Search for `messageExtensionDeclaresInstanceField`.

**Comment by FMorschel** [comment]
Here is the CL https://dart-review.googlesource.com/c/sdk/+/407080

**Comment by FMorschel** [comment]
I got an answer from jensjoha that the approach I took was not the best. I'm trying to now convert the existing `ParserErrorCode` to a `CompileTimeErrorCode`. But I'm not sure what should I do at `pkg\front_end\messages.yaml` to `ExtensionDeclaresInstanceField`. I've tried removing `ParserErrorCode.` to make it similar to `EXTENSION_TYPE_DECLARES_INSTANCE_FIELD` below but I got an error that asked for all `analyzerCode`s to have `ParserErrorCode` at the beginning (which I'm a bit confused since just below we have the other error without it):

```yaml
ExtensionDeclaresInstanceField:
  index: 93
  problemMessage: "Extensions can't declare instance fields"
  correctionMessage: "Try removing the field declaration or making it a static field"
  analyzerCode: ParserErrorCode.EXTENSION_DECLARES_INSTANCE_FIELD
  script: |
    extension E on int {
      int? field;
    }

# ...

ExtensionTypeDeclaresInstanceField:
  problemMessage: "Extension types can't declare instance fields"
  correctionMessage: "Try removing the field declaration or making it a static field"
  analyzerCode: EXTENSION_TYPE_DECLARES_INSTANCE_FIELD
  script: |
    extension type ET(int id) {
      int? field;
    }
```

I could simply create the `CompileTimeErrorCode` at `pkg\analyzer\messages.yaml` but then I'm not sure what to do at `pkg\_fe_analyzer_shared\lib\src\parser\parser_impl.dart`. I see that below we have extension types triggering the `CompileTimeErrorCode` I mentioned at the yaml above. But the one for extension is still a `ParserErrorCode` because of the reason mentioned above. Any help with this would be appreciated.
