### ISSUE TITLE
Make `strict-inference` and `strict-raw-types` report as `error` instead of `warning`

### ISSUE THREAD

**Issue by zhenhao-ola** [dart-lang/sdk#59928]
I enabled strict type check as per the [Flutter documentation](https://dart.dev/tools/analysis#enabling-additional-type-checks) in my codebase. However, I found out that not all of them reports as error.

```
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

`strict-casts` will be reported as error, which is wanted behaviour.

However, `strict-inference` and `strict-raw-types` will only report as `warning` in flutter analyze.

Is there any way to make `strict-inference` and `strict-raw-types` report as `error` instead of `warning` ?
