### ISSUE TITLE
Analyzer not working on `analysis_options.yaml` on stable

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#60124]
Create a new Flutter project with the latest stable:

On `analysis_options.yaml` add:

```yaml
lints:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: true
```

This is not triggering `incompatible_lint` which I could see on latest main. Not sure if I'm doing something wrong here but I don't think so.

```
The rule 'always_use_package_imports' is incompatible with the rule 'prefer_relative_imports'.
Try removing one of the incompatible rules.dart(incompatible_lint)
```

CC @DanTup @pq
