### ISSUE TITLE
Incompatible lint doesnt trigger for included yaml

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#60125]
Steps:

1. Create new Dart project
2. Add `very_good_analysis` to dependencies (can be dev)
3. Swap the content of the `analysis_option.yaml` with:

```yaml
include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
  rules:
    prefer_relative_imports: true
```

If you look at https://pub.dev/packages/very_good_analysis they say they prefer the usage of `always_use_package_imports`. But this triggers nothing, only this way you'll have both lints triggering on a loop. I think we either should trigger `incompatible_lint` here or prefer the user manually written lint (prefered IMO).

CC @pq
